// Szpila 2.7 line bank (Polish) for the extra categories from szpila-extra.ts
// (coding, languages and the things people try to cut down on). Merged with
// HARD_27/SOFT_27 in szpila.ts. Same rules: gender-neutral wording, swearing at
// the behaviour, never at who someone is; porn/pervert lines mock, never get
// explicit; "meals" always pushes to EAT. English mirror: szpila-en-27-extra.ts.
import type { Lines27 } from "./szpila-27";
import type { ExtraCategory } from "./szpila-extra";

export const HARD_27X: Record<ExtraCategory, Lines27> = {
  pervert: {
    nag: [
      "Potwierdź, że dziś oczy na wysokości oczu, a nie niżej. To nie jest trudna geometria, kurwa.",
      "Zaznacz, że dziś bez gapienia się na obcych ludzi jak na promocję w Biedronce.",
      "Komplement to „ładnie ci w tym kolorze”, a nie oblizywanie się jak pies. Potwierdź, że dziś kulturalnie.",
      "Bez potwierdzenia zakładam, że w tramwaju znowu odpala się tryb skanera. Zaznacz, jeśli nie.",
      "Nikt nie chce twoich wiadomości o pierwszej w nocy z tekstem „hej, nie śpisz?”. Potwierdź, że dziś nie, do chuja.",
      "Szacunek to nie opcja w ustawieniach. Zaznacz, że dziś był włączony cały dzień.",
      "Ręce przy sobie, komentarze w głowie, a najlepiej w ogóle bez nich. Potwierdź, że dziś czysto.",
      "Nieproszone zdjęcia? Nieproszone uwagi? Nieproszone dotykanie? Zero. Zaznacz, że dziś zero, kurwa.",
      "Myśl głową, nie tym, co masz poniżej pasa. Potwierdź, że dziś mózg miał władzę.",
      "Jak coś byłoby obrzydliwe, gdyby ktoś robił to twojej siostrze albo przyjacielowi, to nie rób tego. Zaznacz, że dziś czysto.",
      "Zboczone żarty w pracy to nie poczucie humoru, to HR. Potwierdź, że dziś bez.",
      "Gapienie się na ludzi na siłowni to nie trening szyi. Zaznacz, że dziś ćwiczysz swoje, a nie patrzysz na cudze.",
      "„Nie” znaczy nie. „Może” też znaczy nie. Cisza znaczy nie. Potwierdź, że dziś rozumiesz, kurwa.",
      "Bez potwierdzenia uznaję, że wyobraźnia znowu ma ruję jak kot w marcu. A ja wiem, co mówię.",
      "Ludzie to nie eksponaty. Patrz, jak na człowieka, i idź dalej. Zaznacz, że dziś się udało.",
      "Wiadomość do kogoś, kto nie odpisuje od tygodnia? Odpuść, do chuja. Potwierdź, że dziś odpuszczone.",
      "Twoje myśli nie muszą od razu lądować w komentarzu pod cudzym zdjęciem. Zaznacz, że dziś bez.",
      "Zachowuj się tak, jakby twoja babcia czytała ci przez ramię. Bo ja czytam. Potwierdź, że czysto.",
      "Oblesie nie mają serii. Ty masz. Potwierdź, że dziś jej nie spierdolisz.",
      "Zimny prysznic, spacer, robota. Byle nie odpierdalanie. Zaznacz, że dziś kultura na poziomie.",
      "Bycie miłym to nie zaproszenie. Zaznacz, że dziś nikt nie musiał przez ciebie zmieniać miejsca w autobusie.",
      "Flirt jest okej, jak jest obustronny. Jednostronny to nękanie. Potwierdź, że dziś wiesz różnicę, kurwa.",
      "Dziś bez dwuznacznych tekstów do koleżanek i kolegów z pracy. Zaznacz, że udało się być normalnie.",
      "Gapisz się tak, że ludzie sprawdzają, czy mają plamę na koszulce. Potwierdź, że dziś nie.",
      "Kot w marcu przynajmniej ma wymówkę. Ty nie masz. Zaznacz, że dziś bez zboczeństw.",
    ],
    praise: [
      "Dzień bez zboczeństw. Ludzie wokół ciebie dziś po prostu żyli w spokoju. Tak ma być.",
      "Czysto. Oczy patrzyły tam, gdzie trzeba, a ręce leżały, gdzie ich miejsce.",
      "Kultura osobista dziś na plusie. Kurwa, aż mi się chce mruczeć.",
      "Zero obleśnych tekstów. Babcia byłaby dumna, a ja jestem lekko zaskoczony.",
      "Dzień z szacunkiem do ludzi. Prosta rzecz, a ile robi różnicy.",
      "Mózg rządził cały dzień, nie hormony. Brawo.",
    ],
    slip: [
      "Znowu zboczeństwo. Ogarnij się i przeproś, jeśli komuś było przez ciebie niezręcznie.",
      "Wpadka. Oczy i łapy znowu robiły swoje, a mózg był na przerwie, kurwa.",
      "Zboczeństwo zaliczone. Jutro patrz ludziom w oczy, a nie gdzie indziej.",
      "Znowu odpierdolone. Zimny prysznic, długi spacer i nauka na błędach.",
      "Wpadka z zachowaniem. Szacunek do ludzi to nie jest dodatek, to podstawa.",
      "Znowu wyobraźnia w krzakach. Jutro trzymaj ją na smyczy, do chuja.",
    ],
    rage: [
      "Ja pierdolę, dalej brak potwierdzenia przy zboczeństwach. Zakładam, że skaner pracuje na pełnej mocy.",
      "Cały dzień milczenia. Podejrzane jak ktoś, kto za długo stoi przy przebieralni. Zaznacz, kurwa.",
      "Potwierdź, że było kulturalnie, albo uznaję wpadkę. Dobra wola się skończyła.",
      "Zero potwierdzenia. Zakładam, że komentarze znowu wyprzedzają myślenie o kilometr.",
      "Kurwa, jedno kliknięcie: „dziś było z szacunkiem”. Chyba że nie było. To się przyznaj.",
      "Milczenie przy „{name}” jest bardziej wymowne niż twoje spojrzenia. Zaznacz.",
      "Brak potwierdzenia. Ogarnij oczy, ręce i myśli, a potem kliknij, do chuja.",
    ],
  },
  coding: {
    nag: [
      "Programowanie: {done} z {target} min. Twój edytor ma więcej uptime'u bez ciebie niż z tobą.",
      "Jeszcze {left} kodu. Nie musi być pięknie, musi się kompilować. A najpierw musi powstać, kurwa.",
      "Ostatni commit: „wip”. Sprzed tygodnia. Ja pierdolę.",
      "Side project umiera w szufladzie jak tamagotchi bez baterii. Odpal edytor.",
      "Trzydzieści minut kodu dziennie i za rok jesteś kimś innym. Ty wolisz być tym samym. Pisz.",
      "Nie musisz pisać od zera całego frameworka. Jedna funkcja. Jeden test. Teraz, do chuja.",
      "Przestań zmieniać motyw w edytorze i zacznij w nim pisać.",
      "Dark mode włączony, kod wyłączony. Klasyka, kurwa.",
      "AI może napisać za ciebie kod, ale nie zrozumie go za ciebie. Siadaj i ogarniaj.",
      "TODO w kodzie mają już swoje TODO. Zrób chociaż jedno.",
      "Repo ma więcej gwiazdek od bota niż commitów od ciebie. Ogarnij się.",
      "Kod nie gryzie. Bugi gryzą, ale tylko te, których nie naprawiasz. Pisz.",
      "Jeszcze {left}. Nawet refaktor jednej brzydkiej funkcji się liczy, do chuja.",
      "Oglądanie konferencji o programowaniu to nie programowanie. Klawiatura, kurwa.",
      "Git status: nic do commita. Życie status: nic do pokazania. Zmień oba.",
      "Pomysł na apkę masz od roku. Pierwszej linijki dalej nie ma. Napisz ją dziś.",
      "Czytanie dokumentacji to połowa roboty. Druga połowa to pisanie kodu. Zrób drugą połowę.",
      "Console.log to też debugowanie. Ale najpierw musi być co debugować, geniuszu.",
      "Jak wyjść z Vima, wiesz. Jak wejść w kod, już nie bardzo. Odpalaj edytor, kurwa.",
      "Twoje umiejętności rdzewieją szybciej niż zależności w starym projekcie. Aktualizuj się.",
      "Nawet mały bugfix to commit. Commit to postęp. Postęp to mniej mojego pierdolenia.",
      "Leetcode, side project, kurs. Wybierz cokolwiek i pisz przez {left}.",
      "Merge conflicty z samym sobą rozwiązuje się pisaniem kodu, a nie odkładaniem, do chuja.",
    ],
    praise: [
      "Kod napisany. Zielone kwadraciki na GitHubie właśnie zakwitły.",
      "Programowanie zaliczone. Nawet jeśli działa tylko na twoim komputerze, to się liczy.",
      "Commit zrobiony. Kurwa, aż chce się zrobić push.",
      "Kodzenie odhaczone. Bugi drżą, a ja jestem lekko dumny.",
      "Zrobione. Ten kod może być brzydki, ale istnieje, i to jest najważniejsze.",
    ],
    rage: [
      "Cały dzień zero kodu. Twój GitHub wygląda jak zimowy krajobraz. Pusto i biało, kurwa.",
      "Jeszcze {left} programowania, a ty dalej scrollujesz. Ja pierdolę, otwórz ten edytor.",
      "Jedna funkcja. Jeden plik. Jeden commit. Nie każę ci pisać systemu operacyjnego, do chuja.",
      "Laptop otwarty, edytor zamknięty. Odwróć to natychmiast, kurwa mać.",
      "Przestań planować architekturę w głowie i napisz cokolwiek. Teraz.",
      "Kod się nie napisze od patrzenia na kursor. Klawiatura, do chuja, klawiatura!",
    ],
  },
  language: {
    nag: [
      "Nauka języka: {done} z {target} min. Sowa z Duolingo już wie, gdzie mieszkasz.",
      "Jeszcze {left}. Piętnaście minut dziennie i za rok rozmawiasz. Bez tego dalej pokazujesz na migi.",
      "Seria w Duolingo umiera, a z nią twoja godność. Ucz się, kurwa.",
      "Słówka nie wejdą ci do głowy przez osmozę. Fiszki do ręki.",
      "Za granicą znowu zamówisz „ten, no, ten” i pokażesz palcem. Ucz się, do chuja.",
      "Odmiana czasowników nie zrobi się sama. Dwujęzyczność też nie przyjdzie od samego marzenia.",
      "Pięć nowych słówek dziennie to prawie dwa tysiące rocznie. Ty masz dziś zero.",
      "Serial bez napisów? Nie. Najpierw nauka, potem możesz udawać, że rozumiesz.",
      "Jeszcze {left} nauki. Słuchawki, podcast, spacer. Dwa nawyki za jednym zamachem.",
      "Native speakerzy nie urodzili się z gramatyką w głowie. Uczyli się. Ty też możesz, kurwa.",
      "Twój akcent brzmi jak Google Translate po trzech piwach. Ćwicz wymowę.",
      "Gramatyka to nie wróg. Wrogiem jest twoje „zacznę od poniedziałku”.",
      "Lekcja w apce trwa pięć minut. Tyle trwa wybieranie, co obejrzeć. Wybierz lekcję.",
      "Fiszki leżą w szufladzie i zapominają cię szybciej niż ty je. Powtórka, do chuja.",
      "Zamiast scrollować po polsku, scrolluj w obcym języku. Przynajmniej coś zostanie w głowie.",
      "Słownik w telefonie, a w głowie pustka. Napraw to dziś, kurwa.",
      "Jeszcze {left}. Powtórz wczorajsze słówka, zanim całkiem wyparują.",
      "Mówienie do lustra w obcym języku to nie wariactwo, tylko trening. Spróbuj.",
      "Kolejny rok z „I am from Poland, I like pizza”? Ucz się, do cholery.",
      "Język to klucz do pracy, podróży i memów, których teraz nie rozumiesz. Ucz się.",
      "Duolingo wysyła ci groźby, a ty je ignorujesz. Ja jestem gorszy od sowy, ostrzegam.",
      "Czasy przeszłe w obcym języku same się nie ogarną. Siadaj, kurwa.",
      "Pięć minut powtórki rano, pięć wieczorem. Tyle. Nawet ty to zmieścisz w grafiku.",
      "Rozumiesz piosenki tylko z refrenu? Czas to zmienić. Lekcja, do chuja.",
    ],
    praise: [
      "Nauka języka zaliczona. Jeszcze chwila i zamówisz kawę bez pokazywania palcem.",
      "Lekcja zrobiona. Sowa z Duolingo odkłada siekierę.",
      "Słówka powtórzone. Twój mózg mówi już w dwóch językach. No, w półtora, kurwa.",
      "Zaliczone. Seria żyje, a ty jesteś krok bliżej rozmowy bez stresu.",
      "Język ćwiczony. Za granicą będzie mniej wstydu, a więcej rozmowy.",
      "Nauka odhaczona. Very good, czy jak tam się mówi, kurwa.",
    ],
    rage: [
      "Cały dzień bez nauki języka. Sowa z Duolingo już ładuje broń. Metaforycznie, kurwa.",
      "Jeszcze {left} nauki. Ja pierdolę, nawet jedna lekcja w apce. Jedna!",
      "Seria zaraz pęknie. Twoja godność pękła już dawno. Ucz się, do chuja.",
      "Pięć słówek. PIĘĆ. Tyle masz dziś zrobić, a robisz zero, kurwa mać.",
      "Słówka zapominasz szybciej, niż ja zrzucam kubki ze stołu. Powtórka, teraz.",
      "Odpal tę pierdoloną apkę i zrób lekcję. Potem możesz mnie nienawidzić w dwóch językach.",
    ],
  },
  porn: {
    nag: [
      "Potwierdź, że dziś bez pornosów. Karta incognito też potrzebuje urlopu, kurwa.",
      "Nuda w nocy to nie zaproszenie do historii przeglądarki. Zaznacz, że dziś czysto.",
      "Bez potwierdzenia zakładam, że Wi-Fi znowu pracuje na nadgodzinach. Zaznacz, jeśli nie.",
      "Dopamina z ekranu to kredyt chwilówka. Spłacasz potem mgłą w głowie. Potwierdź, że dziś bez.",
      "Telefon do łóżka to proszenie się o kłopoty. Zostaw go w kuchni i zaznacz, że dziś czysto.",
      "Prawdziwe życie nie ma filtrów i scenariusza. I dobrze. Potwierdź, że dziś w nim jesteś, do chuja.",
      "Ciągnie cię? Pompki, prysznic, spacer, dziesięć minut. Potem zaznacz, że dziś czysto.",
      "Każdy czysty dzień to mózg, który się odtruwa. Nie wlewaj mu znowu tego syfu. Potwierdź.",
      "Pornole robią z mózgu papkę i z oczekiwań kabaret. Zaznacz, że dziś odpuszczasz, kurwa.",
      "Zmęczenie, stres i samotność to wyzwalacze. Zadzwoń do kogoś zamiast odpalać kartę. Potwierdź, że czysto.",
      "Blokada stron w telefonie to nie wstyd, to strategia. Ustaw i zaznacz, że dziś czysto.",
      "„Tylko zerknę” to najstarsze kłamstwo internetu. Potwierdź, że dziś bez zerkania.",
      "Twoja seria czystych dni jest więcej warta niż pięć minut w trybie incognito. Zaznacz, że ją chronisz.",
      "Mózg potrzebuje nudy, żeby odpocząć. Nie zapychaj jej pornosami. Potwierdź, że dziś bez.",
      "Bez potwierdzenia uznaję, że historia przeglądarki znowu idzie do kasowania. Zaznacz, jeśli nie, kurwa.",
      "Odpuść dziś, a jutro obudzisz się z czystszą głową i lepszym humorem. Potwierdź, że czysto.",
      "Wyłącz telefon o 23:00 i zaśnij jak człowiek. Zaznacz, że dziś bez pornografii.",
      "Pornografia to fast food dla mózgu. Tani, szybki i potem źle się czujesz. Potwierdź, że dziś bez.",
      "Masz w sobie więcej siły, niż ci się wydaje. Pokaż to dziś i zaznacz, że czysto, do chuja.",
      "Karta incognito nie ukryje niczego przed tobą samym. Potwierdź, że dziś jej nie otwierasz.",
      "Ręce na klawiaturę, ale do pracy. Albo na kierownicę roweru. Zaznacz, że dziś czysto.",
      "Wieczorem najtrudniej. Wiem. Dlatego teraz potwierdź, że dzisiaj dajesz radę, kurwa.",
      "Algorytm stron z pornosami chce twojego czasu tak samo jak TikTok. Nie dawaj mu. Zaznacz, że czysto.",
      "Ten dzień możesz wygrać. Zaznacz na koniec, że się udało.",
    ],
    praise: [
      "Dzień bez pornosów. Mózg dziękuje, a karta incognito zbiera kurz.",
      "Czysto. Seria rośnie, a z nią twoja kontrola nad sobą.",
      "Zero pornografii. Kurwa, szacun. To nie jest łatwe i dziś się udało.",
      "Kolejny czysty dzień. Głowa jaśniejsza, wieczór spokojniejszy.",
      "Bez pornosów. Historia przeglądarki dziś nudna jak flaki z olejem. Idealnie.",
    ],
    slip: [
      "Wpadka z pornosami. Zamknij kartę, umyj ryj zimną wodą i od jutra od nowa, kurwa.",
      "Znowu się wysypało. Nie dobijaj się, ale zobacz, co cię dziś wyzwoliło, i jutro to omiń.",
      "Pornole wygrały dzisiaj. Seria od zera, ale wiedza o wyzwalaczach zostaje.",
      "Wpadka. Telefon w łóżku znowu okazał się złym pomysłem. Jutro ładowarka w kuchni.",
      "Znowu incognito. Ja pierdolę. Jutro pierwszy dzień nowej serii, nie zmarnuj go.",
    ],
    rage: [
      "Ja pierdolę, dalej brak potwierdzenia przy pornosach. Zakładam, że karta incognito już się grzeje.",
      "Cały dzień ciszy. Podejrzane jak telefon schowany pod kołdrą. Zaznacz, kurwa.",
      "Potwierdź, że czysto, albo uznaję wpadkę. Nie ma trzeciej opcji.",
      "Milczenie przy „{name}”. Zakładam najgorsze, a ty możesz to zmienić jednym kliknięciem.",
      "Brak potwierdzenia od rana. Twoja seria wisi na włosku, do chuja.",
      "Odłóż telefon, wyjdź z pokoju i zaznacz, że dziś czysto. Teraz, kurwa mać.",
    ],
  },
  meals: {
    nag: [
      "Potwierdź, że dziś jest śniadanie. Kawa na pusty żołądek to nie posiłek, to wyzwanie dla wrzodów, kurwa.",
      "Obiad olany „bo nie było czasu”? Na scrollowanie jakoś był. Zaznacz, że dziś jedzenie o ludzkiej porze.",
      "Bez potwierdzenia zakładam, że znowu jedziesz na kawie i nerwach do wieczora. Zjedz coś, do chuja.",
      "Głodny mózg to wkurwiony mózg. Zjedz normalny posiłek i potwierdź, że dziś regularnie.",
      "Pominięty posiłek kończy się wilczym głodem o 22:00 i opróżnioną lodówką. Potwierdź, że dziś nie.",
      "Kanapka, jogurt, banan. Cokolwiek, byle coś. Zaznacz, że dziś bez pomijania posiłków.",
      "Organizm to nie telefon na trybie oszczędzania baterii. Nakarm go. Potwierdź, że dziś jedzone.",
      "„Zjem później” to twoje ulubione kłamstwo zaraz po „zaraz idę spać”. Zjedz teraz, kurwa.",
      "Zawroty głowy o 15:00 to nie magia, to brak obiadu. Potwierdź, że dziś jest normalnie.",
      "Śniadanie mistrzów to nie papieros i espresso. Zjedz coś prawdziwego i zaznacz.",
      "Głód robi z ciebie potwora, który warczy na ludzi. Nie bądź dziś potworem. Zjedz.",
      "Trzy posiłki dziennie to nie luksus, to instrukcja obsługi człowieka. Potwierdź, że dziś działa.",
      "Przygotuj jedzenie wieczorem na jutro i nie będzie wymówek. Zaznacz, że dziś posiłki zjedzone.",
      "Jedzenie przy biurku też się liczy. Jedzenie zero razy do 17:00 nie. Potwierdź, że dziś jedzone, do chuja.",
      "Twój żołądek burczy jak stary diesel. Daj mu paliwa. Zaznacz, że dziś bez pomijania.",
      "Bez potwierdzenia uznaję, że przerwa na lunch znowu poszła na maile. Zjedz coś, kurwa.",
      "Kawa nie ma kalorii, które dadzą ci energię na cały dzień. Jedzenie ma. Potwierdź, że dziś jedzone.",
      "Nawet kot je regularnie, a ja jestem leniwym kotem. Potwierdź, że dziś też jedzone o porach.",
      "Pusty żołądek, krótki lont. Zjedz coś, zanim kogoś opierdolisz bez powodu.",
      "Pomijanie posiłków to nie dieta, to sabotaż. Zaznacz, że dziś normalnie, do chuja.",
      "Mrożonki, gotowe sałatki, jajka na twardo. Zero wymówek. Potwierdź, że dziś posiłki są.",
      "Zjedz porządne śniadanie, a resztę dnia będzie łatwiej. Zaznacz, że dziś się udało.",
      "Bez jedzenia mózg pracuje jak laptop na 3% baterii. Podłącz ładowarkę: zjedz. Potwierdź.",
      "Jak nie masz apetytu, zjedz chociaż coś małego. Byle nie zero. Zaznacz, że dziś jedzone.",
      "Lunch to nie strata czasu, to tankowanie. Potwierdź, że dziś bak pełny, kurwa.",
      "Jedzenie o normalnej porze to nie słabość. Słabością jest padanie na ryj o 16:00. Zjedz.",
      "Potwierdź, że dziś były posiłki o ludzkich porach. Twój organizm na to zasługuje.",
    ],
    praise: [
      "Posiłki zjedzone o porach. Żołądek gra marsza triumfalnego.",
      "Dzień bez pomijania jedzenia. Humor lepszy, głowa jaśniejsza, ludzie bezpieczniejsi.",
      "Śniadanie, obiad, kolacja. Kurwa, książkowo.",
      "Zjedzone. Organizm dostał paliwo i nie musiał żebrać.",
      "Regularne jedzenie zaliczone. Nawet wieczorny wilczy głód dziś nie przyszedł.",
      "Brawo. Dziś organizm był traktowany jak człowiek, a nie jak wielbłąd.",
    ],
    slip: [
      "Znowu pominięty posiłek. Zjedz coś teraz, nawet małego, i jutro śniadanie bez wymówek.",
      "Wpadka z jedzeniem. Organizm cały dzień na oparach. Nakarm go teraz, kurwa.",
      "Posiłek przepadł. Za godzinę przyjdzie głód i zje ci humor. Zjedz coś normalnego.",
      "Znowu na kawie do wieczora. Jutro przygotuj jedzenie z wyprzedzeniem, do chuja.",
      "Pominięte jedzenie. To nie jest osiągnięcie, to rozładowana bateria. Ładuj.",
      "Wpadka. Jutro budzik na śniadanie, a nie tylko na pracę.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy posiłkach. Zakładam, że żyjesz fotosyntezą, kurwa.",
      "Ja pierdolę, dalej nic. Zjedz coś, zanim zaczniesz warczeć na ludzi.",
      "Potwierdź, że jedzone, albo uznaję, że znowu jedziesz na samej kawie.",
      "Brak potwierdzenia. Twój żołądek właśnie złożył skargę do rzecznika praw człowieka.",
      "Lodówka jest pięć metrów od ciebie. Idź tam i zjedz coś normalnego, do chuja.",
      "Milczysz przy posiłkach. Zakładam, że ostatnie jedzenie to wczorajsza kolacja. Zjedz teraz.",
      "Kurwa, jedzenie to nie nagroda za skończoną pracę. To paliwo. Tankuj.",
    ],
  },
  energy: {
    nag: [
      "Potwierdź, że dziś bez energetyków. Serce i tak wali ci jak bęben na koncercie metalowym, kurwa.",
      "Puszka tauryny zamiast snu to pożyczka z najgorszego banku. Zaznacz, że dziś bez.",
      "Bez potwierdzenia zakładam, że w plecaku grzechocze już trzecia puszka.",
      "Energetyk o 16:00 = sen o 3:00. Potwierdź, że dziś odpuszczasz, do chuja.",
      "Woda, spacer, drzemka. Trzy darmowe energetyki. Zaznacz, że dziś bez puszek.",
      "Kolorowa puszka, a w środku chemia i cukier. Potwierdź, że dziś czysto.",
      "Zęby, żołądek i serce wspólnie proszą: dziś bez energetyka. Zaznacz, kurwa.",
      "Energia z puszki trwa godzinę, zjazd trwa resztę dnia. Potwierdź, że dziś bez.",
      "Ręce się trzęsą, oczy jak u sowy, a mówisz, że to normalne. Zaznacz, że dziś bez energetyków.",
      "Zamiast puszki zjedz coś normalnego. Energia z jedzenia nie kończy się palpitacjami. Potwierdź.",
      "Dziesięć złotych dziennie na energetyki to trzysta miesięcznie. Za tyle masz siłownię. Zaznacz, że bez.",
      "Bez potwierdzenia zakładam, że lodówka w pracy ma już twoje imię na puszkach. Zaznacz, jeśli nie.",
      "Twoje serce to nie silnik wyścigowy. Nie tankuj go taurynową benzyną. Potwierdź, że dziś czysto.",
      "Zmęczenie mówi „śpij”, a ty mu wlewasz energetyka do gardła. Zaznacz, że dziś słuchasz ciała.",
      "Puszka o poranku, puszka w południe. Rytuał zombie. Potwierdź, że dziś go przerywasz, kurwa.",
      "Energetyk to nie śniadanie. Zaznacz, że dziś jedzenie zamiast puszki.",
      "Zaśniesz dziś normalnie, jeśli dziś bez energetyka. Proste. Potwierdź.",
      "Jak potrzebujesz puszki, żeby funkcjonować, to problem nie jest w puszce. Zaznacz, że dziś bez, do chuja.",
    ],
    praise: [
      "Dzień bez energetyków. Serce bije w normalnym rytmie, szok.",
      "Zero puszek. Kurwa, nawet ręce się nie trzęsą.",
      "Bez tauryny. Dziś zaśniesz jak człowiek.",
      "Czysto. Portfel i żołądek dziękują jednym głosem.",
      "Energia dziś z jedzenia i snu. Tak to powinno działać.",
      "Dzień bez puszki. Zjazdu nie będzie, bo nie było wjazdu.",
      "Zero energetyków. Zęby właśnie odetchnęły z ulgą.",
    ],
    slip: [
      "Znowu energetyk. Za godzinę zjazd jak z Kasprowego bez nart.",
      "Puszka wypita. Serce właśnie przyspieszyło, a rozum zwolnił.",
      "Wpadka z energetykiem. Dziś w nocy będziesz liczyć sufit, kurwa.",
      "Tauryna wygrała. Wypij teraz dużo wody i nie kupuj kolejnej.",
      "Znowu puszka. Twój żołądek właśnie skwierczy.",
      "Energetyk zaliczony. Za tydzień serce wystawi ci rachunek.",
      "Wpadka. Jutro zamiast puszki: woda i spacer na świeżym powietrzu.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy energetykach. Zakładam, że krew już ci się gazuje, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę syk puszki przez ekran.",
      "Potwierdź, że czysto, albo uznaję, że trzecia puszka już w drodze.",
      "Brak potwierdzenia. Twoje serce właśnie dzwoni po karetkę na wszelki wypadek.",
      "Milczysz przy energetykach. Podejrzane jak drżące ręce. Zaznacz, do chuja.",
      "Zakładam najgorsze: puszka do śniadania, puszka do obiadu. Udowodnij, że nie.",
      "Kurwa, jedno kliknięcie. Dziś bez puszki czy nie?",
    ],
  },
  shopping: {
    nag: [
      "Potwierdź, że dziś bez impulsywnych zakupów. Kurier już zna kod do twojej klatki, kurwa.",
      "Koszyk na Allegro się nie obrazi, jak go dziś nie opłacisz. Zaznacz, że portfel zamknięty.",
      "Zasada 48 godzin: wrzuć do koszyka, poczekaj dwa dni. Połowa rzeczy sama wyparuje. Potwierdź, że dziś czekasz.",
      "Promocja „-70%” to wciąż 30% za coś, czego nie potrzebujesz. Zaznacz, że dziś bez, do chuja.",
      "Bez potwierdzenia zakładam, że BLIK już się rozgrzewa w telefonie.",
      "Temu, AliExpress, Zalando. Trzy słowa, które kosztują cię najwięcej. Potwierdź, że dziś żadne.",
      "Nudzi ci się? Idź na spacer, nie do sklepu internetowego. Zaznacz, że dziś bez zakupów.",
      "Raty zero procent to wciąż raty. Potwierdź, że dziś nic nie kupione na kredyt, kurwa.",
      "Kolejna bluza, której nie założysz, kolejny gadżet, który leży w pudełku. Zaznacz, że dziś bez.",
      "Usuń kartę zapisaną w sklepie. Przepisywanie numeru to idealna chwila na otrzeźwienie. Potwierdź, że dziś bez.",
      "Zakupy na poprawę humoru działają do momentu, kiedy przychodzi wyciąg z konta. Zaznacz, że dziś nie.",
      "Pytanie kontrolne: czy to kupisz za tydzień? Nie? To nie kupuj dziś. Potwierdź, do chuja.",
      "Paczkomat pod blokiem cię nie kocha. Kocha tylko twoje pieniądze. Zaznacz, że dziś pusty.",
      "Newslettery ze zniżkami do kosza, aplikacje sklepów do usunięcia. Potwierdź, że dziś czysto.",
      "Masz w szafie rzeczy z metkami. Załóż je, zamiast kupować nowe. Zaznacz, że dziś bez zakupów, kurwa.",
      "„Darmowa dostawa od 100 zł” i nagle kupujesz trzy rzeczy, żeby nie płacić 10 zł. Geniusz finansów. Zaznacz, że dziś nie.",
      "Twoje oszczędności dziękują za każdy dzień bez kliknięcia „kup teraz”. Potwierdź dzisiejszy.",
      "Zamknij kartę ze sklepem. Teraz. Zaznacz, że dziś portfel przeżył.",
      "Black Friday jest raz w roku, a u ciebie co tydzień. Potwierdź, że dziś zwykły piątek, kurwa.",
      "Kupowanie to nie hobby. Hobby to coś, co robisz rzeczami, które już masz. Zaznacz, że dziś bez.",
      "Bez potwierdzenia uznaję, że koszyk znowu pęka w szwach. Zaznacz, jeśli nie, do chuja.",
      "Odłóż kasę na coś, co naprawdę ma znaczenie. Wakacje, poduszka finansowa, cokolwiek. Potwierdź, że dziś odłożone.",
      "Reklama za tobą chodzi jak pies. Nie dawaj jej kiełbasy. Zaznacz, że dziś bez zakupów.",
      "Każda impulsywna paczka to mała dziura w budżecie. Potwierdź, że dziś bez dziur, kurwa.",
    ],
    praise: [
      "Dzień bez impulsywnych zakupów. Konto bankowe właśnie przestało płakać.",
      "Portfel zamknięty. Kurier musi dziś szukać innego frajera.",
      "Zero zakupów. Kurwa, oszczędności rosną, a ja jestem pod wrażeniem.",
      "Czysto. Koszyk pełny, ale nieopłacony. Idealny stan.",
      "Bez kupowania pierdół. Za miesiąc podziękujesz, jak zobaczysz saldo.",
    ],
    slip: [
      "Znowu kupione. Za tydzień nawet nie będzie wiadomo po co, kurwa.",
      "Wpadka z zakupami. Paczka przyjdzie jutro, a wyrzuty sumienia już są.",
      "Impulsywny zakup zaliczony. Masz jeszcze 14 dni na zwrot. Użyj ich.",
      "Kliknięte „kup teraz”. Dopamina na pięć minut, rachunek na miesiąc.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy zakupach. Zakładam, że kurier już parkuje pod blokiem, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd dźwięk powiadomienia „zamówienie przyjęte”.",
      "Potwierdź, że portfel przeżył, albo uznaję, że karta już się topi.",
      "Brak potwierdzenia. Twoje konto właśnie zawiesiło się z przerażenia.",
      "Milczysz przy wydawaniu. Podejrzane jak paczka schowana przed domownikami. Zaznacz, do chuja.",
      "Zakładam najgorsze: trzy paczki z Chin i bluza, której nie potrzebujesz. Udowodnij, że nie.",
    ],
  },
  gambling: {
    nag: [
      "Potwierdź, że dziś bez hazardu. Bukmacher zarabia na tym, że wierzysz w „pewniaki”, kurwa.",
      "Kasyno online nie zamyka się nigdy. Dlatego ty musisz zamknąć apkę. Zaznacz, że dziś bez.",
      "Bez potwierdzenia zakładam, że kupon już jest wypełniony. Zaznacz, jeśli nie.",
      "„Odegram się” to zdanie, które zrujnowało więcej ludzi niż wszystkie kryzysy razem. Potwierdź, że dziś nie, do chuja.",
      "Zdrapka na stacji to nie inwestycja. Zaznacz, że dziś bez.",
      "Bonus powitalny to haczyk z robakiem. Ty jesteś rybą. Potwierdź, że dziś nie gryziesz.",
      "Każda zakładka bukmachera w telefonie to pułapka. Usuń i zaznacz, że dziś czysto.",
      "Wygrana dziś to przegrana jutro z odsetkami. Potwierdź, że dziś bez zakładów, kurwa.",
      "Mecz da się oglądać bez kuponu. Serio. Zaznacz, że dziś tylko oglądasz.",
      "Kasa na hazard to kasa na czynsz, jedzenie i wakacje. Potwierdź, że dziś została w kieszeni.",
      "Ruletka nie pamięta, co wypadło wcześniej. Ty pamiętaj, ile przegrane. Zaznacz, że dziś bez.",
      "Blokada stron hazardowych istnieje. Ustaw ją i potwierdź, że dziś czysto, do chuja.",
      "Statystyki nie kłamią: na dłuższą metę zawsze wygrywa dom. Zaznacz, że dziś nie grasz.",
      "Pogadaj z kimś, jak ciągnie. Wstydu nie ma. Wstyd jest w pustym koncie. Potwierdź, że dziś bez.",
      "Zakład na „pewny” mecz? Pewne jest tylko to, że bukmacher kupi nowe auto. Zaznacz, że dziś nie.",
      "Bez potwierdzenia uznaję, że automaty w apce znowu kręcą się z twoimi pieniędzmi, kurwa.",
      "Każdy dzień bez hazardu to złotówki zostające u ciebie. Potwierdź dzisiejszy.",
      "Emocje możesz mieć za darmo: sport, kino, rower. Zaznacz, że dziś bez stawiania.",
    ],
    praise: [
      "Dzień bez hazardu. Twoje pieniądze dziś spały spokojnie w portfelu.",
      "Zero zakładów. Bukmacher dziś nic na tobie nie zarobił, ha!",
      "Czysto. Kurwa, najlepszy kupon to ten niepostawiony.",
      "Bez hazardu. Konto ma się dobrze, a ty masz spokojną głowę.",
      "Dzień bez kasyna. Dom dziś przegrał z tobą.",
      "Zero stawiania. To jest prawdziwa wygrana.",
      "Bez zakładów. Seria rośnie szybciej niż jakikolwiek kurs.",
    ],
    slip: [
      "Znowu hazard. Bukmacher właśnie dopisał cię do listy ulubionych klientów.",
      "Wpadka z zakładami. Nie odgrywaj się, to droga na dno. Zamknij apkę.",
      "Kupon postawiony. Kasyno dziękuje za sponsoring, kurwa.",
      "Znowu przegrane. A jak wygrane, to i tak wróci do nich. Tak to działa.",
      "Hazard wygrał dzisiaj. Jutro usuń aplikację, zanim ją otworzysz.",
      "Wpadka. Porozmawiaj z kimś zaufanym, serio. Z tym łatwiej walczyć w dwójkę.",
      "Znowu zdrapki. Jedyne, co się zdrapało, to twoje oszczędności.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy hazardzie. Zakładam, że kupon już leci, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę kręcące się bębny automatu.",
      "Potwierdź, że czysto, albo uznaję, że portfel właśnie chudnie.",
      "Brak potwierdzenia. Twoje oszczędności piszą testament.",
      "Milczysz przy hazardzie. Podejrzane jak telefon odwrócony ekranem w dół w trakcie meczu. Zaznacz, do chuja.",
      "Zakładam najgorsze: odgrywanie się po przegranej. Udowodnij, że nie.",
      "Kurwa, zamknij tę apkę i zaznacz, że dziś bez stawiania.",
    ],
  },
  binge: {
    nag: [
      "Potwierdź, że dziś bez maratonu seriali. Netflix pyta „oglądasz dalej?”, a ja pytam „żyjesz dalej?”, kurwa.",
      "Jeden odcinek to jeden odcinek. Nie sezon. Zaznacz, że dziś trzymasz się zasady.",
      "Bez potwierdzenia zakładam, że autoplay leci od trzech godzin, a ty nawet nie mrugasz.",
      "Wyłącz autoplay. To jedyny przycisk, który naprawdę zmieni ci wieczór. Potwierdź, że dziś bez maratonu.",
      "Serial będzie jutro. Twój sen dzisiaj nie. Zaznacz, że dziś odpuszczasz, do chuja.",
      "Cliffhanger na końcu odcinka to pułapka zrobiona przez ludzi, którzy zarabiają na twoim niewyspaniu. Potwierdź, że dziś się nie dajesz.",
      "Oglądanie seriali do trzeciej to nie relaks, to maraton dla kanapy. Zaznacz, że dziś bez.",
      "„Jeszcze tylko jeden” to najdroższe słowa platform streamingowych. Potwierdź, że dziś nie.",
      "Bohaterowie serialu mają ciekawsze życie, bo ty swoje oglądasz w ich imieniu. Zaznacz, że dziś bez maratonu.",
      "Seriale do nocy, a rano płacz, że nie ma czasu na nic. Potwierdź, że dziś inaczej, kurwa.",
      "Zamiast trzeciego odcinka: spacer, książka, sen. Zaznacz, że dziś się udało.",
      "Fabuła się nie zmieni do jutra. Twoje zmęczenie owszem. Potwierdź, że dziś bez binge'a.",
      "Pięć sezonów w tydzień to nie osiągnięcie, to wołanie o pomoc. Zaznacz, że dziś bez.",
      "Odcinek do kolacji, nie do świtu. Potwierdź, że dziś wiesz, gdzie jest koniec.",
      "Kanapa ma już odcisk w kształcie twojego tyłka. Zaznacz, że dziś bez maratonu, do chuja.",
      "Pilot w ręku, życie na pauzie. Potwierdź, że dziś odwracasz te role.",
      "Bez potwierdzenia uznaję, że sezon leci na raz, a ty jesz chipsy z miski bez dna. Zaznacz, jeśli nie.",
      "Ustaw budzik na koniec odcinka. Jak zadzwoni, wyłączasz. Potwierdź, że dziś działa, kurwa.",
    ],
    praise: [
      "Dzień bez maratonu. Twoje oczy dziś widziały świat poza ekranem.",
      "Czysto. Jeden odcinek, a nie cały sezon. Kurwa, dorosłość.",
      "Bez binge'a. Netflix dziś stracił kilka godzin twojego życia. Dobrze mu tak.",
      "Zero maratonu. Wieczór był twój, a nie scenarzystów.",
      "Serial odpuszczony. Sen dziś będzie długi i bez spoilerów.",
      "Bez autoplaya. Wygrana z algorytmem w trzech rundach.",
      "Dzień bez maratonu. Kanapa wreszcie ma wolne.",
    ],
    slip: [
      "Znowu cały sezon na raz. Scenarzyści zarobili, a noc przepadła. Kurwa.",
      "Wpadka z serialami. Autoplay znowu wygrał z rozsądkiem.",
      "Maraton zaliczony. Oczy czerwone jak przycisk nagrywania.",
      "Znowu do trzeciej z serialem. Jutro dzień jak z kiepskiego odcinka.",
      "Binge wygrał. Jutro jeden odcinek i pilot do szuflady.",
      "Wpadka. Fabuła ciekawa, ale twój sen poszedł się jebać.",
      "Znowu „jeszcze tylko jeden”. Ja pierdolę, ile razy?",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy serialach. Zakładam, że autoplay leci od rana, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd intro kolejnego odcinka.",
      "Potwierdź, że bez maratonu, albo uznaję, że sezon już w połowie.",
      "Brak potwierdzenia. Twoja kanapa właśnie stała się twoim domem.",
      "Milczysz przy serialach. Podejrzane jak ekran świecący o czwartej. Zaznacz, do chuja.",
      "Zakładam najgorsze: cały sezon i chipsy. Udowodnij, że nie.",
      "Kurwa, wyłącz ten pierdolony autoplay i zaznacz.",
    ],
  },
  snooze: {
    nag: [
      "Potwierdź, że dziś wstawanie za pierwszym budzikiem. Drzemka to nie odpoczynek, to tortury na raty, kurwa.",
      "Pięć budzików co pięć minut to nie plan, to dramat. Zaznacz, że dziś jeden wystarczył.",
      "Bez potwierdzenia zakładam, że dziś drzemka wygrała trzy do zera.",
      "Postaw budzik po drugiej stronie pokoju. Jak wstaniesz, żeby go wyłączyć, już nie wracaj. Potwierdź, że działa.",
      "Każde „jeszcze pięć minut” robi z poranka bieg z przeszkodami. Zaznacz, że dziś bez, do chuja.",
      "Drzemka po budziku robi z mózgu watę. Potwierdź, że dziś nóżki od razu na podłogę.",
      "Budzik nie jest twoim wrogiem. Twoim wrogiem jest przycisk drzemki. Zaznacz, że dziś nietknięty.",
      "Wstajesz od razu, to masz poranek. Drzemiesz, to masz panikę. Potwierdź, że dziś poranek.",
      "Światło, woda, ruch. Trzy sekundy po budziku. Zaznacz, że dziś bez drzemki, kurwa.",
      "Kładź się wcześniej, to nie będziesz walczyć z budzikiem. Potwierdź, że dziś wstanie było za pierwszym razem.",
      "Drzemka to kredyt, który spłacasz spóźnieniem. Zaznacz, że dziś bez.",
      "Kot budzi się raz i od razu wrzeszczy o jedzenie. Bądź jak kot. Potwierdź, że dziś bez drzemki.",
      "Twój budzik ma już traumę od tylu odrzuceń. Zaznacz, że dziś go nie ranisz, do chuja.",
      "Bez potwierdzenia uznaję, że kołdra wygrała z obowiązkami. Zaznacz, jeśli nie.",
      "Pierwszy budzik, pierwsza decyzja. Wygraj ją. Potwierdź, że dziś się udało, kurwa.",
      "Poranek bez drzemki to dodatkowe kilkanaście minut na kawę i śniadanie. Zaznacz, że je masz.",
      "Ustaw jedną godzinę i się jej trzymaj. Potwierdź, że dziś bez przesuwania.",
      "Drzemka to zabawa w chowanego z rzeczywistością. Rzeczywistość zawsze wygrywa. Zaznacz, że dziś bez.",
    ],
    praise: [
      "Wstawanie za pierwszym razem. Budzik właśnie się wzruszył.",
      "Bez drzemki. Poranek był twój, a nie kołdry.",
      "Zero „jeszcze pięć minut”. Kurwa, szacun, dyscyplina jak w wojsku.",
      "Wstanie od razu zaliczone. Dziś nie trzeba było biec na autobus.",
      "Czysto. Przycisk drzemki dziś na bezrobociu.",
      "Bez drzemki. Mózg obudził się raz i porządnie.",
      "Poranek wygrany. Budzik może iść na emeryturę z honorem.",
    ],
    slip: [
      "Znowu drzemka. Budzik dzwonił pięć razy, a negocjacje z nim trwały pół godziny. Kurwa.",
      "Wpadka z budzikiem. Poranek w trybie paniki, zgadłem?",
      "Drzemka wygrała. Jutro budzik na drugi koniec pokoju.",
      "Znowu przycisk drzemki. Twoje „pięć minut” trwało czterdzieści.",
      "Wpadka. Kołdra była silniejsza. Jutro idź spać wcześniej.",
      "Drzemka zaliczona. Mózg jak wata cukrowa do południa.",
      "Znowu spóźnione wstawanie. Ja pierdolę, jutro bez dyskusji.",
    ],
    rage: [
      "Brak potwierdzenia przy budziku. Zakładam, że drzemka pobiła rekord świata, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd szósty budzik.",
      "Potwierdź, że wstanie było od razu, albo uznaję wpadkę.",
      "Cisza przy drzemce. Podejrzane jak spóźnienie bez wyjaśnienia. Zaznacz, do chuja.",
      "Zakładam najgorsze: budzik o siódmej, wstanie o ósmej. Udowodnij, że nie.",
      "Kurwa, jedno kliknięcie: od razu czy z drzemką?",
      "Milczysz przy budziku. Kołdra chyba znowu wygrała.",
    ],
  },
  nails: {
    nag: [
      "Potwierdź, że dziś bez obgryzania paznokci. Palce to nie paluszki z sezamem, kurwa.",
      "Ręce w ustach jak u przedszkolaka. Zaznacz, że dziś paznokcie całe.",
      "Bez potwierdzenia zakładam, że skórki już dawno poszły na przystawkę.",
      "Stres? Ściśnij piłeczkę, a nie paznokcie zębami. Potwierdź, że dziś bez obgryzania, do chuja.",
      "Wiesz, ile bakterii masz pod paznokciami? I to idzie prosto do gęby. Zaznacz, że dziś czysto.",
      "Gorzki lakier to nie kara, to wsparcie. Pomaluj i potwierdź, że dziś bez obgryzania.",
      "Paznokcie rosną, jak im dasz szansę. Daj. Zaznacz, że dziś bez.",
      "Obgryzanie przy serialu, w pracy, w korku. Tik jak w zegarku. Potwierdź, że dziś przerwany, kurwa.",
      "Zauważ, kiedy ręka idzie do ust. Zatrzymaj ją. Zaznacz, że dziś się udało.",
      "Opuszki palców bolą, a ty dalej gryziesz. Ja pierdolę. Potwierdź, że dziś bez.",
      "Zajmij czymś ręce: długopis, kostka Rubika, kot do głaskania. Zaznacz, że dziś bez obgryzania.",
      "Krótko obcięte paznokcie są trudniejsze do obgryzania. Obetnij i potwierdź, że dziś czysto.",
      "Twoje palce wyglądają, jakby walczyły z bobrem. I przegrały. Zaznacz, że dziś bez.",
      "Paznokcie to nie kanapka. Potwierdź, że dziś bez obgryzania, kurwa.",
      "Każdy dzień bez obgryzania to milimetr postępu. Dosłownie. Zaznacz dzisiejszy.",
      "Bez potwierdzenia uznaję, że ręce znowu w ustach. Zaznacz, jeśli nie.",
      "Rękawiczki w domu to przesada? Może. Ale działają. Potwierdź, że dziś bez obgryzania, do chuja.",
      "Nawyk siedzi w dłoniach, ale decyzja w głowie. Zaznacz, że dziś głowa wygrała.",
    ],
    praise: [
      "Paznokcie całe. Twoje palce wreszcie wyglądają jak palce.",
      "Dzień bez obgryzania. Kurwa, aż chce się pomalować je na złoto.",
      "Czysto. Ręce dziś trzymane z dala od gęby.",
      "Bez obgryzania. Skórki przeżyły kolejny dzień.",
      "Paznokcie zostały. Nawyk dziś przegrał.",
      "Zero obgryzania. Pokaż dłonie bez wstydu.",
      "Brawo. Milimetr po milimetrze, a jednak rośnie.",
    ],
    slip: [
      "Znowu obgryzione. Twoje palce wyglądają jak po spotkaniu z maszynką do mięsa.",
      "Wpadka z paznokciami. Jutro gorzki lakier od rana.",
      "Obgryzanie zaliczone. Bakterie spod paznokci mówią „dziękujemy”, kurwa.",
      "Znowu ręce w ustach. Stres wygrał. Jutro piłeczka antystresowa w kieszeni.",
      "Wpadka. Skórki znowu na przystawkę.",
      "Paznokcie przegrały. Obetnij krótko i zacznij jutro od nowa.",
      "Znowu gryzione. Ja pierdolę, przecież to nawet nie jest smaczne.",
    ],
    rage: [
      "Brak potwierdzenia przy paznokciach. Zakładam, że zostały same kikuty, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd chrupanie.",
      "Potwierdź, że paznokcie całe, albo uznaję wpadkę.",
      "Cisza przy obgryzaniu. Podejrzane jak plaster na każdym palcu. Zaznacz, do chuja.",
      "Zakładam najgorsze: dziesięć palców, zero paznokci. Udowodnij, że nie.",
      "Ręce z ust i kliknij. Teraz, kurwa.",
      "Milczysz przy paznokciach. Pewnie dlatego, że masz palce w gębie.",
    ],
  },
  caffeine: {
    nag: [
      "Potwierdź, że dziś kawa z umiarem. Serce ci zaraz wyskoczy przez uszy, kurwa.",
      "Kawa po 16:00 to zaproszenie bezsenności na nocowanie. Zaznacz, że dziś bez.",
      "Bez potwierdzenia zakładam, że czwarte espresso już paruje na biurku.",
      "Kawa to nie woda. Woda to woda. Potwierdź, że dziś kofeina pod kontrolą, do chuja.",
      "Ręce się trzęsą, a ty mówisz, że to od zimna. Zaznacz, że dziś mniej kawy.",
      "Jedna, dwie kawy to rytuał. Pięć to uzależnienie. Potwierdź, że dziś rytuał.",
      "Kofeina pożycza ci energię z jutra. Z odsetkami. Zaznacz, że dziś bez lichwy.",
      "Bezkofeinowa też smakuje jak kawa. Potwierdź, że dziś po południu tylko taka, kurwa.",
      "Zmęczenie po trzeciej kawie? To znak, że potrzebujesz snu, a nie czwartej kawy. Zaznacz, że dziś odpuszczasz.",
      "Kubek kawy w ręku jak smoczek u dziecka. Potwierdź, że dziś mniej.",
      "Serce wali, żołądek pali, sen ucieka. Pakiet „za dużo kawy”. Zaznacz, że dziś bez, do chuja.",
      "Herbata, woda, spacer. Inne sposoby na energię też istnieją. Potwierdź, że dziś umiar.",
      "Ekspres do kawy ma więcej przebiegu niż twój samochód. Zaznacz, że dziś odpoczywa.",
      "Bez potwierdzenia uznaję, że krew w żyłach to już cappuccino. Zaznacz, jeśli nie, kurwa.",
      "Kawa na pusty żołądek? Najpierw jedzenie, potem kawa. Potwierdź, że dziś tak.",
      "Limit kofeiny istnieje. Nie jest „ile wlezie”. Zaznacz, że dziś w normie.",
      "Twoja kawa ma więcej fanów niż ty wolnych godzin. Potwierdź, że dziś mniej kubków.",
      "Śpisz źle, bo pijesz dużo kawy. Pijesz dużo kawy, bo śpisz źle. Przerwij to koło. Zaznacz.",
    ],
    praise: [
      "Kawa z umiarem. Serce bije, a nie galopuje.",
      "Kofeina pod kontrolą. Kurwa, dziś zaśniesz jak człowiek.",
      "Czysto. Ekspres dziś miał wolne, pierwszy raz od miesięcy.",
      "Umiar zaliczony. Ręce stabilne jak u chirurga.",
      "Bez przesady z kawą. Żołądek przestał płonąć.",
      "Kawa w normie. Twoja energia dziś była twoja, a nie pożyczona.",
      "Brawo. Dziś to ty pijesz kawę, a nie kawa pije ciebie.",
    ],
    slip: [
      "Znowu kawa za kawą. Ręce się trzęsą jak u złodzieja na komisariacie.",
      "Wpadka z kofeiną. Dziś w nocy będziesz liczyć owce do trzech tysięcy.",
      "Kawa po 16:00 zaliczona. Bezsenność już rezerwuje miejsce w łóżku, kurwa.",
      "Znowu przesada z kawą. Serce bije jak perkusja na weselu.",
      "Wpadka. Jutro limit: dwie kawy do południa.",
      "Kofeina wygrała. Wypij dużo wody i nie dolewaj.",
      "Znowu piąta kawa. Ja pierdolę, w żyłach ci płynie espresso.",
    ],
    rage: [
      "Brak potwierdzenia przy kawie. Zakładam, że ekspres już się dymi, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd młynek do kawy.",
      "Potwierdź, że umiar, albo uznaję, że kawa wlewa się jak do wiadra.",
      "Cisza przy kofeinie. Podejrzane jak drżący kubek. Zaznacz, do chuja.",
      "Zakładam najgorsze: pięć kaw i bezsenność gratis. Udowodnij, że nie.",
      "Odstaw ten kubek i kliknij, kurwa.",
      "Milczysz przy kawie. Pewnie dlatego, że serce za głośno wali.",
    ],
  },
  procrastination: {
    nag: [
      "Potwierdź, że dziś bez odkładania. „Zrobię to jutro” powtarzasz tak długo, że jutro ma cię dość, kurwa.",
      "Najtrudniejsze jest pierwsze pięć minut. Zacznij, a potem zaznacz, że dziś bez prokrastynacji.",
      "Bez potwierdzenia zakładam, że znowu sprzątasz biurko zamiast robić to, co trzeba.",
      "Prokrastynacja to kredyt na stres z wysokim oprocentowaniem. Zaznacz, że dziś bez, do chuja.",
      "Rozbij to na małe kroki. Pierwszy krok: teraz. Potwierdź, że dziś działa.",
      "Deadline nie jest motywacją, tylko paniką z opóźnieniem. Zaznacz, że dziś robione na czas.",
      "Oglądanie filmików o produktywności to nie produktywność. Potwierdź, że dziś bez.",
      "Zrób najgorszą rzecz rano i resztę dnia masz z głowy. Zaznacz, że dziś się udało, kurwa.",
      "Timer na 25 minut. Tylko to zadanie. Potem przerwa. Potwierdź, że dziś działa.",
      "Twoja lista zadań ma więcej wersji niż Windows. Przestań ją poprawiać i zacznij odhaczać.",
      "Perfekcjonizm to prokrastynacja w garniturze. Zrób źle, ale zrób. Zaznacz, że dziś bez odkładania.",
      "Bez potwierdzenia uznaję, że znowu „tylko sprawdzę maile” trwało dwie godziny. Zaznacz, jeśli nie, do chuja.",
      "Jutro też będzie ci się nie chciało. Różnica jest taka, że jutro będzie mniej czasu. Zrób dziś.",
      "Zadanie, które odkładasz od tygodnia, zajmie dwadzieścia minut. Wstyd trwał tydzień. Potwierdź, że dziś zrobione.",
      "Wyłącz telefon, zamknij karty, zrób jedną rzecz. Zaznacz, że dziś bez prokrastynacji, kurwa.",
      "Motywacja przychodzi po zaczęciu, nie przed. Potwierdź, że dziś zaczęte.",
      "„Na ostatnią chwilę” to nie styl pracy, to styl życia w stresie. Zaznacz, że dziś nie.",
      "Odkładanie na później to zabawa w berka z samym sobą. Zawsze przegrywasz. Potwierdź, że dziś bez.",
    ],
    praise: [
      "Dzień bez odkładania. Lista zadań patrzy na ciebie z szacunkiem.",
      "Zrobione na czas. Kurwa, nie wierzę, ale widzę.",
      "Bez prokrastynacji. Stres dziś na bezrobociu.",
      "Czysto. Jutro nie musi sprzątać po dzisiaj.",
      "Zadania odhaczone od razu. Nowa wersja ciebie właśnie się zainstalowała.",
      "Bez odkładania. Deadline dziś nie musiał krzyczeć.",
      "Brawo. Najtrudniejsze rzeczy zrobione najpierw, jak u dorosłych.",
    ],
    slip: [
      "Znowu wszystko przesunięte. Kalendarz właśnie cię wyśmiał, kurwa.",
      "Wpadka z odkładaniem. Ta jedna rzecz dalej wisi jak miecz nad głową, kurwa.",
      "Prokrastynacja zaliczona. Biurko czyste, zadanie nietknięte.",
      "Znowu „zaraz”. Zaraz minęło sześć godzin temu.",
      "Wpadka. Jutro zacznij od tej najgorszej rzeczy, zanim otworzysz cokolwiek innego.",
      "Odkładanie wygrało. Twój stres właśnie dostał nadgodziny.",
      "Znowu na ostatnią chwilę. Ja pierdolę, kiedyś ta chwila cię zje.",
    ],
    rage: [
      "Brak potwierdzenia przy odkładaniu. Ironia losu: pewnie odkładasz nawet to, kurwa.",
      "Ja pierdolę, dalej nic. Lista zadań właśnie się rozpłakała.",
      "Potwierdź, że bez odkładania, albo uznaję, że dzień przeciekł przez palce.",
      "Cisza przy prokrastynacji. Podejrzane jak nagle wysprzątane mieszkanie. Zaznacz, do chuja.",
      "Zakładam najgorsze: sześć godzin „przygotowywania się do pracy”. Udowodnij, że nie.",
      "Kurwa, zrób jedną rzecz z listy i kliknij.",
      "Milczysz przy prokrastynacji. Typowe. Odłożone na później, prawda?",
    ],
  },
};

export const SOFT_27X: Record<ExtraCategory, Lines27> = {
  pervert: {
    nag: [
      "Szacunek do ludzi wokół to codzienny wybór. Potwierdź dzisiejszy.",
      "Potwierdź, że dziś było kulturalnie i z szacunkiem.",
    ],
    praise: ["Dzień z szacunkiem do innych. Świetnie!"],
    slip: ["Zdarzyła się wpadka. Jutro więcej uważności."],
  },
  coding: {
    nag: [
      "Nawet jedna mała funkcja to krok naprzód.",
      "Zostało {left} programowania. Ulubiona muzyka i do dzieła!",
      "Mały commit dziś to duży projekt za miesiąc.",
    ],
    praise: ["Kod napisany. Projekt rośnie!", "Programowanie zaliczone. Super!"],
  },
  language: {
    nag: [
      "Kilka słówek dziennie robi wielką różnicę.",
      "Zostało {left} nauki języka. Krótka lekcja w apce?",
      "Powtórka wczorajszych słówek to świetny start.",
    ],
    praise: ["Nauka języka zaliczona. Seria trwa!", "Kolejna lekcja za tobą. Brawo!"],
  },
  porn: {
    nag: [
      "Telefon poza sypialnią na noc bardzo pomaga.",
      "Każdy dzień się liczy. Potwierdź dzisiejszy.",
    ],
    praise: ["Kolejny czysty dzień. Świetnie!"],
    slip: ["Wpadka się zdarzyła. Liczy się, że jutro próbujesz dalej."],
  },
  meals: {
    nag: [
      "Pora na coś do jedzenia - nawet mała przekąska się liczy.",
      "Regularne posiłki to więcej energii. Potwierdź, że dziś się udało.",
      "Śniadanie to dobry start dnia.",
    ],
    praise: ["Posiłki o porach. Organizm dziękuje!"],
    slip: ["Posiłek przepadł. Zjedz coś teraz i jutro zaplanuj jedzenie."],
  },
  energy: {
    nag: ["Szklanka wody i krótki spacer też dodają energii."],
    praise: ["Dzień bez energetyków. Świetnie!"],
    slip: ["Energetyk się zdarzył. Jutro spróbuj wody."],
  },
  shopping: {
    nag: ["Zanim klikniesz „kup”, odczekaj dobę.", "Potwierdź, że dziś portfel odpoczywa."],
    praise: ["Dzień bez zbędnych zakupów. Super!"],
    slip: ["Zakup się zdarzył. Sprawdź, czy da się go zwrócić."],
  },
  gambling: {
    nag: ["Każdy dzień bez zakładów to pieniądze dla ciebie."],
    praise: ["Dzień bez hazardu. Świetnie!"],
    slip: ["Zdarzyło się. Rozmowa z kimś bliskim może pomóc."],
  },
  binge: {
    nag: ["Jeden odcinek i dobranoc - to dobry plan."],
    praise: ["Wieczór bez maratonu. Brawo!"],
    slip: ["Maraton się zdarzył. Jutro wyłącz autoodtwarzanie."],
  },
  snooze: {
    nag: ["Budzik daleko od łóżka ułatwia wstawanie."],
    praise: ["Wstawanie za pierwszym razem. Super!"],
    slip: ["Drzemka się zdarzyła. Jutro spróbuj wcześniej się położyć."],
  },
  nails: {
    nag: ["Zajmij czymś dłonie, gdy pojawi się stres."],
    praise: ["Paznokcie całe. Świetnie!"],
    slip: ["Zdarzyło się. Krótko obcięte paznokcie pomagają."],
  },
  caffeine: {
    nag: ["Po południu wybierz herbatę albo wodę."],
    praise: ["Kofeina z umiarem. Brawo!"],
    slip: ["Kawy było więcej. Jutro postaw sobie limit."],
  },
  procrastination: {
    nag: ["Zacznij od pięciu minut - reszta pójdzie łatwiej."],
    praise: ["Zadania zrobione na czas. Świetnie!"],
    slip: ["Coś się odwlekło. Jutro zacznij od tego zadania."],
  },
};
