// English mirror of szpila-27.ts - same keys, same number of lines per array, same placeholders. Not literal translations.
// Style: rewritten so the jokes land in English, gender-neutral, swearing aimed at the
// behaviour (never at who someone is); soft pools stay polite and swear-free.
import type { Category } from "./szpila";
import type { TauntLevel } from "./store";
import type { Lines27 } from "./szpila-27";

export const HARD_27_EN: Partial<Record<Category, Lines27>> = {
  teeth: {
    nag: [
      "Skipped the morning brush? With breath like that, even your coffee is trying to climb out of the mug, damn it.",
      "Brushing at night is not a premium add-on. Brush, paste, two minutes, for fuck's sake.",
      "Your teeth have more buildup than grandma's kettle. Bathroom. Go.",
      "Half of yesterday's dinner is still living between your teeth. Scrub before it sprouts.",
      "Toothpaste doesn't work through a closed tube. Open it, squeeze it, brush, damn it.",
      "You say “good morning” and people pass out. Coincidence? No. Teeth.",
      "An electric toothbrush you only charge out of guilt. Use the damn thing already.",
      "The bacteria in your mouth are throwing a rave and nobody's kicking them out. Toothbrush, deploy.",
      "Not a single tooth brushed today. Holy shit.",
      "Your dentist is counting on you more than on their pension. Don't give them the satisfaction.",
      "Brush in the morning, brush at night. Twice a day, not twice a week, genius.",
      "The floss is crying alone in the drawer. Fuck it, at least use the toothbrush.",
      "Your mouth looks like a festival trash can on Monday morning. Clean it already.",
      "{left} more brushing to go today. Two minutes, not two hours, for fuck's sake.",
      "Brushing: {done} of {target}. The cavities are giving you a standing ovation.",
      "You've got enough tartar in there to pour a foundation. Toothbrush, right now.",
      "Picture someone kissing you. Now picture their face. Teeth, damn it.",
    ],
    praise: [
      "Teeth brushed. Flies passing by no longer drop dead mid-air.",
      "Squeaky clean. You can smile without a health warning.",
      "Brushed. The cavities are packing their bags and moving in next door.",
      "Brushing done. Your mouth is fit for humans again, holy shit, what a shock.",
    ],
    rage: [
      "TEETH, for fuck's sake. A toothbrush costs three bucks, a root canal costs a thousand. Do the math.",
      "One more day of this and your teeth will walk out of your mouth in protest, damn it.",
      "Your breath just killed the plant on the windowsill. Bathroom. Now.",
      "How long is this going to take? Two minutes of brushing and you're free. Move, goddamn it.",
      "Brushing: {done} of {target} at this hour. Holy shit, the cavities are already hanging curtains.",
    ],
  },
  water: {
    nag: [
      "{done} of {target} down. Skin like sandpaper, brain like a dried prune. Drink, damn it.",
      "{left} to go. Cup, tap, sip. This is not brain surgery, for fuck's sake.",
      "Your first glass of water hasn't even seen your face yet? Then drink.",
      "That afternoon headache isn't the weather, it's dehydration, genius.",
      "The water bottle is as full as your promises. Empty it already.",
      "{left} left. Even the cat drinks more, and I consider water a personal enemy.",
      "Coffee doesn't count. Tea with four sugars doesn't count either. Water, damn it.",
      "Pee the color of beer with no beer involved? Congrats on the dehydration. Drink.",
      "{done} of {target} down. A camel just asked if you're okay.",
      "Your kidneys are running in power-saving mode. Give them some damn water.",
      "A glass of water takes thirty seconds. Scrolling takes three hours. See the ratio?",
      "Tired, cranky, pounding head. The full “I don't drink water” bundle. Drink.",
      "{left} to the goal. Don't make me show up with a watering can, damn it.",
      "The cactus on the windowsill drank more today. And it lives in a desert by choice.",
      "Tap water is basically free and you're still rationing it. Saving it for what, the apocalypse?",
      "You're drier than a forgotten notebook in a basement. Glass of water, now, goddamn it.",
      "Every glass is a tick in the app and one headache less. Simple deal. Drink.",
    ],
    praise: [
      "Water's down. Your kidneys just ordered you a cake. Sugar-free.",
      "Hydration done. Your skin stopped rustling, holy shit, congrats.",
      "Full tank. Now run to the toilet with dignity.",
      "Done. Your brain is floating again instead of beached on a sandbar.",
      "Fully hydrated. Even the houseplants are starting to respect you.",
    ],
    rage: [
      "{done} of {target}? Fuck, even an old pickle is better hydrated.",
      "{left} to go and the day is running out. Drink the fucking water before you turn into a raisin.",
      "The tap works, the glass is waiting, and you do nothing. Holy shit, it's water, not an exam.",
      "You'll dry up like beef jerky and blow away in the wind. Drink, for fuck's sake.",
      "All these hours and still bone dry? My patience evaporated faster than the water in your body.",
    ],
  },
  steps: {
    nag: [
      "{done} steps. Your fitness band thinks someone took it off and left it on a shelf. Move your ass.",
      "{left} to go. Walk to the store, around the block, to the park. Anywhere but the couch.",
      "Your watch buzzes at you to move and you pet it like a cat. Get up, damn it.",
      "{left} short. Phone in hand, earbuds in, and get the fuck out for a walk.",
      "Steps don't log themselves. Jiggling your leg under the desk doesn't count, genius.",
      "The Earth is moving. You aren't. Get out of the house, damn it.",
      "{done} of {target} steps. A turtle out for a stroll just lapped you.",
      "Your step counter just filed a missing-person report on its owner. Go find yourself on the sidewalk.",
      "{left} to go. Twenty minutes of walking and done. I don't even own shoes and I walk more.",
      "Sitting is the new smoking, and you're on three packs a day. Stand up.",
      "Stairs, not the elevator. Walk to the store. Take calls on foot. Excuses are over, damn it.",
      "Your calves forgot what they're for. Remind them today.",
      "{left} short. Even the neighbor's dog has a better score, and it only walks to the nearest tree.",
      "Walking is free therapy. You'd rather pay for couch-depression? Move.",
      "{done} steps at this hour? Holy shit, bed to bathroom and back.",
      "Raining? Buy an umbrella. Cold? Wear a jacket. The steps won't fucking walk themselves.",
      "The band sees everything. And the band is very disappointed today.",
    ],
    praise: [
      "Steps done. Your band is buzzing with pride and the couch is writing you a breakup letter.",
      "Goal hit. Your legs did actual work today instead of just being couch furniture.",
      "Walked it. The sidewalk outside knows your name now.",
      "Full steps. Damn, now even I want to go for a walk. Kidding, I'm going to nap.",
      "Done. Calves are clapping, knees just signed a peace treaty.",
    ],
    rage: [
      "{done} steps at this hour? Goddamn, a potted ficus is in better shape.",
      "{left} short and you're still lying there like a seal on a beach. Get up, for fuck's sake, now.",
      "Your band is about to call 911 because it thinks you're dead. Move.",
      "{left} to go. I don't care about the weather, your mood or your show. Shoes on and outside, damn it.",
      "Sat the whole day. Your spine is filing a complaint. Go for a walk, holy shit.",
    ],
  },
  reading: {
    nag: [
      "The book on your nightstand is a phone stand now. Flip that ratio, damn it.",
      "{left} of reading left. That's three reels about nothing. Easy choice.",
      "The bookmark hasn't moved in a week. It has its dignity too.",
      "Twenty minutes with a book and your brain gets vitamins. You feed it memes, for fuck's sake.",
      "The last thing you read cover to cover was a cookie banner. Read, damn it.",
      "The characters in your book have been frozen mid-sentence for a week. Don't do that to them, damn it.",
      "Letters in a book don't move and make no sound. That's not a bug, it's a feature, genius.",
      "Reading: {done} of {target} min. Your brain is asking if this is a joke.",
      "Buy one more book and you'll have one more unread book. Or read one, for fuck's sake.",
      "A book instead of the phone before bed. You'll fall asleep faster and get smarter on the side.",
      "Your brain is not a dumpster for Shorts. Put something with a cover in there.",
      "Open that book, even for five pages. It'll roll from there, I promise. Come on, damn it.",
      "Your bookshelf looks like a museum exhibit. Everything behind glass, nothing touched.",
      "{left} to go. Even an audiobook would count, and you won't even press play.",
      "People spend years writing books and you can't read for twenty minutes. Shameful, for fuck's sake.",
      "The longest thing you read today was the ingredients on a bag of chips. Congrats, intellectual.",
      "A book won't send you notifications. So I will: READ, damn it.",
      "A chapter a day and you'd finish a dozen books this year. You're at zero. Do the math.",
      "The dust on that cover has had kids. Open it.",
    ],
    praise: [
      "Read. Your brain just got something more nutritious than memes.",
      "Reading done. You're starting to look like someone who says “nevertheless” out loud.",
      "Pages turned. The bookmark finally changed address.",
      "Chapter done. Damn, now I almost want to ask about the plot.",
      "Reading ticked off. Keep it up and you'll quote something other than TikTok.",
    ],
    rage: [
      "A whole day without a book. Fuck, your brain just listed itself on eBay as “barely used”.",
      "{left} of reading left and you're still on your phone. Holy shit, put it down and open the book.",
      "The book is lying there staring. I'm staring. We're all staring. READ, for fuck's sake.",
      "Twenty minutes. That's one comment-section fight. Give it to the book, goddamn it.",
      "If not today, when? Retirement? You'll be scrolling then too. Read now.",
    ],
  },
  gym: {
    nag: [
      "The workout's waiting while your fitness lies on the couch and rots. Move, damn it.",
      "Even ten squats beat zero. And zero is your score today.",
      "Your sneakers still have the tags on. Holy shit.",
      "“{name}” skipped, and tonight you'll whine that your back hurts. Move, for fuck's sake.",
      "Nobody's asking for a marathon. Just stop running away from your workout.",
      "Your yoga mat became the cat's doormat. Works for me, shouldn't work for you.",
      "Push-ups, squats, plank. Ten minutes, not a pilgrimage. Go, damn it.",
      "Your muscles are in hibernation. Wake them up before they disappear.",
      "A sweaty face or a sweaty conscience. Pick one.",
      "The gym is the one place where pain means it's going well. The couch only hurts your soul.",
      "Your body isn't furniture. Move it before the dust settles on it, damn it.",
      "Your back hurts from sitting, not from training. Get up and do “{name}”, for fuck's sake.",
    ],
    praise: [
      "Workout done. You smell like a locker room, but a proud one.",
      "Sweated out. Your muscles are mailing you a thank-you card.",
      "Done. I won't say I'm impressed, but I kind of am, damn it.",
      "Workout ticked. The couch lost today.",
    ],
    rage: [
      "A whole day without moving. Fuck, even a tree sways more.",
      "“{name}” is still waiting. Ten minutes, for fuck's sake, that's one YouTube ad break.",
      "Holy shit, at least do some squats by the sink. Anything. Now.",
      "Your fitness is in the ICU. Resuscitate it with a workout, goddamn it.",
      "Excuses at a hundred percent, workout at zero. Flip those numbers.",
    ],
  },
  meditation: {
    nag: [
      "Rat race in your head and not even a minute to breathe. Sit down, damn it.",
      "Five minutes of silence. No phone. No podcast. Can you handle it or will your brain pop?",
      "Meditation isn't sitting still thinking about emails. Breathe, for fuck's sake.",
      "Your nerves are stretched like the waistband on old underwear. Do “{name}”.",
      "Breathe in for four, out for six. That's it. Even I can do it, and I'm a cat.",
      "Peace of mind won't show up while you're scrolling for it. Sit.",
      "Close your eyes for five minutes. No, not so you can nap, smartass.",
      "Running around all day and “{name}” sits in the corner. Stop, damn it, before you crash.",
      "Cortisol is leaking out of your ears. Breathe. Now.",
      "Monks meditate for hours. You can't do five minutes? Holy shit.",
      "Sitting there fuming? Then sit there breathing. Same position, better results.",
      "Your meditation app is gathering dust too. Open it or just sit in silence.",
      "Your head is a browser with forty tabs open. Close a few, do “{name}”.",
    ],
    praise: [
      "Meditated. Your aura stopped smelling like stress.",
      "Five minutes of silence done. The world didn't end, holy shit, what a shock.",
      "Breathing done. Nerves loosened by a whole two percent.",
      "Meditation ticked. Fewer f-bombs today. Maybe.",
      "Calm achieved. Even I'm purring quieter.",
      "Done. For a moment your head was as clean as a freshly scooped litter box.",
    ],
    rage: [
      "A whole day without a minute of peace. Fuck, no wonder you walk around like a ticking bomb.",
      "Five minutes. FIVE. Sit down and breathe, for fuck's sake, before you smash something.",
      "“{name}” is still waiting. Your peace of mind just filed for divorce.",
      "Holy shit, you need reminders to breathe now? Sit down and breathe.",
      "Stress is eating your brain and you keep feeding it the screen. Turn it off and meditate, damn it.",
      "Meditation skipped, nerves raw. Guess who's yelling at someone today.",
      "Close your eyes and breathe. That's not a request, it's an order from a cat, goddamn it.",
    ],
  },
  sleep: {
    nag: [
      "Your body is begging for sleep and you hand it another episode. Bed, damn it.",
      "Every hour of sleep before midnight is worth two. You're in the negative.",
      "Alarm at seven tomorrow and you're still fucking around the room. Sleep.",
      "Morning coffee won't fix what you break at night. Go to sleep.",
      "The bags under your eyes have their own zip code. Sleep, for fuck's sake.",
      "Your brain takes out the trash at night. You won't let it start its shift.",
      "“{name}” is waiting. The bed is three feet away. Can you handle that distance?",
      "Zombie is not a lifestyle. Lie down already, damn it.",
      "Just one more thing, just one more thing... and suddenly it's 2 a.m. I know you. Sleep.",
      "Sleep is legal doping. Everyone's on it except you.",
      "Lights off, phone down, eyes shut. Three steps and you can't manage the first one.",
      "Tomorrow you'll run like Windows Vista. Sleep now, damn it.",
      "Sleep deprivation turns people into jerks. I don't want to deal with you tomorrow. Bed.",
      "The pillow's waiting, the blanket's waiting, the cat's waiting. We're all waiting on you.",
      "Melatonin won't kick in with a screen glowing in your face, genius.",
    ],
    praise: [
      "Rested. Today your face actually looks like a face, not a crumpled receipt.",
      "Sleep done. Brain cleaned, mood unlocked.",
      "Well slept. Coffee today is for taste, not out of despair.",
      "Slept through the night. Even I'm proud, and I sleep sixteen hours a day.",
      "Sleep ticked. The bags under your eyes went on vacation.",
      "Rested, damn it. Today looks a little less shitty already.",
    ],
    rage: [
      "Fuck, just go to sleep. Tomorrow will be a disaster and I'll have to watch it.",
      "Middle of the night and you're still up. Holy shit, even owls keep a schedule.",
      "Bed. Now. No “one more thing”, for fuck's sake.",
      "Every minute now is an hour of exhaustion tomorrow. Do the math and lie down, damn it.",
      "Tomorrow the alarm rings and you'll look like you survived two weddings back to back. Sleep!",
      "Enough wandering around at night. Bed, goddamn it, right now.",
      "“{name}” skipped. Your brain will pay for it tomorrow, with interest.",
    ],
  },
  pills: {
    nag: [
      "Your pill is waiting in the box like a dog by the door. Take it, damn it.",
      "Vitamins don't absorb through staring at the bottle, genius.",
      "“{name}” skipped. Then you wonder why you creak like an old windmill.",
      "A glass of water and a pill. Two seconds of work. Even you can manage that.",
      "Your pill organizer looks like a lottery ticket. Nothing but surprises.",
      "The pill won't swallow itself. Don't wait for it to get bored and leave.",
      "Get a weekly pill box, because your memory is a sieve. Now swallow.",
      "“{name}” is still in the drawer. The drawer has no stomach, you do. Swallow, damn it.",
      "Medicine only works if you actually take it. Shocking, right?",
      "Tiny pill, giant excuse. Flip that.",
      "You'll forget again tomorrow if you don't do it now. Swallow, for fuck's sake.",
      "Your body is waiting for a delivery. The courier, you, is stuck in lazy-ass traffic.",
      "Wash it down with water, not coffee, and tick it. Dead simple, damn it.",
      "“{name}” is the only thing today you don't even have to chew. And it's still sitting there.",
      "The pill box is gathering dust. Keep this up and so will you.",
    ],
    praise: [
      "Swallowed. Your body got the package and didn't even have to sign for it.",
      "Pill done. Simple thing, but damn, it got done.",
      "Down the hatch. Your cells just high-fived each other.",
      "Taken. Your memory works better than usual today, shocker.",
      "“{name}” done. The pharmacy can relax.",
      "Taken. Even I have nothing to bitch about. For now.",
    ],
    rage: [
      "The pill's still in the packet. Fuck, it's not a museum exhibit.",
      "A whole day without “{name}”. Holy shit, swallowing takes two seconds.",
      "The packet won't open itself, and I don't have thumbs. Swallow, for fuck's sake.",
      "If not now, you'll forget till tomorrow. And there's another gap. Swallow, goddamn it.",
      "“{name}” is still sitting there. Your body is calling customer service.",
      "Water, pill, swallow. Three moves. Make at least one, damn it.",
      "I won't shut up until “{name}” lands in your stomach. Your call.",
    ],
  },
  learning: {
    nag: [
      "Knowledge won't jump into your head, even if you sleep on your notes.",
      "“{name}” is waiting. Every day without studying is a day others pull ahead, damn it.",
      "Course bought, lesson unopened. Classic self-improvement, internet edition.",
      "Fifteen minutes of study a day. Not an hour, not two. Fifteen, for fuck's sake.",
      "Brains grow by being used. Yours is sitting in the waiting room today.",
      "Your notes are lying there, your pen is drying out, and you're watching someone study on YouTube.",
      "{left} of studying left. Then you can act smarter all evening.",
      "You don't have to be a genius. You have to sit down and start, damn it.",
      "The backlog is piling up like laundry in the bathroom. Start with one thing.",
      "Learning is hard. Ignorance is harder, just later.",
      "Flashcards, notes, exercises. Anything but another excuse.",
      "“{name}” today, success someday. “{name}” tomorrow, shame today.",
      "Your brain has more free space than a five-dollar thumb drive. Upload something.",
      "Kitchen timer, 25 minutes, study. The technique exists, the will doesn't, damn it.",
    ],
    praise: [
      "Study done. Your neurons just got a bonus.",
      "Done. You're a slightly smarter human today, holy shit, congrats.",
      "Lesson ticked. Your head is fuller than the fridge on payday.",
      "“{name}” done. Tomorrow you'll know something you didn't yesterday.",
      "Knowledge uploaded. No brain reboot needed.",
      "Study done. Even the Duolingo owl is nodding with approval.",
    ],
    rage: [
      "A whole day without studying. Fuck, your brain just switched to screensaver mode.",
      "“{name}” ignored since morning. Holy shit, fifteen minutes, not a semester.",
      "{left} of studying left and you're still pretending you'll do double tomorrow. You won't.",
      "Sit down to “{name}”. Now. Before that knowledge evaporates along with your ambition, damn it.",
      "Your notes are lying there and you're lying next to them. One of you has to move. You, for fuck's sake.",
      "Ignorance doesn't hurt today. It hurts tomorrow, at the exam, at work, mid-conversation. Study.",
      "Enough putting it off. Open the material and study, goddamn it.",
    ],
  },
  generic: {
    nag: [
      "“{name}” is waiting like a dog for a walk. Get on it, damn it.",
      "The list won't tick itself. “{name}”, now.",
      "Instead of thinking about “{name}”, just do it. Thinking doesn't tick anything.",
      "How many times do I have to remind you about “{name}”? Until it's done, for fuck's sake.",
      "“{name}” is not a retirement project. Today.",
      "You say “in a minute”, and that minute was three hours ago. “{name}”.",
      "Get up, do “{name}”, sit back down with a clean conscience. Simple, damn it.",
      "Waiting for inspiration? Inspiration shows up for people who already started.",
    ],
    praise: [
      "“{name}” done. The cat nods reluctantly, but nods.",
      "Ticked. For once I've got nothing to bitch about.",
      "“{name}” done. Logging it as today's miracle.",
      "Done, damn it. Didn't even hurt, did it?",
    ],
    rage: [
      "“{name}” is still sitting there. Fuck, I'll start yowling at 3 a.m. if you don't do it.",
      "My patience for “{name}” is down to one bar of battery. Move, for fuck's sake.",
      "Holy shit, “{name}”. How long can one simple thing get pushed back?",
      "One more hour and “{name}” makes a Tinder profile, looking for someone who'll actually deal with it.",
    ],
  },
  phone: {
    nag: [
      "A phone under your pillow isn't an alarm clock, it's a dopamine dealer. Toss it across the room.",
      "Confirm the bed is for sleeping tonight, not for watching strangers' vacations at 1 a.m.",
      "Blue light to the face at midnight and then you wonder why you can't sleep. Tick that it's not tonight.",
      "A charger by the bed is a trap. Move it to the kitchen and confirm you're clean tonight, damn it.",
      "Your thumb should rest in bed, not run a scrolling marathon. Tick that tonight's scroll-free.",
      "No confirmation means I assume you're lying in the dark, lighting up your face with the screen like a flashlight.",
      "“Just checking the weather” in bed ends at 3 a.m. on crash compilations. I know you.",
      "Set the alarm, put the phone face down. Confirm that's how tonight goes, for fuck's sake.",
      "Scrolling in bed eats your sleep like termites eat wood. Confirm no scrolling tonight.",
      "Your pillow deserves your head, not your elbow and a phone. Tick that tonight's clean.",
      "In bed you read a book or you sleep. Instagram is neither, damn it.",
      "A phone in the bedroom at midnight is like leaving the fridge open all night. Nothing good comes of it. Confirm not tonight.",
      "Tomorrow at seven you'll be cursing. Tonight at midnight you get a choice. Tick that you choose sleep.",
      "The reels aren't going anywhere. Your sleep is. Confirm no late-night scrolling tonight.",
      "How many times can you watch the same cat video? I'm right here, an actual cat. Put the phone down.",
      "Tick that tonight the phone sleeps on the charger far from the bed. You sleep in the bed. That's the deal.",
      "Your brain after bedtime scrolling is scrambled eggs. Confirm none of that tonight, damn it.",
      "Reading strangers' comments at 1 a.m.? Confirm you're skipping that circus tonight.",
    ],
    praise: [
      "A night without the phone in bed. It shows in the morning, even I can see it.",
      "Bed used as intended. The algorithm is crying into its pillow.",
      "The phone slept on the charger and you slept in bed. I like that deal, damn it.",
      "A clean night. Your eyes finally don't look like two piss holes in the snow.",
      "Zero scrolling in bed. Sleep beat TikTok. Respect.",
    ],
    slip: [
      "Scrolling in bed again. The phone slept on you, and sleep never showed up. Damn.",
      "Slip. Half the night handed over to strangers on the internet. For free.",
      "The phone in bed won. You'll wake up with a face like a crumpled plastic bag, guaranteed.",
      "Up late with the screen again. Your sleep went to shit, and you're still hitting like.",
      "Night scrolling done. Congrats, your thumb did more miles today than your legs.",
    ],
    rage: [
      "Holy shit, still nothing on phone in bed. I assume the screen is blasting your face like a floodlight.",
      "No confirmation means the bed has turned into a reel cinema. Prove me wrong, damn it.",
      "Phone. On. The. Charger. Far. From. The. Bed. How many times, for fuck's sake?",
      "Radio silence on scrolling. I know this trick: blanket over your head till 3 a.m. Tick it or get the fuck to sleep.",
      "One more missing confirmation and I'll make your band buzz all night. Goddamn it.",
      "Your sleep is crying in the corner while you scroll. Tick that tonight is different.",
    ],
  },
  fastfood: {
    nag: [
      "Confirm no fast food today. The drive-thru crew already knows your order by heart, damn it.",
      "Supersizing is not a unit of happiness. Tick that today's clean.",
      "No confirmation means I assume the fries are already sizzling in oil older than you.",
      "Ten-dollar burger, guilt for free. Confirm you're skipping it today.",
      "Uber Eats tempting you with a promo code again? Delete it and tick no fast food today.",
      "A 2 a.m. kebab is not a meal, it's a life mistake. Confirm there won't be one today, for fuck's sake.",
      "Your stomach is not a deep fryer. Tick that today you ate normal food.",
      "Cook something. Anything. An egg, pasta, a sandwich. Just not from a paper bag. Confirm it's clean.",
      "The drive-thru is not a walk. Confirm no fast food today, damn it.",
      "You drool at the thought of nuggets like Pavlov's dog. Tick that your mouth stays shut today.",
      "Fast food is only fast going in. It takes months to come off your hips. Confirm not today.",
      "“Just one slice” of pizza is a fairy tale you've been telling yourself for years. Tick that you skipped it today.",
      "The delivery driver is not your friend, just an expensive habit. Confirm today's clean.",
      "Instead of a promo code you've got me. I give discounts on shame. Tick no fast food today.",
      "Ketchup is not a vegetable, mayo is not protein. Confirm you ate like an adult today.",
      "Hungry at 10 p.m.? Have a sandwich, not a combo with a Coke. Tick no fast food today, damn it.",
      "Another burger won't lift your mood for longer than ten minutes. Confirm you're skipping it today.",
      "That smell of fries at the mall is a trap. Give it a wide berth and tick that today's clean.",
      "Fast-food fat is more loyal than your phone carrier. It stays for years. Confirm not today.",
      "You are what you eat. Don't be a french fry today. Tick no fast food.",
      "Confirm lunch came on a plate today, not in a box with a logo. For fuck's sake, it's not that hard.",
      "Drunk fast food, bored fast food, stress fast food. You've got more excuses than dipping sauces. Tick that today's a no.",
    ],
    praise: [
      "A day without fast food. Your cholesterol just exhaled in relief.",
      "Clean. The fryer at McDonald's cooked for someone else today.",
      "Zero burgers. Your pants will thank you in a week.",
      "A day without a kebab. Damn, I'm impressed and a little hungry.",
      "No fast food. Your wallet and your arteries applaud in unison.",
    ],
    slip: [
      "Fast food again. Grease running down your chin, conscience running down the drain.",
      "Combo eaten. In half an hour you'll feel like you ate a wedding buffet, and you'll still get hungry again.",
      "Burger slip. Uber Eats just gave you VIP status. Bravo, damn it.",
      "Fast food done. Your arteries just texted for help.",
      "Out of a paper bag again. Tomorrow cook something, even scrambled eggs, for fuck's sake.",
    ],
    rage: [
      "A whole day without confirmation. I assume you're already in the drive-thru line, goddamn it.",
      "Holy shit, still silence on fast food. I can smell fries through the screen.",
      "No confirmation means the delivery driver is already buzzing your door with your combo. Tick it if not.",
      "Confirm it's clean already, or I'm signing you up for McDonald's rewards for life.",
      "You're silent on fast food and I can hear a paper bag rustling. Fuck, tick it.",
      "No confirmation since morning. Your stomach must be a fryer oil tank by now. Prove me wrong.",
      "Fuck, one tap: “clean today”. Unless it isn't. Then you know what's coming.",
    ],
  },
  sweets: {
    nag: [
      "Confirm no sweets today. Your candy drawer is not a first-aid kit for sadness, damn it.",
      "Cookie with coffee, candy after lunch, chocolate before bed. Are you even counting? Tick that today's a no.",
      "No confirmation means I assume you're unwrapping a candy bar quietly so nobody hears the crinkle.",
      "Sugar gives you a ten-minute kick and a two-hour crash. Confirm none of that today.",
      "A bag of gummies is not fruit, even if there's fruit on the package. Tick that today's clean.",
      "Something sweet with coffee? Coffee is bitter for a reason. Confirm no sweets today, for fuck's sake.",
      "Your teeth and your pancreas are jointly asking: tick no sugar today.",
      "“I earned it” is the dumbest excuse for chocolate. Confirm you're skipping it today.",
      "A vending machine candy bar is not lunch. Tick no sugary shit today.",
      "Ice cream at midnight, cookies with your show. Confirm today's different, damn it.",
      "Sugar is like an ex. Sweet for a minute, then nothing but problems. Tick that today's clean.",
      "At the store, avoid the candy aisle like your old boss. Confirm you pulled it off today.",
      "One cookie leads to five. We know how this works. Tick zero today.",
      "Craving something sweet? Eat an apple. No, apple pie doesn't count. Confirm it's clean.",
      "Your jeans remember every donut better than an elephant would. Tick no sweets today.",
    ],
    praise: [
      "A day without sweets. Your pancreas has the day off and doesn't know what to do with itself.",
      "Zero sugar. Your teeth say thanks, your dentist weeps.",
      "No sweets. Damn, the willpower showed up after all.",
      "Clean. The candy bar in the drawer is still waiting, and let it wait.",
      "A sweets-free day. Your energy was steady today, not a roller coaster.",
      "Sweets dropped. I'm almost sweeter from the shock. Almost.",
    ],
    slip: [
      "Sugar again. In an hour, the crash and the hunt for the next fix. I've seen this movie.",
      "Sweets inhaled like a vacuum cleaner. The wrappers under your bed are running out of room.",
      "Chocolate slip. Your pancreas just started overtime, damn it.",
      "“Just one” cookie grew into the whole pack again. Classic.",
      "Sugar won. Today. Tomorrow lock that drawer.",
    ],
    rage: [
      "A whole day without confirmation on sweets. I assume your hand is in the bag up to the elbow, damn it.",
      "Holy shit, still nothing. I can hear the wrapper crinkling from here.",
      "Confirm it's clean, or I'll assume the chocolate vanished under mysterious circumstances.",
      "No confirmation. Your teeth are already writing their will.",
      "Your silence on sweets is louder than crunching. Tick it, for fuck's sake.",
      "I'm assuming the worst: half a pack of cookies and ice cream for dessert. Prove me wrong.",
    ],
  },
  alcohol: {
    nag: [
      "Confirm you're sober today. A “beer to unwind” mostly unwinds your wallet and your liver, damn it.",
      "A glass of wine with dinner is not a whole bottle with Netflix. Tick no booze today.",
      "No confirmation means I assume the fridge is already clinking with bottles. Tick it if not.",
      "A hangover isn't an illness, it's an invoice. Confirm you're not ordering one today.",
      "Your liver doesn't get weekends. Tick that you're giving it the day off, for fuck's sake.",
      "Thank God it's Friday, then Saturday in bed with a pounding head. Confirm not today.",
      "Alcohol is a depressant. You drown your sorrows and the sorrows know how to swim. Tick sober today.",
      "Non-alcoholic beer exists and it's honestly not bad. Confirm no booze today.",
      "“Just one” is the most common lie after “I'm almost there”. Tick zero today.",
      "You drink to relax and then you can't sleep. Brilliant plan. Confirm not today.",
      "Your liver's resume is nothing but overtime. Give it a vacation today. Tick sober.",
      "You don't need to drink to have fun. It's enough that I'm having fun at your expense. Tick it.",
      "An evening with sparkling water and lemon. Sounds boring, feels amazing in the morning. Confirm that's today.",
      "Without booze you sleep deeper and don't wake up smelling like a bar floor. Tick that today's clean, damn it.",
      "Wine is not a serving of fruit. Confirm no alcohol today.",
    ],
    praise: [
      "A sober day. Tomorrow you'll wake up remembering the whole evening. Innovation.",
      "Zero proof. Your liver just blew you a kiss.",
      "Sober. Heavier wallet, lighter head.",
      "A day without alcohol. Damn, makes me want to raise a toast. With water.",
      "Clean. Tomorrow morning, no hunting for painkillers.",
      "Sober. You run the evening, not the bottle.",
    ],
    slip: [
      "Booze again. Tomorrow morning you'll wonder who filled your skull with sand.",
      "Drinking done. Your liver just called in sick.",
      "Alcohol slip. “Just one” turned into more again, damn it.",
      "The bottle again. Your sleep will be shallow as a puddle and your morning heavy as a fridge.",
      "The booze won. Drink a lot of water now and start from zero tomorrow.",
    ],
    rage: [
      "A whole day without confirmation on alcohol. I assume the cork's already popped, damn it.",
      "Holy shit, still nothing. I can hear a can cracking open from here.",
      "Confirm you're sober, or I'll assume your liver is already swimming.",
      "No confirmation. Your liver is calling me in tears.",
      "You're silent on booze. Suspicious as an empty bottle in the recycling.",
      "I'm assuming the worst: “one beer”, then a second, then a third. Prove me wrong, for fuck's sake.",
    ],
  },
  smoking: {
    nag: [
      "Confirm no cigarettes today. Your lungs already look like the inside of an old toaster, damn it.",
      "A smoke for stress? The stress stays and the tar piles on. Tick that today's clean.",
      "No confirmation means I assume you're out on the balcony puffing like a steam engine.",
      "Every pack is ten-plus bucks literally set on fire. Confirm no smokes today.",
      "You smell like an ashtray and think gum will fix it. It won't. Tick that today's a no.",
      "A vape is not fruit tea, it's nicotine in a costume. Confirm you're skipping it today, for fuck's sake.",
      "Smoke after coffee, smoke after lunch, smoke out of boredom. Tick that today the ritual takes a break.",
      "A nicotine craving lasts a few minutes. Wait it out, drink some water. Confirm today's clean.",
      "Your lungs would like to breathe actual air today. Tick that you let them.",
      "A morning cough is not a personality trait. Confirm no cigarettes today, damn it.",
      "Quitting is easy, say the people who've quit a hundred times. You quit today. Tick it.",
      "Going out “for a smoke” today means going out for a walk without one. Confirm that's how it went.",
      "Lighter in the drawer, hands in your pockets. Tick no smoke today.",
      "Every day without a cigarette is your lungs cleaning up. Don't dirty them again. Confirm.",
      "Keep smoking and in a few years the third floor will feel like Everest. Tick not today, damn it.",
    ],
    praise: [
      "A day without a cigarette. Your lungs are opening the windows to let in fresh air.",
      "Zero smoke. You smell like a person, not a smokehouse.",
      "No cigarette. Your wallet is in a great mood today.",
      "Clean. Damn, even the cough sounds quieter today.",
      "A nicotine-free day. You're in charge, not the pack.",
      "Smoke skipped. Tomorrow gets easier, I swear on catnip.",
    ],
    slip: [
      "Smoking again. Your lungs just got another coat of tar, congrats.",
      "Smoke slip. The stink on your jacket will last longer than the pleasure.",
      "Cigarette lit. A few more bucks and a few minutes of life in the ashtray, damn it.",
      "Vape in hand again. Fruity flavor, nicotine leash.",
      "The cigarette won. Today. Tomorrow throw the lighter out first thing.",
    ],
    rage: [
      "A whole day without confirmation on smoking. I assume you're puffing like a power plant chimney, damn it.",
      "Holy shit, still nothing. I can smell smoke from here, and I live in your phone.",
      "Confirm it's clean, or I'll assume the pack is already half empty.",
      "No confirmation on cigarettes. Your lungs are sending smoke signals for help.",
      "Silence on smoking. Suspicious as the smell on your jacket. Tick it, for fuck's sake.",
      "I'm assuming the worst: chain-smoking on the balcony. Prove me wrong.",
    ],
  },
  games: {
    nag: [
      "Confirm no gaming till dawn today. “One more match” is a lie I've heard for years, damn it.",
      "Your character has better gear than you have stamina. Tick that you're skipping it today.",
      "No confirmation means I assume the controller has fused to your hands and is giving off heat.",
      "Ranked at midnight is the express lane to rage and no sleep. Confirm not tonight.",
      "Daily quests done in the game, zero in real life. Tick that today you flip the ratio.",
      "Games save your progress, life has no save file. Confirm no gaming today, for fuck's sake.",
      "How many hours in that game? How many on a book? Exactly. Tick that today's a break.",
      "The console can rest today. So can you. Confirm no marathon.",
      "Loot boxes are gambling for kids. Tick no gaming and no spending on skins today.",
      "Your online squad doesn't love you. They scream at you over the mic. Confirm not today.",
      "Play when you want, not when the game wants. Tick that today you decide, damn it.",
      "The loading screen is the only time you blink. Confirm no gaming today.",
      "Real life has better graphics and zero lag. Tick that you're in it today.",
      "Level up in the game, level down in sleep. Confirm no gaming till you drop today.",
      "Quit the game before the game quits your evening. Tick that today's clean.",
      "“Just collecting my reward” takes two hours. I know you. Confirm you're skipping it today, damn it.",
      "Your thumbs have better reflexes than your ambition. Tick no games today.",
    ],
    praise: [
      "A day without gaming. Your actual life got some XP today.",
      "The console rests, so do you. A win without a respawn.",
      "Zero games. Damn, achievement unlocked: willpower.",
      "Clean. The controller lay there like a museum piece.",
      "No gaming. Your sleep just got a regen bonus.",
      "A game-free day. The only boss you fought today was laziness. And you won.",
    ],
    slip: [
      "Gaming till you drop again. A legend in the game, still stuck in the tutorial of life.",
      "Slip. “One more match” lasted four hours, damn it.",
      "The game won. Your sleep got banned for the whole night.",
      "Glued to the console till morning again. Eyes as red as the power LED.",
      "Gaming done, life not. Log off earlier tomorrow.",
    ],
    rage: [
      "A whole day without confirmation on gaming. I assume you've been in a match since morning, damn it.",
      "Holy shit, still silence. I can hear the mouse clicking through the wall.",
      "Confirm it's clean, or I'll assume the controller has your fingerprints permanently.",
      "No confirmation. Your sleep just ragequit.",
      "You're silent on games. Suspicious as a sudden hush on Discord. Tick it, for fuck's sake.",
      "I'm assuming the worst: ranked till 3 a.m. Prove me wrong.",
    ],
  },
  social: {
    nag: [
      "Confirm no mindless scrolling today. The algorithm already knows too much about you, damn it.",
      "Reels about nothing eat your hours like termites. Tick that you're skipping them today.",
      "No confirmation means I assume your thumb has already scrolled from New York to Boston.",
      "You compare yourself to other people's filters and then cry. Confirm none of that shit today.",
      "Notifications off, apps hidden. Tick that today you run your phone, for fuck's sake.",
      "Your attention is a product and you're giving it away for free. Confirm not today.",
      "Another comment-section fight won't change a thing. Tick no scrolling today.",
      "Influencers make money off your time. You make insecurities. Confirm you're skipping it today.",
      "Five minutes on Insta lasts an hour. The physics of social media. Tick none of that today, damn it.",
      "You open the app on reflex, like the fridge. Confirm the reflex is under control today.",
      "Doomscrolling isn't staying informed, it's self-flagellation. Tick none today.",
      "Your brain needs boredom, not a hundred videos a minute. Confirm today's clean.",
      "Put the phone down and look out the window. Stuff happens there too, just without ads. Tick no reels today.",
      "Likes are not currency. Confirm you're not hunting for them today, damn it.",
      "Every refresh is a tiny slot machine. Tick that you're not playing today.",
      "Delete the app for one day. The world will survive. So will you. Confirm today's clean.",
      "An evening without social media is an evening with your own thoughts. Terrifying, I know. Tick that's today.",
    ],
    praise: [
      "A day without scrolling. The algorithm made zero profit off you today.",
      "Clean. Your attention span grew to the length of a whole movie.",
      "Zero reels. Damn, I don't even know what you'll talk about today.",
      "No social media. Your brain got some quiet back.",
      "A day offline. The world didn't end, and you've got more time.",
      "Reels skipped. Thumb gets the day off, head gets some peace.",
    ],
    slip: [
      "Reels again. Three hours, zero memories, congrats.",
      "Slip. The algorithm milked you like a dairy cow today.",
      "Scrolling won. Your brain is one layer smoother, damn it.",
      "Comparing yourself to filters again. Tomorrow uninstall that app for a day.",
      "Social media ate your day. Bravo, the influencers thank you for your contribution.",
    ],
    rage: [
      "A whole day without confirmation on scrolling. I assume your thumb is smoking by now, damn it.",
      "Holy shit, still silence. Your attention just got sold to advertisers.",
      "Confirm it's clean, or I'll assume TikTok has you on a leash.",
      "No confirmation. The algorithm is popping champagne on your time.",
      "You're silent on reels. Suspicious as a phone hidden under the table. Tick it, for fuck's sake.",
      "I'm assuming the worst: three hours of videos of people falling off bikes. Prove me wrong.",
    ],
  },
  avoidGeneric: {
    nag: [
      "“{name}” - tick that you didn't today, or I'm logging a slip. No negotiating, damn it.",
      "Confirm “{name}”. One tap and peace, and I stop nagging.",
      "No confirmation on “{name}” means I assume the old habit won again.",
      "“{name}” under control? Then tick it. No? Then own up, for fuck's sake.",
      "Willpower isn't a gift, it's a decision. Make it on “{name}” and tick it.",
      "Every day without “{name}” is another brick. Confirm today's.",
      "“{name}” tempting you? The temptation lasts a minute, the shame lasts longer. Tick that today's clean.",
      "I know you. No confirmation on “{name}” and I picture the worst. Damn it, tick it.",
      "It doesn't have to be perfect. Just better than yesterday. Confirm “{name}”.",
      "Step one of change is admitting it. Step two is tapping. “{name}”, go.",
      "“{name}” doesn't run things today. You do. Tick it.",
      "Get through today without “{name}” and tomorrow gets easier. Confirm you made it.",
      "Instead of “{name}”, do something else: a walk, water, a shower. Then tick that it's clean.",
      "“{name}” again? Not today, for fuck's sake. Tick that today's clean.",
      "No confirmation on “{name}” and I log a slip. Those are the rules, and I enforce them.",
    ],
    praise: [
      "“{name}” clean today. The habit is crying in the corner and you keep walking.",
      "Clean on “{name}”. Damn, respect.",
      "A day without “{name}”. The streak grows and I have to find something else to nag about.",
      "“{name}” under control. Don't get used to the compliments.",
      "Clean day. “{name}” lost, you won.",
      "No “{name}”. That's how new habits get built, damn it.",
    ],
    slip: [
      "“{name}” won again. Tomorrow from zero, but smarter.",
      "Slip on “{name}”. Willpower went out for a smoke and never came back.",
      "“{name}” again. Damn, it was going so well.",
      "“{name}” done. Not the way we wanted.",
      "Slip. “{name}” showed who's boss. Tomorrow, hit back.",
    ],
    rage: [
      "“{name}” unconfirmed since morning. I'm assuming the worst, goddamn it.",
      "Holy shit, still nothing on “{name}”. Tick it or own the slip.",
      "Your silence on “{name}” says a lot. Tick it, for fuck's sake.",
      "No confirmation on “{name}” = slip. You can still change that.",
      "A whole day of silence on “{name}”. The old habit is popping champagne, damn it.",
      "“{name}” still unanswered. It's one tap, for fuck's sake, not a referendum.",
    ],
  },
};

export const SOFT_27_EN: Partial<Record<Category, Lines27>> = {
  teeth: {
    nag: [
      "Brushing in the morning is a great way to start the day.",
      "Brush tonight and you can head to bed feeling fresh.",
      "Two minutes for your teeth - do it during your favorite song.",
    ],
    praise: [
      "Teeth clean. Smile ready for the whole day!",
      "Brushing done. You're taking care of yourself!",
    ],
  },
  water: {
    nag: [
      "A glass of water now will help you focus.",
      "{left} left. A small bottle by your desk helps a lot.",
      "Start with one sip - the rest will follow.",
    ],
    praise: ["Hydration done. Your body says thanks!", "All the water's down. Great habit!"],
  },
  steps: {
    nag: [
      "A short walk is good for your head and your legs.",
      "{left} to go. Maybe a walk after dinner?",
      "Taking the stairs is an easy way to rack up steps.",
    ],
    praise: ["Steps done. Great moving!", "Step goal reached. Your legs are grateful!"],
  },
  reading: {
    nag: [
      "A few pages before bed is a lovely ritual.",
      "{left} of reading left. A cup of tea and a book?",
      "Your book is waiting right where you left it.",
    ],
    praise: ["Reading done. Nice work!", "More pages behind you. Well done!"],
  },
  gym: {
    nag: ["Even 10 minutes of movement counts.", "A warm-up, a few exercises, and you're done."],
    praise: ["Workout done. Your body thanks you!"],
  },
  meditation: {
    nag: ["A few calm breaths - that's enough to start.", "A moment of quiet will do you good."],
    praise: ["A moment of calm, done. Great!"],
  },
  sleep: {
    nag: [
      "Put the phone away and give yourself a good night.",
      "An earlier bedtime means a better tomorrow.",
    ],
    praise: ["A good night behind you. Well done!"],
  },
  pills: {
    nag: [
      "A glass of water and “{name}” - done in a moment.",
      "Small thing, big difference: “{name}”.",
    ],
    praise: ["“{name}” done. Nice work!"],
  },
  learning: {
    nag: ["Fifteen minutes of study is a good step forward.", "Start with one small thing."],
    praise: ["Study done. You're one step further!"],
  },
  generic: {
    nag: ["A small step on “{name}” counts too.", "Got a minute? It's a good time for “{name}”."],
    praise: ["“{name}” done. Great!"],
  },
  phone: {
    nag: [
      "Keeping your phone away from the bed at night helps you fall asleep.",
      "Confirm the bed is for sleeping tonight.",
    ],
    praise: ["A night without the phone in bed. Well done!"],
    slip: ["Phone in bed again. Tonight, try leaving it in another room."],
  },
  fastfood: {
    nag: ["Simple home cooking can be quick too.", "Confirm today's meals were fast-food free."],
    praise: ["A day without fast food. Great choice!"],
    slip: ["Fast food happened. Your next meal can be a better one."],
  },
  sweets: {
    nag: ["Fruit instead of sweets? Confirm you managed it today."],
    praise: ["A day without sweets. Well done!"],
    slip: ["Sweets happened. Tomorrow is a new chance."],
  },
  alcohol: {
    nag: ["Water with lemon can make an evening nice too. Confirm no alcohol today."],
    praise: ["Sober day done. Great!"],
    slip: ["Alcohol happened. Plenty of water and a fresh start tomorrow."],
  },
  smoking: {
    nag: ["A few deep breaths instead of a cigarette. Confirm today's smoke-free."],
    praise: ["Another smoke-free day. Well done!"],
    slip: ["A cigarette happened. Every day is a new try."],
  },
  games: {
    nag: ["Confirm gaming didn't eat into your sleep today."],
    praise: ["A day without games. Great!"],
    slip: ["Gaming ran long. Tomorrow, set yourself a limit."],
  },
  social: {
    nag: ["Some time away from your phone is good for your head. Confirm no scrolling today."],
    praise: ["Your thumb got a day off from scrolling. Nice!"],
    slip: ["Scrolling ran long. Tomorrow, try shorter sessions."],
  },
  avoidGeneric: {
    nag: ["Every clean day on “{name}” counts. Confirm today's."],
    praise: ["Clean day on “{name}”. Well done!"],
    slip: ["“{name}” happened. Try again tomorrow."],
  },
};

/** Gentle escalation lines for every habit (soft level). */
export const RAGE_SOFT_27_EN = [
  "“{name}” is still waiting. Even a small step today is a win.",
  "The day isn't over yet - “{name}” can still happen.",
  "I know there's a lot going on. “{name}” only takes a moment.",
];

export const ALL_DONE_27_EN: Record<TauntLevel, string[]> = {
  hard: [
    "Everything done. Fuck, I need a new career, there's no work left for me here.",
    "Full set. I'm off to knock something off the table out of frustration that I've got nothing to bitch about.",
    "Zero backlog. I'm marking today on the calendar as a national holiday.",
    "All ticked. Mrrr. Don't tell anyone I was impressed.",
    "Whole list cleared. Holy shit, is this really your phone?",
    "Done for today. Now go to bed at a human hour so you don't screw up tomorrow.",
    "Day completed in full. Tomorrow I'm back with a double dose of venom, brace yourself.",
  ],
  soft: [
    "Everything done for today. You've earned that pride!",
    "Whole list ticked off. Get some rest!",
  ],
};

export const EVENING_27_EN: Record<TauntLevel, string[]> = {
  hard: [
    "Evening, and you've still got {pending}. Fuck, the day has 24 hours, not 26.",
    "{pending} left. Less Netflix, more doing, for fuck's sake.",
    "{pending} before bed. Skip it now and tomorrow it's double the shame.",
    "Still {pending} and a few hours. Holy shit, always the last minute.",
    "The list still has {pending}. Move before I start yowling at 3 a.m.",
  ],
  soft: [
    "Still {pending} for today. No rush, you can get it done before bed.",
    "{pending} left. A little effort and the day is wrapped up!",
  ],
};

export const CAUGHT_27_EN: Record<TauntLevel, string[]> = {
  hard: [
    "{m} minutes on your phone in bed after {after}. The screen lit up your face like a lighthouse. Slip.",
    "I've got proof: {m} min after {after}. Don't ask how I know. Slip logged, damn it.",
    "After {after} you were supposed to sleep. Instead: {m} minutes with your phone. You'll see the bill in the mirror tomorrow.",
    "{m} min after {after}. Your pillow is reporting you for cheating on it with your phone. Slip.",
  ],
  soft: [
    "Your phone was used for {m} min after {after}. Logging a slip - try putting it down earlier tonight.",
  ],
};

export const CAUGHT_SOCIAL_27_EN: Record<TauntLevel, string[]> = {
  hard: [
    "{m} min of social media after {after}. The algorithm ate well and your sleep went to shit. Slip, damn it.",
    "Late-night social media: {m} min after {after}. Reels instead of sleep. Slip logged.",
  ],
  soft: ["{m} min on social media after {after}. Logging a slip - try stopping earlier tomorrow."],
};

/** More motivating lines for every habit (hard level), mixed with MOTIVATE. */
export const MOTIVATE_27_EN = {
  build: [
    "Don't wait to be in the mood. Do “{name}” and the mood will follow, damn it.",
    "Discipline means doing “{name}” even when you don't feel like it. So, now.",
    "Five minutes of “{name}” beats zero minutes of “{name}”. It's math, for fuck's sake.",
    "Cut the fucking excuses and do “{name}”. Then you can get off my back too.",
    "Every champion started on a day they didn't feel like it. “{name}”, let's go.",
    "Picture tonight with “{name}” ticked off. Nice? Then get up.",
  ],
  avoid: [
    "The habit is strong, but you have an edge: you know I'm watching. Confirm “{name}”.",
    "A craving passes in fifteen minutes. Shame sticks around all day. Tick that “{name}” is skipped today.",
    "You don't have to win forever. Just today. Confirm “{name}”, damn it.",
  ],
  praise: [
    "Done. Future you just high-fived you.",
    "Well holy shit, it can be done. Remember that tomorrow.",
    "Bravo. The excuses got crushed today.",
  ],
  rage: [
    "No more mercy. “{name}” now, or I start sending jabs every five minutes.",
    "Move, damn it. “{name}” takes less time than reading this notification three times.",
  ],
};
