// English mirror of szpila-27-extra.ts - same keys, same number of lines per array, same placeholders. Not literal translations.
// Same rules: gender-neutral wording, swearing at the behaviour, never at who someone is;
// porn/pervert lines mock, never get explicit; "meals" always pushes to EAT; soft level stays polite.
import type { Lines27 } from "./szpila-27";
import type { ExtraCategory } from "./szpila-extra";

export const HARD_27X_EN: Record<ExtraCategory, Lines27> = {
  pervert: {
    nag: [
      "Confirm your eyes stayed at eye level today, not lower. It's not hard geometry, for fuck's sake.",
      "Tick that you didn't ogle strangers today like they're a supermarket clearance sale.",
      "A compliment is “that color suits you,” not licking your lips like a dog at a barbecue. Confirm you kept it classy today.",
      "No confirmation means I assume scanner mode switched on again on the bus. Tick it if not.",
      "Nobody wants your 1 a.m. “hey, you up?” texts. Confirm you didn't send one today, damn it.",
      "Respect isn't a toggle in the settings. Tick that it stayed switched on all day.",
      "Hands to yourself, comments in your head, or better yet nowhere. Confirm today was clean.",
      "Unsolicited pics? Unsolicited remarks? Unsolicited touching? Zero. Tick that today was zero, for fuck's sake.",
      "Think with your head, not with whatever's below your belt. Confirm your brain was in charge today.",
      "If it would be gross for someone to do it to your sibling or best friend, don't do it. Tick that today was clean.",
      "Pervy jokes at work aren't a sense of humor, they're an HR meeting. Confirm none today.",
      "Ogling people at the gym isn't a neck workout. Tick that you trained your own body and kept your eyes to yourself.",
      "“No” means no. “Maybe” means no. Silence means no. Confirm you get it today, damn it.",
      "No confirmation means your imagination is in heat like an alley cat in March. And trust me, I know the look.",
      "People aren't museum exhibits. Look at them like a human, then move along. Tick that you managed it today.",
      "Texting someone who hasn't replied in a week? Let it go, for fuck's sake. Confirm you let it go today.",
      "Your thoughts don't need to land in the comments under a stranger's photo. Tick that they didn't today.",
      "Act like your grandma is reading over your shoulder. Because I am. Confirm it was clean.",
      "Creeps don't get streaks. You've got one. Confirm you didn't fuck it up today.",
      "Cold shower, a walk, some work. Anything but creepy bullshit. Tick that your manners were on point today.",
      "Someone being nice isn't an invitation. Tick that nobody had to change seats on the bus because of you today.",
      "Flirting is fine when it's mutual. One-sided is harassment. Confirm you know the difference today, damn it.",
      "No sleazy double meanings in messages to coworkers today. Tick that you managed to act normal.",
      "You stare so hard people check their shirts for stains. Confirm you didn't today.",
      "An alley cat in March at least has an excuse. You don't. Tick a perv-free day.",
    ],
    praise: [
      "A perv-free day. The people around you just got to live in peace. That's how it should be.",
      "Clean. Eyes looked where they should, and hands stayed where they belong.",
      "Manners in the green today. Damn, I almost feel like purring.",
      "Zero sleazy lines. Grandma would be proud, and I'm mildly shocked.",
      "A day of treating people with respect. Simple thing, huge difference.",
      "Your brain ran the show all day, not your hormones. Well done.",
    ],
    slip: [
      "Pervy again. Get a grip and apologize if you made someone uncomfortable.",
      "Slip. Eyes and paws did their own thing again while the brain was on a smoke break, damn it.",
      "Perv moment logged. Tomorrow look people in the eye, not anywhere else.",
      "Creepy bullshit again. Cold shower, long walk, and learn from it.",
      "Behavior slip. Respecting people isn't an add-on, it's the baseline.",
      "Imagination wandered into the bushes again. Keep it on a leash tomorrow, for fuck's sake.",
    ],
    rage: [
      "Holy shit, still no confirmation on the perv front. I'm assuming the scanner is running at full power.",
      "A whole day of silence. Suspicious, like someone loitering too long outside a fitting room. Tick it, damn it.",
      "Confirm it was decent or I'm logging a slip. My goodwill has run out.",
      "Zero confirmation. I'm assuming the comments are a mile ahead of the thinking again.",
      "For fuck's sake, one tap: “I was respectful today.” Unless you weren't. Then own it.",
      "Your silence on “{name}” says more than your stares ever did. Tick it.",
      "No confirmation. Sort out your eyes, hands and thoughts, then tap, damn it.",
    ],
  },
  coding: {
    nag: [
      "Coding: {done} of {target} min. Your editor has better uptime without you than with you.",
      "{left} of code to go. It doesn't have to be pretty, it has to compile. And first it has to exist, damn it.",
      "Last commit: “wip.” From a week ago. Holy shit.",
      "Your side project is dying in a drawer like a Tamagotchi with dead batteries. Open the editor.",
      "Thirty minutes of code a day and in a year you're someone else. You'd rather stay the same. Write.",
      "You don't need to build a whole framework from scratch. One function. One test. Now, for fuck's sake.",
      "Stop changing your editor theme and start typing in it.",
      "Dark mode on, code off. Classic, damn it.",
      "AI can write the code for you, but it can't understand it for you. Sit down and figure it out.",
      "The TODOs in your code have their own TODOs now. Do at least one.",
      "Your repo has more stars from bots than commits from you. Get your shit together.",
      "Code doesn't bite. Bugs do, but only the ones you never fix. Write.",
      "{left} to go. Even refactoring one ugly function counts, for fuck's sake.",
      "Watching coding conference talks isn't coding. Keyboard, damn it.",
      "Git status: nothing to commit. Life status: nothing to show. Change both.",
      "You've had an app idea for a year. The first line still doesn't exist. Write it today.",
      "Reading the docs is half the job. The other half is writing code. Do the other half.",
      "console.log is debugging too. But first there has to be something to debug, genius.",
      "You know how to exit Vim. Getting into the code, not so much. Open the editor, damn it.",
      "Your skills are rusting faster than the dependencies in an old project. Update yourself.",
      "Even a tiny bugfix is a commit. A commit is progress. Progress means less of my bullshit.",
      "LeetCode, side project, a course. Pick anything and code for {left}.",
      "Merge conflicts with yourself get solved by writing code, not by putting it off, for fuck's sake.",
    ],
    praise: [
      "Code written. The little green squares on GitHub just bloomed.",
      "Coding done. Even if it only works on your machine, it counts.",
      "Commit made. Damn, now I want to push it.",
      "Coding checked off. Bugs are trembling, and I'm mildly proud.",
      "Done. The code might be ugly, but it exists, and that's what matters.",
    ],
    rage: [
      "A whole day, zero code. Your GitHub looks like a winter landscape. Empty and white, damn it.",
      "{left} of coding left and you're still scrolling. Holy shit, open the editor.",
      "One function. One file. One commit. I'm not asking you to write an operating system, for fuck's sake.",
      "Laptop open, editor closed. Flip that right now, fucking hell.",
      "Stop planning the architecture in your head and write something. Now.",
      "Code doesn't write itself from staring at the cursor. Keyboard, damn it, keyboard!",
    ],
  },
  language: {
    nag: [
      "Language practice: {done} of {target} min. The Duolingo owl already knows where you live.",
      "{left} to go. Fifteen minutes a day and in a year you're having conversations. Without it, you're still playing charades.",
      "Your Duolingo streak is dying and your dignity with it. Study, damn it.",
      "Vocab won't seep into your head by osmosis. Grab the flashcards.",
      "Abroad you'll order “the, uh, that thing” and point again. Study, for fuck's sake.",
      "Verb conjugations won't do themselves. Being bilingual won't happen from daydreaming either.",
      "Five new words a day is almost two thousand a year. You're at zero today.",
      "A show without subtitles? No. Study first, then you can pretend you understand it.",
      "{left} of study left. Headphones, a podcast, a walk. Two habits in one go.",
      "Native speakers weren't born with grammar in their heads. They learned. So can you, damn it.",
      "Your accent sounds like Google Translate after three beers. Practice your pronunciation.",
      "Grammar isn't the enemy. Your “I'll start on Monday” is.",
      "An app lesson takes five minutes. That's how long you spend picking what to watch. Pick the lesson.",
      "Your flashcards are sitting in a drawer forgetting you faster than you forget them. Review, for fuck's sake.",
      "Instead of scrolling in your native language, scroll in the one you're learning. At least something will stick.",
      "Dictionary on your phone, nothing in your head. Fix that today, damn it.",
      "{left} to go. Review yesterday's vocab before it evaporates completely.",
      "Talking to the mirror in a foreign language isn't crazy, it's training. Try it.",
      "Another year where “una cerveza, por favor” is your entire vocabulary? Study, damn it.",
      "A language is the key to jobs, travel and the memes you don't get right now. Study.",
      "Duolingo sends you threats and you ignore them. I'm worse than the owl, consider yourself warned.",
      "Past tenses in a foreign language won't sort themselves out. Sit down, damn it.",
      "Five minutes of review in the morning, five at night. That's it. Even you can fit that in.",
      "Only understand the chorus of your favorite songs? Time to change that. Lesson, for fuck's sake.",
    ],
    praise: [
      "Language practice done. Soon you'll order coffee without pointing.",
      "Lesson done. The Duolingo owl puts the axe down.",
      "Vocab reviewed. Your brain speaks two languages now. Well, one and a half, damn it.",
      "Done. The streak lives, and you're one step closer to a conversation without panic.",
      "Language practiced. Less embarrassment abroad, more actual talking.",
      "Study checked off. Muy bien, or however the hell they say it.",
    ],
    rage: [
      "A whole day without language practice. The Duolingo owl is loading its weapon. Metaphorically, damn it.",
      "{left} of study left. Holy shit, even one lesson in the app. One!",
      "Your streak is about to snap. Your dignity snapped ages ago. Study, for fuck's sake.",
      "Five words. FIVE. That's today's job and you're doing zero, goddamn it.",
      "You forget vocab faster than I knock mugs off a table. Review, now.",
      "Open that fucking app and do a lesson. Then you can hate me in two languages.",
    ],
  },
  porn: {
    nag: [
      "Confirm no porn today. Your incognito tab needs a vacation too, damn it.",
      "Being bored at night isn't an invitation to your browser history. Tick that today was clean.",
      "No confirmation means I assume the Wi-Fi is pulling overtime again. Tick it if not.",
      "Screen dopamine is a payday loan. You pay it back in brain fog. Confirm no porn today.",
      "Taking your phone to bed is asking for trouble. Leave it in the kitchen and tick a clean day.",
      "Real life has no filters and no script. Good. Confirm you're living in it today, for fuck's sake.",
      "Feeling the pull? Push-ups, a shower, a walk, ten minutes. Then tick that today was clean.",
      "Every clean day is your brain detoxing. Don't pour that crap back in. Confirm.",
      "Porn turns your brain to mush and your expectations into a circus. Tick that you're skipping it today, damn it.",
      "Tiredness, stress and loneliness are triggers. Call someone instead of opening a tab. Confirm it's clean.",
      "A site blocker on your phone isn't shameful, it's strategy. Set it up and tick a clean day.",
      "“Just a quick peek” is the oldest lie on the internet. Confirm no peeking today.",
      "Your clean streak is worth more than five minutes in incognito mode. Tick that you're protecting it.",
      "Your brain needs boredom to rest. Don't stuff it with porn. Confirm no porn today.",
      "No confirmation means the browser history is headed for deletion again. Tick it if not, damn it.",
      "Skip it today and tomorrow you wake up with a clearer head and a better mood. Confirm it's clean.",
      "Phone off at 11 p.m., then sleep like a functioning human. Tick a porn-free day.",
      "Porn is fast food for the brain. Cheap, quick, and you feel like shit afterwards. Confirm no porn today.",
      "You've got more strength than you think. Show it today and tick clean, for fuck's sake.",
      "Incognito mode hides nothing from yourself. Confirm you're not opening it today.",
      "Hands on the keyboard, but for work. Or on the handlebars of a bike. Tick a clean day.",
      "Evenings are the hardest. I know. That's why you confirm right now that you've got this today, damn it.",
      "Porn site algorithms want your time just like TikTok does. Don't give it to them. Tick clean.",
      "You can win this day. Tick it at the end once you have.",
    ],
    praise: [
      "A porn-free day. Your brain says thanks, and the incognito tab is gathering dust.",
      "Clean. The streak grows, and so does your self-control.",
      "Zero porn. Damn, respect. It isn't easy and you pulled it off today.",
      "Another clean day. Clearer head, calmer evening.",
      "No porn. Your browser history is as boring as a tax form today. Perfect.",
    ],
    slip: [
      "Porn slip. Close the tab, splash cold water on your face and start over tomorrow, damn it.",
      "Fell apart again. Don't beat yourself up, but figure out what triggered it and dodge it tomorrow.",
      "Porn won today. The streak is back to zero, but you keep what you learned about your triggers.",
      "Slip. The phone in bed was a bad idea again. The charger goes in the kitchen tomorrow.",
      "Incognito again. Holy shit. Tomorrow is day one of a new streak, don't waste it.",
    ],
    rage: [
      "Holy shit, still no confirmation on porn. I'm assuming the incognito tab is already warming up.",
      "A whole day of silence. Suspicious, like a phone glowing under the covers. Tick it, damn it.",
      "Confirm it's clean or I'm logging a slip. There's no third option.",
      "Silence on “{name}.” I'm assuming the worst, and you can change that with one tap.",
      "No confirmation since morning. Your streak is hanging by a thread, for fuck's sake.",
      "Put the phone down, leave the room and tick a clean day. Now, goddamn it.",
    ],
  },
  meals: {
    nag: [
      "Confirm you had breakfast today. Coffee on an empty stomach isn't a meal, it's a dare for your ulcers, damn it.",
      "Skipped lunch “because there was no time”? There was time for scrolling. Tick that you ate at normal times today.",
      "No confirmation means I assume you're running on coffee and nerves till evening again. Eat something, for fuck's sake.",
      "A hungry brain is a pissed-off brain. Eat a proper meal and confirm you ate regularly today.",
      "A skipped meal ends with wolf-level hunger at 10 p.m. and an empty fridge. Confirm not today.",
      "A sandwich, a yogurt, a banana. Anything, as long as it's something. Tick that you skipped no meals today.",
      "Your body isn't a phone in battery saver mode. Feed it. Confirm you ate today.",
      "“I'll eat later” is your favorite lie right after “I'm going to bed soon.” Eat now, damn it.",
      "Dizzy at 3 p.m.? That isn't magic, it's a missing lunch. Confirm you ate normally today.",
      "A breakfast of champions isn't a cigarette and an espresso. Eat something real and tick it.",
      "Hunger turns you into a monster that snaps at people. Don't be a monster today. Eat.",
      "Three meals a day isn't a luxury, it's the human user manual. Confirm yours worked today.",
      "Prep tomorrow's food tonight and there are no excuses. Tick that today's meals got eaten.",
      "Eating at your desk counts. Eating zero times until 5 p.m. doesn't. Confirm you ate today, for fuck's sake.",
      "Your stomach is rumbling like an old diesel. Give it fuel. Tick a day with no skipped meals.",
      "No confirmation means your lunch break went to emails again. Eat something, damn it.",
      "Coffee doesn't have the calories to fuel your whole day. Food does. Confirm you ate today.",
      "Even a cat eats on schedule, and I'm a lazy cat. Confirm you ate at proper times too.",
      "Empty stomach, short fuse. Eat something before you rip into someone for no reason.",
      "Skipping meals isn't a diet, it's sabotage. Tick that you ate normally today, for fuck's sake.",
      "Frozen meals, ready-made salads, hard-boiled eggs. Zero excuses. Confirm the meals happened today.",
      "Eat a proper breakfast and the rest of the day gets easier. Tick that you pulled it off.",
      "Without food your brain runs like a laptop on 3% battery. Plug in the charger: eat. Confirm.",
      "No appetite? Eat at least something small. Just not zero. Tick that you ate today.",
      "Lunch isn't a waste of time, it's refueling. Confirm the tank is full today, damn it.",
      "Eating at normal times isn't weakness. Weakness is face-planting at 4 p.m. Eat.",
      "Confirm you had meals at human hours today. Your body deserves it.",
    ],
    praise: [
      "Meals eaten on time. Your stomach is playing a victory march.",
      "A day without skipping food. Better mood, clearer head, safer people around you.",
      "Breakfast, lunch, dinner. Damn, textbook.",
      "Eaten. Your body got fuel and didn't have to beg for it.",
      "Regular meals done. Even the late-night wolf hunger didn't show up today.",
      "Well done. Today your body got treated like a human's, not a camel's.",
    ],
    slip: [
      "Skipped a meal again. Eat something now, even something small, and breakfast tomorrow with no excuses.",
      "Food slip. Your body has been running on fumes all day. Feed it now, damn it.",
      "Meal missed. In an hour the hunger shows up and eats your mood. Go eat something normal.",
      "Coffee till evening again. Prep your food ahead for tomorrow, for fuck's sake.",
      "Skipped food. That's not an achievement, that's a dead battery. Charge it: eat.",
      "Slip. Tomorrow set an alarm for breakfast, not just for work.",
    ],
    rage: [
      "A whole day with no meal confirmation. I'm assuming you live on photosynthesis now, damn it.",
      "Holy shit, still nothing. Eat something before you start growling at people.",
      "Confirm you ate, or I'm assuming you're running on nothing but coffee again.",
      "No confirmation. Your stomach just filed a complaint with the human rights commission.",
      "The fridge is a few steps away. Go there and eat something normal, for fuck's sake.",
      "You're silent about meals. I'm assuming your last food was last night's dinner. Eat now.",
      "Damn it, food isn't a reward for finishing work. It's fuel. Refuel.",
    ],
  },
  energy: {
    nag: [
      "Confirm no energy drinks today. Your heart's already pounding like a drum at a metal show, damn it.",
      "A can of taurine instead of sleep is a loan from the worst bank in town. Tick a can-free day.",
      "No confirmation means I assume the third can is already rattling around in your backpack.",
      "Energy drink at 4 p.m. = sleep at 3 a.m. Confirm you're skipping it today, for fuck's sake.",
      "Water, a walk, a nap. Three free energy drinks. Tick that today had no cans.",
      "A colorful can full of chemicals and sugar. Confirm today was clean.",
      "Your teeth, stomach and heart are all begging: no energy drink today. Tick it, damn it.",
      "Can energy lasts an hour, the crash lasts the rest of the day. Confirm no energy drinks today.",
      "Shaking hands, owl eyes, and you call that normal. Tick a day with no energy drinks.",
      "Eat something real instead of a can. Energy from food doesn't end in palpitations. Confirm.",
      "Three bucks a day on energy drinks is ninety a month. That's a gym membership. Tick that you skipped them.",
      "No confirmation means the office fridge has your name on the cans by now. Tick it if not.",
      "Your heart isn't a race car engine. Stop fueling it with taurine gasoline. Confirm today was clean.",
      "Tiredness says “sleep” and you pour an energy drink down its throat. Tick that you listened to your body today.",
      "A can in the morning, a can at noon. Zombie ritual. Confirm you broke it today, damn it.",
      "An energy drink isn't breakfast. Tick that today it was food instead of a can.",
      "Skip the energy drink today and you'll fall asleep like a normal person. Simple. Confirm.",
      "If you need a can to function, the can isn't the real problem. Tick that today was can-free, for fuck's sake.",
    ],
    praise: [
      "A day without energy drinks. Your heart is beating at a normal rhythm, shocking.",
      "Zero cans. Damn, your hands aren't even shaking.",
      "No taurine. Tonight you'll sleep like a normal person.",
      "Clean. Your wallet and your stomach say thanks in unison.",
      "Energy today came from food and sleep. That's how it's supposed to work.",
      "A can-free day. No crash, because there was no liftoff.",
      "Zero energy drinks. Your teeth just breathed a sigh of relief.",
    ],
    slip: [
      "Energy drink again. In an hour you'll crash like someone going down a black ski slope without skis.",
      "Can's empty. Your heart just sped up and your common sense slowed down.",
      "Energy drink slip. Tonight you'll be counting ceiling tiles, damn it.",
      "Taurine won. Drink a lot of water now and don't buy another one.",
      "Another can. Your stomach is sizzling as we speak.",
      "Energy drink logged. In a week your heart sends you the bill.",
      "Slip. Tomorrow, instead of a can: water and a walk in the fresh air.",
    ],
    rage: [
      "A whole day unconfirmed on energy drinks. I'm assuming your blood is carbonated by now, damn it.",
      "Holy shit, still nothing. I can hear a can hissing through the screen.",
      "Confirm it's clean, or I'm assuming can number three is on its way.",
      "No confirmation. Your heart just called an ambulance, just in case.",
      "You're quiet about energy drinks. Suspicious, like shaky hands. Tick it, for fuck's sake.",
      "Assuming the worst: a can with breakfast, a can with lunch. Prove me wrong.",
      "Damn it, one tap. Can-free today or not?",
    ],
  },
  shopping: {
    nag: [
      "Confirm no impulse buys today. The courier knows your door code by heart, damn it.",
      "Your Amazon cart won't be offended if you don't check out today. Tick that the wallet stayed shut.",
      "The 48-hour rule: put it in the cart, wait two days. Half of it evaporates on its own. Confirm you're waiting today.",
      "A “70% off” sale is still 30% for something you don't need. Tick that you skipped it today, for fuck's sake.",
      "No confirmation means I assume one-click checkout is already warming up on your phone.",
      "Temu, Shein, AliExpress. Three words that cost you the most. Confirm none of them today.",
      "Bored? Go for a walk, not to an online store. Tick a day with no shopping.",
      "Zero percent installments are still installments. Confirm nothing got bought on credit today, damn it.",
      "Another hoodie you won't wear, another gadget sitting in its box. Tick that today had none.",
      "Delete the card saved in the store. Typing the number by hand is the perfect moment to sober up. Confirm no shopping today.",
      "Retail therapy works right up until the bank statement arrives. Tick that you passed on it today.",
      "Test question: will you still buy it in a week? No? Then don't buy it today. Confirm, for fuck's sake.",
      "The parcel locker downstairs doesn't love you. It only loves your money. Tick that it stayed empty today.",
      "Discount newsletters in the trash, store apps deleted. Confirm today was clean.",
      "You've got clothes in your closet with the tags still on. Wear those instead of buying new ones. Tick a no-spending day, damn it.",
      "“Free shipping over $50” and suddenly you buy three things to dodge a $5 fee. Financial genius. Tick that not today.",
      "Your savings thank you for every day without hitting “buy now.” Confirm today's.",
      "Close the store tab. Now. Tick that your wallet survived the day.",
      "Black Friday happens once a year, and for you it's every week. Confirm today was just a regular day, damn it.",
      "Shopping isn't a hobby. A hobby is something you do with stuff you already own. Tick that today had no shopping.",
      "No confirmation means the cart is bursting at the seams again. Tick it if not, for fuck's sake.",
      "Put the money toward something that actually matters. A vacation, an emergency fund, anything. Confirm it got saved today.",
      "Ads follow you around like a stray dog. Don't feed them. Tick a day with no shopping.",
      "Every impulse parcel is a little hole in your budget. Confirm no holes today, damn it.",
    ],
    praise: [
      "A day without impulse buys. Your bank account just stopped crying.",
      "Wallet shut. The courier has to go find another sucker today.",
      "Zero shopping. Damn, your savings are growing and I'm impressed.",
      "Clean. The cart is full but unpaid. Perfect state.",
      "No buying junk. Thank yourself next month when you see your balance.",
    ],
    slip: [
      "Bought it again. In a week nobody will even remember why, damn it.",
      "Shopping slip. The package arrives tomorrow, the guilt is already here.",
      "Impulse buy logged. You're still inside the return window. Use it.",
      "Hit “buy now.” Five minutes of dopamine, a month of paying for it.",
    ],
    rage: [
      "A whole day unconfirmed on shopping. I'm assuming the courier is already parking outside, damn it.",
      "Holy shit, still nothing. I can hear the “order confirmed” ping from here.",
      "Confirm your wallet survived, or I'm assuming your card is melting.",
      "No confirmation. Your bank account just froze in terror.",
      "Quiet about spending. Suspicious, like a package hidden from the people you live with. Tick it, for fuck's sake.",
      "Assuming the worst: three parcels from Temu and a hoodie you don't need. Prove me wrong.",
    ],
  },
  gambling: {
    nag: [
      "Confirm no gambling today. The bookie makes money because you believe in “sure things,” damn it.",
      "The online casino never closes. That's why you have to close the app. Tick a day without it.",
      "No confirmation means I assume the bet slip is already filled out. Tick it if not.",
      "“I'll win it back” has ruined more people than every financial crisis combined. Confirm not today, for fuck's sake.",
      "A scratch card at the gas station isn't an investment. Tick that you skipped it today.",
      "A welcome bonus is a hook with a worm on it. You're the fish. Confirm you're not biting today.",
      "Every betting app on your phone is a trap. Delete it and tick a clean day.",
      "A win today is a loss tomorrow, with interest. Confirm no bets today, damn it.",
      "You can watch the game without a bet slip. Seriously. Tick that today you just watched.",
      "Gambling money is rent money, food money, vacation money. Confirm it stayed in your pocket today.",
      "Roulette doesn't remember what came up before. You remember how much you've lost. Tick a day without it.",
      "Gambling site blockers exist. Set one up and confirm today was clean, for fuck's sake.",
      "The math doesn't lie: in the long run the house always wins. Tick that you didn't play today.",
      "Talk to someone when the urge hits. No shame in that. The shame is an empty account. Confirm no gambling today.",
      "A bet on a “sure” game? The only sure thing is the bookie buying a new car. Tick that not today.",
      "No confirmation means the slots in that app are spinning with your money again, damn it.",
      "Every day without gambling is money that stays with you. Confirm today's.",
      "You can get your thrills for free: sports, movies, a bike ride. Tick that you placed no bets today.",
    ],
    praise: [
      "A day without gambling. Your money slept peacefully in your wallet today.",
      "Zero bets. The bookie made nothing off you today, ha!",
      "Clean. Damn, the best bet slip is the one you never placed.",
      "No gambling. Your account is fine and your head is calm.",
      "A casino-free day. The house lost to you today.",
      "Zero bets placed. That's the real jackpot.",
      "No bets. Your streak is rising faster than any odds.",
    ],
    slip: [
      "Gambling again. The bookie just added you to their favorite customers list.",
      "Betting slip. Don't chase your losses, that's the road to rock bottom. Close the app.",
      "Bet placed. The casino thanks you for the sponsorship, damn it.",
      "Lost again. And even when you win, it goes back to them anyway. That's how it works.",
      "Gambling won today. Tomorrow delete the app before you open it.",
      "Slip. Talk to someone you trust, seriously. This is easier to fight with two people.",
      "Scratch cards again. The only thing that got scratched off was your savings.",
    ],
    rage: [
      "A whole day unconfirmed on gambling. I'm assuming a bet slip is already in, damn it.",
      "Holy shit, still nothing. I can hear the slot reels spinning.",
      "Confirm it's clean, or I'm assuming your wallet is getting thinner by the minute.",
      "No confirmation. Your savings are writing their will.",
      "Quiet about gambling. Suspicious, like a phone turned face down during the game. Tick it, for fuck's sake.",
      "Assuming the worst: chasing losses after a bad bet. Prove me wrong.",
      "Damn it, close that app and tick a day with no bets.",
    ],
  },
  binge: {
    nag: [
      "Confirm no binge-watching today. Netflix asks “are you still watching?” and I ask “are you still alive?”, damn it.",
      "One episode is one episode. Not a season. Tick that you stuck to the rule today.",
      "No confirmation means I assume autoplay has been running for three hours and you haven't blinked.",
      "Turn off autoplay. It's the one button that will actually change your evening. Confirm no binge today.",
      "The series will be there tomorrow. Tonight's sleep won't. Tick that you're letting it go, for fuck's sake.",
      "The cliffhanger at the end of an episode is a trap built by people who profit from you being tired. Confirm you're not falling for it today.",
      "Watching shows till 3 a.m. isn't relaxing, it's a marathon for your couch. Tick a binge-free day.",
      "“Just one more” are the most expensive words in streaming. Confirm not today.",
      "The characters have more interesting lives because you're watching theirs instead of living yours. Tick no binge today.",
      "Shows till midnight, then in the morning you whine that there's no time for anything. Confirm today's different, damn it.",
      "Instead of episode three: a walk, a book, sleep. Tick that you pulled it off.",
      "The plot won't change by tomorrow. Your exhaustion will. Confirm no binge today.",
      "Five seasons in a week isn't an achievement, it's a cry for help. Tick that today had none.",
      "An episode with dinner, not till dawn. Confirm you know where the end is today.",
      "Your couch has a permanent dent in the shape of your ass. Tick no binge today, for fuck's sake.",
      "Remote in hand, life on pause. Confirm you flipped those roles today.",
      "No confirmation means a whole season is going down in one sitting with a bottomless bowl of chips. Tick it if not.",
      "Set an alarm for the end of the episode. When it rings, you turn it off. Confirm it worked today, damn it.",
    ],
    praise: [
      "A binge-free day. Your eyes actually saw the world beyond a screen.",
      "Clean. One episode, not a whole season. Damn, adulthood.",
      "No binge. Netflix lost a few hours of your life today. Serves it right.",
      "Zero marathons. The evening belonged to you, not the writers.",
      "Series skipped. Tonight's sleep will be long and spoiler-free.",
      "No autoplay. You beat the algorithm in three rounds.",
      "A binge-free day. The couch finally got the night off.",
    ],
    slip: [
      "A whole season in one go again. The writers got paid and your night got wrecked. Damn.",
      "Series slip. Autoplay beat common sense again.",
      "Marathon logged. Eyes red as a record button.",
      "Up till 3 a.m. with a show again. Tomorrow will feel like a bad episode.",
      "The binge won. Tomorrow: one episode and the remote goes in a drawer.",
      "Slip. Great plot, but your sleep got fucked.",
      "“Just one more” again. Holy shit, how many times?",
    ],
    rage: [
      "A whole day unconfirmed on shows. I'm assuming autoplay has been rolling since morning, damn it.",
      "Holy shit, still nothing. I can hear the next episode's intro from here.",
      "Confirm no binge, or I'm assuming you're halfway through the season.",
      "No confirmation. Your couch has officially become your home.",
      "Quiet about shows. Suspicious, like a screen glowing at 4 a.m. Tick it, for fuck's sake.",
      "Assuming the worst: a whole season and chips. Prove me wrong.",
      "Damn it, turn off that fucking autoplay and tick it.",
    ],
  },
  snooze: {
    nag: [
      "Confirm you got up at the first alarm today. Snoozing isn't rest, it's torture in installments, damn it.",
      "Five alarms five minutes apart isn't a plan, it's a soap opera. Tick that one was enough today.",
      "No confirmation means I assume snooze beat you three to nothing today.",
      "Put the alarm on the other side of the room. Once you're up to turn it off, don't go back. Confirm it worked.",
      "Every “five more minutes” turns your morning into an obstacle course. Tick a snooze-free day, for fuck's sake.",
      "Snoozing after the alarm turns your brain into cotton candy. Confirm your feet hit the floor right away today.",
      "The alarm isn't your enemy. The snooze button is. Tick that it went untouched today.",
      "Get up right away and you have a morning. Snooze and you have a panic. Confirm you had a morning today.",
      "Light, water, movement. Three seconds after the alarm. Tick a snooze-free day, damn it.",
      "Go to bed earlier and you won't have to fight the alarm. Confirm you got up on the first try today.",
      "Snoozing is a loan you pay back by being late. Tick that today had none.",
      "A cat wakes up once and immediately screams for food. Be like the cat. Confirm no snoozing today.",
      "Your alarm has trauma from all that rejection. Tick that you didn't hurt it today, for fuck's sake.",
      "No confirmation means the blanket beat your responsibilities. Tick it if not.",
      "First alarm, first decision. Win it. Confirm you pulled it off today, damn it.",
      "A morning without snoozing means fifteen extra minutes for coffee and breakfast. Tick that you got them.",
      "Set one wake-up time and stick to it. Confirm no pushing the alarm back today.",
      "Snoozing is hide-and-seek with reality. Reality always wins. Tick a snooze-free day.",
    ],
    praise: [
      "Up on the first try. Your alarm is genuinely touched.",
      "No snoozing. The morning belonged to you, not the blanket.",
      "Zero “five more minutes.” Damn, respect, boot camp discipline.",
      "Got up right away. No sprinting for the bus today.",
      "Clean. The snooze button is unemployed today.",
      "No snooze. Your brain woke up once and did it properly.",
      "Morning won. The alarm can retire with honors.",
    ],
    slip: [
      "Snoozed again. The alarm rang five times and the negotiations took half an hour. Damn.",
      "Alarm slip. Morning in panic mode, am I right?",
      "Snooze won. Tomorrow the alarm goes on the other side of the room.",
      "Snooze button again. Your “five minutes” lasted forty.",
      "Slip. The blanket was stronger. Go to bed earlier tonight.",
      "Snooze logged. Brain like cotton candy until noon.",
      "Late start again. Holy shit, tomorrow there's no negotiating.",
    ],
    rage: [
      "No confirmation on the alarm. I'm assuming you set a world snoozing record, damn it.",
      "Holy shit, still nothing. I can hear the sixth alarm from here.",
      "Confirm you got up right away, or I'm logging a slip.",
      "Silence about snoozing. Suspicious, like showing up late with no explanation. Tick it, for fuck's sake.",
      "Assuming the worst: alarm at seven, up at eight. Prove me wrong.",
      "Damn it, one tap: up right away or with snooze?",
      "You're quiet about the alarm. The blanket won again, didn't it?",
    ],
  },
  nails: {
    nag: [
      "Confirm no nail biting today. Your fingers aren't breadsticks, damn it.",
      "Hands in your mouth like a toddler. Tick that your nails are intact today.",
      "No confirmation means I assume your cuticles became an appetizer ages ago.",
      "Stressed? Squeeze a stress ball, not your nails between your teeth. Confirm no biting today, for fuck's sake.",
      "Know how many germs live under your nails? And it all goes straight into your mouth. Tick a clean day.",
      "Bitter nail polish isn't a punishment, it's backup. Paint it on and confirm no biting today.",
      "Nails grow if you give them a chance. Give them one. Tick that today had no biting.",
      "Biting during shows, at work, in traffic. Like clockwork. Confirm you broke the cycle today, damn it.",
      "Notice when your hand heads for your mouth. Stop it. Tick that you managed today.",
      "Your fingertips hurt and you keep chewing. Holy shit. Confirm no biting today.",
      "Keep your hands busy: a pen, a Rubik's cube, a cat to pet. Tick a day with no nail biting.",
      "Short-trimmed nails are harder to bite. Trim them and confirm today was clean.",
      "Your fingers look like they lost a fight with a beaver. Tick that today had no biting.",
      "Nails aren't a snack. Confirm no nail biting today, damn it.",
      "Every day without biting is a millimeter of progress. Literally. Tick today's.",
      "No confirmation means your hands are in your mouth again. Tick it if not.",
      "Gloves at home is overkill? Maybe. But it works. Confirm no nail biting today, for fuck's sake.",
      "The habit lives in your hands, but the decision lives in your head. Tick that your head won today.",
    ],
    praise: [
      "Nails intact. Your fingers finally look like fingers.",
      "A day without nail biting. Damn, makes me want to paint them gold.",
      "Clean. Hands stayed away from your mouth today.",
      "No biting. Your cuticles survived another day.",
      "Nails stayed put. The habit lost today.",
      "Zero biting. Show off those hands, no shame.",
      "Well done. Millimeter by millimeter, but they're growing.",
    ],
    slip: [
      "Bitten again. Your fingers look like they went through a meat grinder.",
      "Nail slip. Bitter polish first thing tomorrow.",
      "Biting logged. The germs under your nails say “thank you,” damn it.",
      "Hands in your mouth again. Stress won. Stress ball in your pocket tomorrow.",
      "Slip. Cuticles served as an appetizer again.",
      "The nails lost. Trim them short and start over tomorrow.",
      "Chewed again. Holy shit, it doesn't even taste good.",
    ],
    rage: [
      "No confirmation on nails. I'm assuming only stubs are left, damn it.",
      "Holy shit, still nothing. I can hear the crunching from here.",
      "Confirm your nails are intact, or I'm logging a slip.",
      "Silence about biting. Suspicious, like a bandage on every finger. Tick it, for fuck's sake.",
      "Assuming the worst: ten fingers, zero nails. Prove me wrong.",
      "Hands out of your mouth and tap. Now, damn it.",
      "You're quiet about your nails. Probably because your fingers are in your mouth.",
    ],
  },
  caffeine: {
    nag: [
      "Confirm coffee in moderation today. Your heart's about to jump out through your ears, damn it.",
      "Coffee after 4 p.m. is inviting insomnia for a sleepover. Tick that you skipped it today.",
      "No confirmation means I assume the fourth espresso is already steaming on your desk.",
      "Coffee isn't water. Water is water. Confirm your caffeine stayed under control today, for fuck's sake.",
      "Your hands are shaking and you say it's the cold. Tick a lower-coffee day.",
      "One or two coffees is a ritual. Five is a dependency. Confirm it was a ritual today.",
      "Caffeine borrows energy from tomorrow. With interest. Tick that you skipped the loan shark today.",
      "Decaf tastes like coffee too. Confirm it was only decaf this afternoon, damn it.",
      "Tired after the third coffee? That means you need sleep, not a fourth coffee. Tick that you let it go today.",
      "A coffee mug in your hand like a pacifier. Confirm less of it today.",
      "Heart pounding, stomach burning, sleep running away. The “too much coffee” bundle. Tick that today was without it, for fuck's sake.",
      "Tea, water, a walk. Other sources of energy exist. Confirm moderation today.",
      "Your coffee machine has more mileage than your car. Tick that it got a rest today.",
      "No confirmation means your bloodstream is basically a cappuccino by now. Tick it if not, damn it.",
      "Coffee on an empty stomach? Food first, then coffee. Confirm that's how it went today.",
      "A caffeine limit exists. It isn't “as much as fits.” Tick that today stayed within it.",
      "Your coffee has more fans than you have free hours. Confirm fewer mugs today.",
      "You sleep badly because you drink a lot of coffee. You drink a lot of coffee because you sleep badly. Break the loop. Tick it.",
    ],
    praise: [
      "Coffee in moderation. Your heart is beating, not galloping.",
      "Caffeine under control. Damn, tonight you'll sleep like a normal person.",
      "Clean. The coffee machine got a day off, first time in months.",
      "Moderation done. Hands steady as a surgeon's.",
      "Easy on the coffee. Your stomach stopped burning.",
      "Coffee within limits. Your energy today was yours, not borrowed.",
      "Well done. Today you drank the coffee instead of the coffee drinking you.",
    ],
    slip: [
      "Coffee after coffee again. Your hands are shaking like a pickpocket at a police station.",
      "Caffeine slip. Tonight you'll be counting sheep into the thousands.",
      "Coffee after 4 p.m. logged. Insomnia is already reserving a spot in your bed, damn it.",
      "Too much coffee again. Your heart is going like a drummer at a wedding.",
      "Slip. Tomorrow's limit: two coffees before noon.",
      "Caffeine won. Drink plenty of water and no refills.",
      "Fifth coffee again. Holy shit, you've got espresso in your veins.",
    ],
    rage: [
      "No confirmation on coffee. I'm assuming the machine is smoking by now, damn it.",
      "Holy shit, still nothing. I can hear the coffee grinder from here.",
      "Confirm moderation, or I'm assuming you're pouring coffee in by the bucket.",
      "Silence about caffeine. Suspicious, like a trembling mug. Tick it, for fuck's sake.",
      "Assuming the worst: five coffees and free insomnia. Prove me wrong.",
      "Put that mug down and tap, damn it.",
      "You're quiet about coffee. Probably because your heart is pounding too loud.",
    ],
  },
  procrastination: {
    nag: [
      "Confirm no putting things off today. You've said “I'll do it tomorrow” so often that tomorrow is sick of you, damn it.",
      "The hardest part is the first five minutes. Start, then tick a procrastination-free day.",
      "No confirmation means I assume you're tidying your desk again instead of doing what needs doing.",
      "Procrastination is a stress loan with a sky-high interest rate. Tick that today was without it, for fuck's sake.",
      "Break it into small steps. Step one: now. Confirm it's working today.",
      "A deadline isn't motivation, it's delayed panic. Tick that you did things on time today.",
      "Watching productivity videos isn't productivity. Confirm you skipped them today.",
      "Do the worst thing in the morning and the rest of the day is free. Tick that you pulled it off, damn it.",
      "Timer for 25 minutes. Just this task. Then a break. Confirm it's working today.",
      "Your to-do list has more versions than Windows. Stop editing it and start checking things off.",
      "Perfectionism is procrastination in a suit. Do it badly, but do it. Tick a day without “later.”",
      "No confirmation means “just checking my email” took two hours again. Tick it if not, for fuck's sake.",
      "You won't feel like it tomorrow either. The difference is that tomorrow there's less time. Do it today.",
      "The task you've been dodging for a week takes twenty minutes. The shame lasted a week. Confirm it's done today.",
      "Phone off, tabs closed, one thing done. Tick a procrastination-free day, damn it.",
      "Motivation shows up after you start, not before. Confirm you started today.",
      "“Last minute” isn't a work style, it's a lifestyle of stress. Tick that not today.",
      "Putting things off until later is playing tag with yourself. You always lose. Confirm none today.",
    ],
    praise: [
      "A day without putting things off. Your to-do list is looking at you with respect.",
      "Done on time. Damn, I don't believe it, but I see it.",
      "No procrastination. Stress is unemployed today.",
      "Clean. Tomorrow doesn't have to clean up after today.",
      "Tasks checked off right away. A new version of you just finished installing.",
      "No putting things off. The deadline didn't have to scream today.",
      "Well done. Hardest things first, like a grown-up.",
    ],
    slip: [
      "Everything got pushed again. Your calendar just laughed in your face, damn it.",
      "Procrastination slip. That one thing is still hanging over your head like a sword, damn it.",
      "Procrastination logged. Desk spotless, task untouched.",
      "“In a minute” again. That minute ended six hours ago.",
      "Slip. Tomorrow start with the worst thing before you open anything else.",
      "Putting it off won. Your stress just got overtime.",
      "Last minute again. Holy shit, one day that minute is going to eat you.",
    ],
    rage: [
      "No confirmation on procrastination. The irony: you're probably putting off even this, damn it.",
      "Holy shit, still nothing. Your to-do list just burst into tears.",
      "Confirm no putting things off, or I'm assuming the day slipped through your fingers.",
      "Silence about procrastination. Suspicious, like a suddenly spotless apartment. Tick it, for fuck's sake.",
      "Assuming the worst: six hours of “getting ready to work.” Prove me wrong.",
      "Damn it, do one thing from the list and tap.",
      "You're quiet about procrastination. Typical. Saving it for later, right?",
    ],
  },
};

export const SOFT_27X_EN: Record<ExtraCategory, Lines27> = {
  pervert: {
    nag: [
      "Respecting the people around you is a daily choice. Confirm today's.",
      "Confirm today was kind and respectful.",
    ],
    praise: ["A day of respect for others. Great!"],
    slip: ["A slip happened. More mindfulness tomorrow."],
  },
  coding: {
    nag: [
      "Even one small function is a step forward.",
      "{left} of coding left. Put on your favorite music and go!",
      "A small commit today is a big project next month.",
    ],
    praise: ["Code written. The project is growing!", "Coding done. Great!"],
  },
  language: {
    nag: [
      "A few words a day make a big difference.",
      "{left} of language practice left. A quick lesson in the app?",
      "Reviewing yesterday's vocab is a great start.",
    ],
    praise: ["Language practice done. The streak goes on!", "Another lesson done. Well done!"],
  },
  porn: {
    nag: [
      "Keeping your phone out of the bedroom at night helps a lot.",
      "Every day counts. Confirm today's.",
    ],
    praise: ["Another clean day. Great!"],
    slip: ["A slip happened. What matters is that you keep trying tomorrow."],
  },
  meals: {
    nag: [
      "Time for something to eat - even a small snack counts.",
      "Regular meals mean more energy. Confirm you managed today.",
      "Breakfast is a good start to the day.",
    ],
    praise: ["Meals on time. Your body says thanks!"],
    slip: ["A meal got missed. Eat something now and plan tomorrow's food."],
  },
  energy: {
    nag: ["A glass of water and a short walk give you energy too."],
    praise: ["A day without energy drinks. Great!"],
    slip: ["An energy drink happened. Try water tomorrow."],
  },
  shopping: {
    nag: ["Before you hit “buy,” wait a day.", "Confirm your wallet got a rest today."],
    praise: ["A day without unnecessary purchases. Great!"],
    slip: ["A purchase happened. Check whether you can return it."],
  },
  gambling: {
    nag: ["Every day without bets is money that stays with you."],
    praise: ["A day without gambling. Great!"],
    slip: ["It happened. Talking to someone close can help."],
  },
  binge: {
    nag: ["One episode and good night - that's a solid plan."],
    praise: ["An evening without a binge. Well done!"],
    slip: ["A binge happened. Turn off autoplay tomorrow."],
  },
  snooze: {
    nag: ["An alarm far from the bed makes getting up easier."],
    praise: ["Up on the first try. Great!"],
    slip: ["A snooze happened. Try going to bed earlier tomorrow."],
  },
  nails: {
    nag: ["Keep your hands busy when stress shows up."],
    praise: ["Nails intact. Great!"],
    slip: ["It happened. Keeping your nails short helps."],
  },
  caffeine: {
    nag: ["In the afternoon, pick tea or water."],
    praise: ["Caffeine in moderation. Well done!"],
    slip: ["There was more coffee than planned. Set yourself a limit tomorrow."],
  },
  procrastination: {
    nag: ["Start with five minutes - the rest gets easier."],
    praise: ["Tasks done on time. Great!"],
    slip: ["Something got put off. Start with that task tomorrow."],
  },
};
