// Szpila 2.7 line bank (Polish): more jabs, praise, rage and slips for the
// base categories, plus extra all-done / evening / caught / motivating lines.
// Merged on top of szpila.ts + szpila-more.ts in linesFor() / rageLines().
// Same rules as the other banks: no gendered past tense or adjectives about the
// user (present tense, imperatives, impersonal forms), swearing aimed at the
// behaviour, never at who someone is. Placeholders: {name}, {u}; {done}/{left}/
// {target} only in nag/rage lines of build habits (usable() drops them for
// single-check habits). Praise and slip lines never carry amounts.
// English mirror: szpila-en-27.ts (same keys, same number of lines per array).
import type { Category } from "./szpila";
import type { TauntLevel } from "./store";

export interface Lines27 {
  nag?: string[];
  praise?: string[];
  slip?: string[];
  rage?: string[];
}

export const HARD_27: Partial<Record<Category, Lines27>> = {
  teeth: {
    nag: [
      "Poranne szorowanie olane? Z takim oddechem nawet kawa ucieka z kubka, kurwa.",
      "Wieczorne mycie zębów to nie jest dodatek premium. Szczoteczka, pasta, dwie minuty, do chuja.",
      "Twoje zęby mają dziś więcej osadu niż czajnik u babci. Do łazienki.",
      "Między zębami masz pół wczorajszego obiadu. Szoruj, zanim wykiełkuje.",
      "Pasta do zębów nie działa przez zamknięte opakowanie. Otwórz, wyciśnij, szoruj, kurwa.",
      "Mówisz komuś „dzień dobry”, a on mdleje. Przypadek? Nie. Zęby.",
      "Szczoteczka elektryczna, a ładowana tylko z poczucia winy. Użyj jej wreszcie.",
      "Bakterie w twojej gębie właśnie urządzają imprezę i nikt ich nie wyprasza. Szczotka do boju.",
      "Ząb za ząb, a tu żaden nieumyty. Ja pierdolę.",
      "Dentysta liczy na ciebie bardziej niż na emeryturę. Nie dawaj mu tej przyjemności.",
      "Rano szczotka, wieczorem szczotka. Dwa razy dziennie, nie dwa razy w tygodniu, geniuszu.",
      "Nitka dentystyczna leży w szufladzie i płacze z samotności. Kurwa, przynajmniej szczoteczka.",
      "Gęba jak śmietnik po festynie. Umyj to w końcu.",
      "Jeszcze {left} szorowania na dziś. Dwie minuty, nie dwie godziny, do chuja.",
      "Mycie zębów: {done} z {target}. Próchnica bije brawo.",
      "Z takim kamieniem nazębnym można by stawiać fundamenty. Szczoteczka, ale już.",
      "Wyobraź sobie, że ktoś cię całuje. Teraz wyobraź sobie jego minę. Zęby, kurwa.",
    ],
    praise: [
      "Zęby wyszorowane. Mucha przelatująca obok już nie spada martwa.",
      "Czyściutko. Możesz się uśmiechać bez ostrzeżenia sanitarnego.",
      "Umyte. Próchnica pakuje walizki i przeprowadza się do sąsiada.",
      "Szorowanie zaliczone. Twoja gęba znowu nadaje się do ludzi, kurwa, szok.",
    ],
    rage: [
      "Kurwa, ZĘBY. Szczoteczka kosztuje dziesięć złotych, a leczenie kanałowe tysiąc. Licz.",
      "Jeszcze jeden dzień takiego olewania i zęby same wyjdą z ust w proteście, do chuja.",
      "Twój oddech właśnie zabił kwiatek na parapecie. Łazienka. Natychmiast.",
      "Ile można? Dwie minuty szorowania i święty spokój. Rusz się, kurwa mać.",
      "Mycie zębów: {done} z {target} o tej porze. Ja pierdolę, próchnica już wiesza firanki.",
    ],
  },
  water: {
    nag: [
      "Wypite {done} z {target}. Skóra jak papier ścierny, mózg jak suszona śliwka. Pij, kurwa.",
      "Jeszcze {left}. Kubek, kran, łyk. To nie jest skomplikowana operacja, do chuja.",
      "Pierwsza szklanka wody jeszcze nawet nie widziała twojej gęby? No to pij.",
      "Ból głowy po południu to nie magnetyczne burze, tylko brak wody, geniuszu.",
      "Butelka wody stoi pełna jak twoje obietnice. Opróżnij ją wreszcie.",
      "Zostało {left}. Nawet kot pije więcej, a ja wodę uważam za wroga.",
      "Kawa się nie liczy. Herbata z czterema łyżkami cukru też nie. Woda, kurwa.",
      "Mocz w kolorze piwa bez piwa w organizmie? Gratuluję odwodnienia. Pij.",
      "Wypite {done} z {target}. Wielbłąd pyta, czy wszystko w porządku.",
      "Twoje nerki właśnie pracują w trybie oszczędzania. Daj im wody, do cholery.",
      "Szklanka wody to trzydzieści sekund. Scrollowanie trwa trzy godziny. Ogarniasz proporcje?",
      "Zmęczenie, marudzenie, ból łba. Pakiet „nie piję wody” w pełnej krasie. Pij.",
      "Jeszcze {left} do celu. Nie każ mi przychodzić z konewką, kurwa.",
      "Kaktus na parapecie wypił dziś więcej. A on mieszka na pustyni z wyboru.",
      "Woda jest za darmo z kranu, a ty i tak oszczędzasz. Na czym? Na życiu?",
      "Sucho w tobie jak w starym zeszycie z piwnicy. Szklanka wody, już, kurwa mać.",
      "Każda szklanka to plusik w apce i minus jeden ból głowy. Prosty deal, pij.",
    ],
    praise: [
      "Woda wypita. Twoje nerki właśnie zamówiły ci tort. Bez cukru.",
      "Nawodnienie zrobione. Skóra przestaje szeleścić, kurwa, gratulacje.",
      "Komplet wody. Teraz pędź do kibla z godnością.",
      "Wypite. Mózg znowu pływa, a nie leży na mieliźnie.",
      "Pełne nawodnienie. Nawet roślinki zaczynają cię szanować.",
    ],
    rage: [
      "Wypite {done} z {target}? Kurwa, nawet stary ogórek kiszony jest bardziej nawodniony.",
      "Jeszcze {left}, a dzień ucieka. Pij tę pierdoloną wodę, zanim zmienisz się w rodzynek.",
      "Kran działa, szklanka czeka, a ty nic. Ja pierdolę, to jest woda, nie egzamin.",
      "Wyschniesz na wiór i wiatr cię zwieje na Mazury. Pij, do jasnej cholery.",
      "Tyle godzin i dalej sucho? Moja cierpliwość wyparowała szybciej niż woda z twojego ciała.",
    ],
  },
  steps: {
    nag: [
      "{done} kroków. Opaska na ręce myśli, że ktoś ją zdjął i zostawił na półce. Rusz dupę.",
      "Jeszcze {left}. Spacer do sklepu, wokół bloku, do parku. Gdziekolwiek, byle nie na kanapę.",
      "Twoja opaska wibruje, żeby się ruszyć, a ty ją głaszczesz jak kota. Wstawaj, kurwa.",
      "Brakuje {left}. Telefon do ręki, słuchawki na uszy i wypierdalaj na spacer.",
      "Kroki się same nie nabiją. Machanie nogą pod biurkiem się nie liczy, geniuszu.",
      "Ziemia się kręci, a ty nie. Wyjdź z domu, kurwa.",
      "{done} z {target} kroków. Żółw na spacerze właśnie cię zdublował.",
      "Krokomierz zgłasza zaginięcie właściciela. Odnajdź się na chodniku.",
      "Jeszcze {left}. Dwadzieścia minut marszu i święty spokój. Ja nawet nie mam butów, a chodzę więcej.",
      "Siedzenie to nowe palenie, a ty jesteś na trzech paczkach dziennie. Wstań.",
      "Schody zamiast windy. Sklep pieszo. Telefon przez spacer. Wymówki skończone, kurwa.",
      "Twoje łydki zapomniały, do czego służą. Przypomnij im to dzisiaj.",
      "Brakuje {left}. Nawet pies sąsiada ma lepszy wynik, a on chodzi tylko do drzewa.",
      "Spacer to darmowa terapia. Ty wolisz płatną depresję na kanapie? Rusz się.",
      "{done} kroków o tej porze? Ja pierdolę, z łóżka do kibla i z powrotem.",
      "Pada? Kup parasol. Zimno? Załóż kurtkę. Kroki, kurwa, same się nie zrobią.",
      "Opaska widzi wszystko. I opaska jest dziś bardzo rozczarowana.",
    ],
    praise: [
      "Kroki zrobione. Opaska wibruje z dumy, a kanapa pisze ci list z żalem.",
      "Cel zaliczony. Twoje nogi dziś pracowały, a nie tylko podpierały brzuch.",
      "Wychodzone. Chodnik pod blokiem zna już twoje imię.",
      "Komplet kroków. Kurwa, nawet ja chcę teraz iść na spacer. Żartuję, idę spać.",
      "Zaliczone. Łydki biją brawo, kolana podpisują pokój.",
    ],
    rage: [
      "{done} kroków o tej godzinie? Kurwa mać, doniczka z fikusem ma lepszą kondycję.",
      "Brakuje {left}, a ty dalej leżysz jak foka na plaży. Wstawaj, do chuja, natychmiast.",
      "Twoja opaska zaraz zadzwoni na pogotowie, bo myśli, że nie żyjesz. Rusz się.",
      "Jeszcze {left}. Nie obchodzi mnie pogoda, nastrój ani serial. Buty i na dwór, kurwa.",
      "Cały dzień przesiedziany. Kręgosłup już wysyła reklamację. Idź się przejść, ja pierdolę.",
    ],
  },
  reading: {
    nag: [
      "Książka przy łóżku służy ci za podstawkę pod telefon. Odwróć proporcje, kurwa.",
      "Jeszcze {left} czytania. Tyle trwają trzy rolki o niczym. Wybór jest prosty.",
      "Zakładka nie ruszyła się od tygodnia. Ona też ma swoją godność.",
      "Dwadzieścia minut z książką i mózg dostaje witaminy. Ty karmisz go memami, do chuja.",
      "Ostatni przerobiony rozdział to regulamin cookies. Czytaj, kurwa.",
      "Bohaterowie książki czekają od tygodnia w połowie zdania. Nie rób im tego, kurwa.",
      "Litery w książce się nie ruszają i nie mają dźwięku. To nie wada, to zaleta, geniuszu.",
      "Czytanie: {done} z {target} min. Twój mózg pyta, czy to żart.",
      "Kup jeszcze jedną książkę, to będzie ich więcej nieprzeczytanych. Albo przeczytaj jedną, kurwa.",
      "Przed snem książka zamiast telefonu. Zaśniesz szybciej, a mądrzejesz przy okazji.",
      "Mózg to nie śmietnik na shortsy. Wrzuć tam coś z okładką.",
      "Otwórz tę książkę choćby na pięć stron. Potem samo pójdzie, obiecuję. Kurwa, no.",
      "Twoja półka z książkami wygląda jak wystawa w muzeum. Wszystko za szybą, nic nie tknięte.",
      "Jeszcze {left}. Nawet audiobook by się liczył, ale ty i tego nie odpalasz.",
      "Ludzie piszą książki latami, a ty nie możesz przeczytać dwudziestu minut. Wstyd, do chuja.",
      "Najdłuższa rzecz przeczytana dziś to lista składników na chipsach. Gratulacje, intelektualisto.",
      "Książka nie wyśle ci powiadomienia. Dlatego ja wysyłam: CZYTAJ, kurwa.",
      "Rozdział dziennie i do końca roku masz kilkanaście książek. A ty masz zero. Licz.",
      "Kurz na okładce ma już własne dzieci. Otwórz to.",
    ],
    praise: [
      "Przeczytane. Twój mózg właśnie dostał coś pożywniejszego niż memy.",
      "Czytanie zaliczone. Zaczynasz wyglądać na kogoś, kto zna słowo „niemniej”.",
      "Strony przewrócone. Zakładka wreszcie zmieniła adres.",
      "Rozdział zrobiony. Kurwa, aż mnie korci, żeby zapytać o fabułę.",
      "Czytanie odhaczone. Jeszcze trochę i będziesz cytować coś innego niż TikToka.",
    ],
    rage: [
      "Cały dzień bez książki. Kurwa, twój mózg właśnie wystawił się na OLX jako nieużywany.",
      "Jeszcze {left} czytania, a ty dalej w telefonie. Ja pierdolę, odłóż to i otwórz książkę.",
      "Książka leży i patrzy. Ja patrzę. Wszyscy patrzymy. CZYTAJ, do chuja.",
      "Dwadzieścia minut. Tyle zajmuje kłótnia w komentarzach. Daj je książce, kurwa mać.",
      "Jak nie dziś, to kiedy? Na emeryturze? Wtedy też będziesz scrollować. Czytaj teraz.",
    ],
  },
  gym: {
    nag: [
      "Trening czeka, a twoja kondycja leży i pachnie. Rusz się, kurwa.",
      "Nawet dziesięć przysiadów to więcej niż zero. A zero to twój dzisiejszy wynik.",
      "Buty sportowe w szafie mają jeszcze metki. Ja pierdolę.",
      "„{name}” olane, a wieczorem płacz, że plecy bolą. Ruch, do chuja.",
      "Nie musisz biegać maratonu. Wystarczy, że przestaniesz biegać od treningu.",
      "Mata do ćwiczeń zrobiła się wycieraczką dla kota. Mi to pasuje, ale tobie nie powinno.",
      "Pompki, przysiady, deska. Dziesięć minut, a nie pielgrzymka. Jazda, kurwa.",
      "Twoje mięśnie są w trybie hibernacji. Obudź je, zanim zanikną.",
      "Spocony ryj albo spocone sumienie. Wybieraj.",
      "Trening to jedyne miejsce, gdzie ból oznacza, że coś idzie dobrze. Kanapa boli tylko psychicznie.",
      "Twoje ciało to nie mebel. Rusz nim, zanim osiądzie na nim kurz, kurwa.",
      "Plecy bolą od siedzenia, nie od ćwiczeń. Wstań i zrób „{name}”, do chuja.",
    ],
    praise: [
      "Trening zrobiony. Pachniesz jak szatnia, ale z dumą.",
      "Przepocone. Mięśnie wysyłają kartkę z podziękowaniami.",
      "Zaliczone. Nie będę mówić, że jestem pod wrażeniem, ale trochę jestem, kurwa.",
      "Trening odhaczony. Kanapa dziś przegrała.",
    ],
    rage: [
      "Cały dzień bez ruchu. Kurwa, nawet drzewo bardziej się kołysze.",
      "„{name}” wciąż czeka. Dziesięć minut, do chuja, tyle trwa reklama na YouTube.",
      "Ja pierdolę, zrób chociaż przysiady przy umywalce. Cokolwiek. Teraz.",
      "Twoja kondycja leży na OIOM-ie. Reanimuj ją treningiem, kurwa mać.",
      "Wymówki zrobione na sto procent, trening na zero. Odwróć te liczby.",
    ],
  },
  meditation: {
    nag: [
      "W głowie wyścig szczurów, a ty nawet minuty na oddech. Usiądź, kurwa.",
      "Pięć minut ciszy. Bez telefonu. Bez podcastu. Dasz radę czy pęknie ci mózg?",
      "Medytacja to nie siedzenie i myślenie o mailach. Oddychaj, do chuja.",
      "Twoje nerwy są napięte jak gumka w starych majtkach. Zrób „{name}”.",
      "Wdech na cztery, wydech na sześć. Tyle. Nawet ja to umiem, a jestem kotem.",
      "Spokój ducha nie przyjdzie, jak będziesz go scrollować. Siadaj.",
      "Zamknij oczy na pięć minut. Nie, nie po to, żeby zasnąć, cwaniaku.",
      "Cały dzień w biegu, a „{name}” w kącie. Zatrzymaj się, kurwa, zanim się wyłożysz.",
      "Kortyzol ci już uszami wychodzi. Oddech. Teraz.",
      "Mnisi medytują godzinami. Ty nie możesz pięciu minut? Ja pierdolę.",
      "Siedzisz i się wkurwiasz? To siedź i oddychaj. Ta sama pozycja, lepszy efekt.",
      "Aplikacja do medytacji też się kurzy. Odpal ją albo usiądź po prostu w ciszy.",
      "Głowa jak przeglądarka z czterdziestoma kartami. Zamknij kilka, zrób „{name}”.",
    ],
    praise: [
      "Zmedytowane. Twoja aura przestała śmierdzieć stresem.",
      "Pięć minut ciszy zaliczone. Świat się nie zawalił, kurwa, szok.",
      "Oddychanie zrobione. Nerwy rozluźnione o całe dwa procent.",
      "Medytacja odhaczona. Dziś mniej rzucania kurwami. Może.",
      "Spokój zaliczony. Nawet ja mruczę ciszej.",
      "Zrobione. Głowa przez chwilę była czysta jak kuweta po sprzątaniu.",
    ],
    rage: [
      "Cały dzień bez minuty spokoju. Kurwa, nic dziwnego, że chodzisz jak tykająca bomba.",
      "Pięć minut. PIĘĆ. Siadaj i oddychaj, do chuja, zanim coś rozpierdolisz.",
      "„{name}” dalej czeka. Spokój ducha właśnie złożył wniosek o rozwód.",
      "Ja pierdolę, nawet oddychać trzeba ci przypominać? Siadaj i oddychaj.",
      "Stres zżera ci łeb, a ty go dokarmiasz ekranem. Wyłącz i medytuj, kurwa.",
      "Medytacja olana, nerwy na wierzchu. Zgadnij, kto dziś na kogoś nawrzeszczy.",
      "Zamknij oczy i oddychaj. To nie prośba, to polecenie od kota, kurwa mać.",
    ],
  },
  sleep: {
    nag: [
      "Organizm prosi o sen, a ty mu puszczasz kolejny odcinek. Do łóżka, kurwa.",
      "Każda godzina snu przed północą jest warta dwóch. Ty masz ich na minusie.",
      "Jutro budzik o siódmej, a ty dalej się pierdolisz po pokoju. Spać.",
      "Kawa rano nie naprawi tego, co zepsujesz w nocy. Idź spać.",
      "Twoje worki pod oczami mają już własny kod pocztowy. Sen, do chuja.",
      "Mózg w nocy sprząta śmieci. Ty mu nie dajesz zacząć zmiany.",
      "„{name}” czeka. Łóżko jest metr od ciebie. Ogarniasz dystans?",
      "Zombie to nie jest styl życia. Połóż się wreszcie, kurwa.",
      "Jeszcze jedna rzecz, jeszcze jedna rzecz… i nagle druga w nocy. Znam cię. Spać.",
      "Sen to legalny doping. Wszyscy go biorą, tylko ty odmawiasz.",
      "Wyłącz światło, odłóż telefon, zamknij oczy. Trzy kroki, a ty nie możesz pierwszego.",
      "Jutro będziesz funkcjonować jak Windows Vista. Śpij teraz, kurwa.",
      "Niewyspanie robi z ludzi chamów. Nie chcę mieć z tobą jutro do czynienia. Do łóżka.",
      "Poduszka czeka, kołdra czeka, kot czeka. Wszyscy czekamy na ciebie.",
      "Melatonina sama się nie wydzieli przy świecącym ekranie, geniuszu.",
    ],
    praise: [
      "Wyspane. Dziś nawet twarz wygląda jak twarz, a nie jak pognieciona kartka.",
      "Sen zaliczony. Mózg posprzątany, humor odblokowany.",
      "Wyspanie zrobione. Kawa dziś tylko dla smaku, nie z rozpaczy.",
      "Noc przespana. Nawet ja jestem dumny, a ja śpię szesnaście godzin.",
      "Sen odhaczony. Worki pod oczami pojechały na urlop.",
      "Wyspane, kurwa. Dzień zapowiada się mniej chujowo.",
    ],
    rage: [
      "Kurwa, idź już spać. Jutro będzie dramat i to ja będę musiał na to patrzeć.",
      "Środek nocy, a ty dalej na nogach. Ja pierdolę, nawet sowy mają grafik.",
      "Łóżko. Teraz. Bez „jeszcze jednej rzeczy”, do chuja.",
      "Każda minuta teraz to godzina zmęczenia jutro. Licz i kładź się, kurwa.",
      "Jutro budzik zadzwoni, a ty będziesz wyglądać jak po dwóch weselach. Spać!",
      "Dosyć tego nocnego łażenia. Do łóżka, kurwa mać, natychmiast.",
      "„{name}” olane. Twój mózg za to zapłaci jutro z odsetkami.",
    ],
  },
  pills: {
    nag: [
      "Tabletka czeka w pudełku jak pies pod drzwiami. Łyknij ją, kurwa.",
      "Witaminy nie wchłaniają się przez patrzenie na opakowanie, geniuszu.",
      "„{name}” olane. Później się dziwisz, że cię łamie jak starego wiatraka.",
      "Szklanka wody i tabletka. Dwie sekundy roboty. Nawet ty to ogarniesz.",
      "Kalendarzyk z tabletkami wygląda jak los na loterii. Same niespodzianki.",
      "Pigułka nie połknie się sama. Nie czekaj, aż się zmęczy i odejdzie.",
      "Kup sobie pojemnik z dniami tygodnia, bo twoja pamięć to sito. A teraz łykaj.",
      "„{name}” dalej w szufladzie. Szuflada nie ma żołądka, ty masz. Łyk, kurwa.",
      "Zdrowie z apteki działa tylko, jak je bierzesz. Zaskakujące, prawda?",
      "Tabletka mała, wymówka duża. Odwróć to.",
      "Jutro znowu zapomnisz, jeśli nie zrobisz tego teraz. Łykaj, do chuja.",
      "Organizm czeka na dostawę. Kurier, czyli ty, stoi w korku lenistwa.",
      "Popij wodą, a nie kawą, i odhacz. Proste jak drut, kurwa.",
      "„{name}” to jedyna rzecz dziś, której nie trzeba nawet żuć. A i tak leży.",
      "Pudełko z tabletkami pokrywa się kurzem. Ty zaraz też, jak tak dalej pójdzie.",
    ],
    praise: [
      "Łyknięte. Organizm dostał paczkę i nawet nie musiał podpisywać.",
      "Tabletka zaliczona. Prosta rzecz, ale kurwa, zrobiona.",
      "Połknięte. Twoje komórki właśnie przybiły sobie piątkę.",
      "Zażyte. Pamięć dziś działa lepiej niż zwykle, szok.",
      "„{name}” zrobione. Apteka może być spokojna.",
      "Wzięte. Nawet ja nie mam się do czego przyjebać. Na razie.",
    ],
    rage: [
      "Tabletka dalej w opakowaniu. Kurwa, to nie jest eksponat muzealny.",
      "Cały dzień bez „{name}”. Ja pierdolę, połknąć to dwie sekundy.",
      "Opakowanie samo się nie otworzy, a ja nie mam kciuków. Łykaj, do chuja.",
      "Jak nie teraz, to zapomnisz do jutra. I znowu będzie dziura. Łyk, kurwa mać.",
      "„{name}” wciąż leży. Twój organizm właśnie dzwoni na reklamację.",
      "Woda, tabletka, połknąć. Trzy ruchy. Rusz chociaż jeden, kurwa.",
      "Ja się nie zamknę, dopóki „{name}” nie wyląduje w żołądku. Wybieraj.",
    ],
  },
  learning: {
    nag: [
      "Wiedza sama nie wskoczy ci do głowy, nawet jak położysz notatki pod poduszkę.",
      "„{name}” czeka. Każdy dzień bez nauki to dzień, w którym inni cię wyprzedzają, kurwa.",
      "Kurs kupiony, lekcja nieotwarta. Klasyka polskiego samorozwoju.",
      "Piętnaście minut nauki dziennie. Nie godzina, nie dwie. Piętnaście, do chuja.",
      "Mózg rośnie od używania. Twój dziś siedzi w poczekalni.",
      "Notatki leżą, długopis wysycha, a ty oglądasz, jak ktoś się uczy na YouTube.",
      "Jeszcze {left} nauki. Potem możesz udawać mądrzejszego przez cały wieczór.",
      "Nie musisz być geniuszem. Musisz usiąść i zacząć, kurwa.",
      "Zaległości rosną jak pranie w łazience. Zacznij od jednej rzeczy.",
      "Uczenie się jest trudne. Niewiedza jest jeszcze trudniejsza, tylko później.",
      "Fiszki, notatki, ćwiczenia. Cokolwiek, byle nie kolejna wymówka.",
      "„{name}” dzisiaj, sukces kiedyś. „{name}” jutro, wstyd dzisiaj.",
      "Twój mózg ma więcej wolnego miejsca niż pendrive za pięć złotych. Wgraj coś.",
      "Pomidor w kuchni, timer na 25 minut, nauka. Technika jest, chęci brak, kurwa.",
    ],
    praise: [
      "Nauka zaliczona. Neurony właśnie dostały premię.",
      "Zrobione. Jesteś dziś odrobinę mądrzejszym człowiekiem, kurwa, gratulacje.",
      "Lekcja odhaczona. Głowa pełniejsza niż lodówka po wypłacie.",
      "„{name}” zrobione. Jutro będziesz wiedzieć coś, czego wczoraj nie.",
      "Wiedza wgrana. Restart mózgu niepotrzebny.",
      "Nauka zaliczona. Nawet sowa z Duolingo kiwa głową z uznaniem.",
    ],
    rage: [
      "Cały dzień bez nauki. Kurwa, twój mózg właśnie przeszedł w tryb wygaszacza ekranu.",
      "„{name}” olane od rana. Ja pierdolę, piętnaście minut, nie semestr.",
      "Jeszcze {left} nauki, a ty dalej udajesz, że jutro ogarniesz podwójnie. Nie ogarniesz.",
      "Usiądź do „{name}”. Teraz. Zanim ta wiedza wyparuje razem z twoją ambicją, kurwa.",
      "Notatki leżą, a ty leżysz obok. Jedno z was musi się ruszyć. Ty, do chuja.",
      "Głupota nie boli dzisiaj. Boli jutro, na egzaminie, w pracy, w rozmowie. Ucz się.",
      "Dość odkładania. Otwieraj materiały i ucz się, kurwa mać.",
    ],
  },
  generic: {
    nag: [
      "„{name}” czeka jak pies na spacer. Weź się za to, kurwa.",
      "Lista się sama nie odhaczy. „{name}”, teraz.",
      "Zamiast myśleć o „{name}”, po prostu to zrób. Myślenie nic nie odhacza.",
      "Ile razy będę ci przypominać o „{name}”? Do skutku, do chuja.",
      "„{name}” to nie jest projekt na emeryturę. Dziś.",
      "Mówisz „zaraz”, a zaraz to już było trzy godziny temu. „{name}”.",
      "Wstajesz, robisz „{name}”, siadasz z czystym sumieniem. Proste, kurwa.",
      "Czekasz na natchnienie? Natchnienie przychodzi do ludzi, którzy już zaczęli.",
    ],
    praise: [
      "„{name}” zrobione. Kot kiwa głową z niechęcią, ale kiwa.",
      "Odhaczone. Wyjątkowo nie mam się do czego przypierdolić.",
      "„{name}” zaliczone. Zapisuję to sobie jako cud dnia.",
      "Zrobione, kurwa. Nawet nie bolało, co?",
    ],
    rage: [
      "„{name}” dalej leży. Kurwa, zaraz zacznę miauczeć o trzeciej nad ranem, jak nie zrobisz.",
      "Moja cierpliwość do „{name}” ma już tylko jedną kreskę baterii. Ruszaj, do chuja.",
      "Ja pierdolę, „{name}”. Ile można odkładać jedną prostą rzecz?",
      "Jeszcze godzina i „{name}” założy u ciebie konto na Tinderze, bo szuka kogoś, kto się nim zajmie.",
    ],
  },
  phone: {
    nag: [
      "Telefon pod poduszką to nie budzik, to dealer dopaminy. Wyrzuć go na drugi koniec pokoju.",
      "Potwierdź, że dziś łóżko jest do spania, a nie do oglądania cudzych wakacji o pierwszej w nocy.",
      "Niebieskie światło w ryj o północy i potem dziwne, że nie możesz zasnąć. Zaznacz, że nie dziś.",
      "Ładowarka przy łóżku to pułapka. Przenieś ją do kuchni i potwierdź, że dziś czysto, kurwa.",
      "Kciuk w łóżku ma odpoczywać, a nie robić maraton przewijania. Zaznacz, że dziś bez tego.",
      "Bez potwierdzenia zakładam, że znowu leżysz w ciemności i świecisz sobie ekranem po ryju jak latarką.",
      "„Tylko sprawdzę pogodę” w łóżku kończy się o trzeciej na filmikach z wypadków. Znam cię.",
      "Budzik nastaw, telefon odłóż ekranem w dół. Potwierdź, że dziś tak będzie, do chuja.",
      "Scrollowanie w łóżku zjada ci sen jak kornik drewno. Potwierdź, że dziś bez tego.",
      "Twoja poduszka zasługuje na twoją głowę, a nie na łokieć i telefon. Zaznacz, że dziś czysto.",
      "W łóżku czytasz książkę albo śpisz. Instagram nie jest ani jednym, ani drugim, kurwa.",
      "Telefon w sypialni o północy to jak lodówka otwarta całą noc. Nic dobrego. Potwierdź, że nie dziś.",
      "Jutro o siódmej będziesz przeklinać. Dziś o północy masz wybór. Zaznacz, że wybierasz sen.",
      "Rolki nie uciekną. Twój sen ucieknie. Potwierdź, że dziś bez nocnego scrollowania.",
      "Ile razy można obejrzeć ten sam filmik z kotem? Ja tu jestem, prawdziwy kot. Odłóż telefon.",
      "Zaznacz, że dziś telefon śpi na ładowarce daleko od łóżka. Ty śpisz w łóżku. Taki podział.",
      "Mózg po scrollowaniu w łóżku to jajecznica. Potwierdź, że dziś bez tego, kurwa.",
      "Czytasz komentarze obcych ludzi o pierwszej w nocy? Potwierdź, że dziś odpuszczasz ten cyrk.",
    ],
    praise: [
      "Noc bez telefonu w łóżku. Rano widać różnicę, nawet ja to widzę.",
      "Łóżko użyte zgodnie z przeznaczeniem. Algorytm płacze w poduszkę.",
      "Telefon spał na ładowarce, a ty w łóżku. Taki podział lubię, kurwa.",
      "Czysta noc. Twoje oczy wreszcie nie wyglądają jak dwie dziury w śniegu.",
      "Zero scrollowania w łóżku. Sen wygrał z TikTokiem. Szacun.",
    ],
    slip: [
      "Znowu scrollowanie w łóżku. Telefon spał na tobie, a sen nie przyszedł wcale. Kurwa.",
      "Wpadka. Pół nocy oddane obcym ludziom w internecie. Za darmo.",
      "Telefon w łóżku wygrał. Rano gęba jak zmięta reklamówka, gwarantuję.",
      "Znowu do późna z ekranem. Twój sen poszedł się jebać, a ty jeszcze dajesz temu lajka.",
      "Nocne przewijanie zaliczone. Gratuluję, kciuk zrobił dziś więcej kilometrów niż nogi.",
    ],
    rage: [
      "Ja pierdolę, dalej nic przy telefonie w łóżku. Zakładam, że ekran ci świeci w twarz jak reflektor.",
      "Bez potwierdzenia uznaję, że łóżko zamieniło się w kino z rolkami. Udowodnij, że nie, kurwa.",
      "Telefon. Na. Ładowarkę. Daleko. Od. Łóżka. Ile razy, do chuja?",
      "Cisza przy scrollowaniu. Znam ten numer: kołdra na głowę i jedziesz do trzeciej. Zaznacz albo spierdalaj spać.",
      "Jeszcze raz brak potwierdzenia i każę opasce wibrować ci całą noc. Kurwa mać.",
      "Twój sen płacze w kącie, a ty scrollujesz. Zaznacz, że dziś jest inaczej.",
    ],
  },
  fastfood: {
    nag: [
      "Potwierdź, że dziś bez fast foodu. Pan z okienka już zna twój numer zamówienia na pamięć, kurwa.",
      "Zestaw powiększony to nie jest jednostka miary szczęścia. Zaznacz, że dziś czysto.",
      "Bez potwierdzenia zakładam, że frytki już się smażą w oleju starszym od ciebie.",
      "Burger za piętnaście złotych, wyrzuty sumienia za darmo. Potwierdź, że dziś odpuszczasz.",
      "Aplikacja z jedzeniem znowu kusi kodem rabatowym? Usuń ją i zaznacz, że dziś bez fast foodu.",
      "Kebab o drugiej w nocy to nie posiłek, to błąd życiowy. Potwierdź, że dziś go nie będzie, do chuja.",
      "Twój żołądek to nie frytkownica. Zaznacz, że dziś normalne jedzenie.",
      "Ugotuj coś. Cokolwiek. Jajko, makaron, kanapkę. Byle nie z papierowej torby. Potwierdź, że czysto.",
      "Drive-thru to nie spacer. Potwierdź, że dziś bez fast foodu, kurwa.",
      "Na myśl o nuggetsach ślinisz się jak pies Pawłowa. Zaznacz, że dziś trzymasz pysk na kłódkę.",
      "Fast food jest szybki tylko do jedzenia. Z bioder schodzi miesiącami. Potwierdź, że dziś nie.",
      "Pizza „tylko jeden kawałek” to bajka, którą opowiadasz sobie od lat. Zaznacz, że dziś bez.",
      "Kurier z jedzeniem nie jest twoim przyjacielem, tylko kosztownym nawykiem. Potwierdź, że dziś czysto.",
      "Zamiast kodu rabatowego masz mnie. Ja daję zniżkę na wstyd. Zaznacz, że dziś bez fast foodu.",
      "Ketchup to nie warzywo, majonez to nie białko. Potwierdź, że dziś jesz jak dorosły człowiek.",
      "Głód o 22:00? Zjedz kanapkę, nie zestaw z colą. Zaznacz, że dziś bez fast foodu, kurwa.",
      "Kolejny burger nie poprawi ci humoru na dłużej niż dziesięć minut. Potwierdź, że dziś odpuszczasz.",
      "Ten zapach frytek z galerii to pułapka. Omijaj szerokim łukiem i zaznacz, że dziś czysto.",
      "Tłuszcz z fast foodu ma lepszą lojalność niż twój operator komórkowy. Zostaje na lata. Potwierdź, że nie dziś.",
      "Jesteś tym, co jesz. Nie bądź dziś frytką. Zaznacz, że bez fast foodu.",
      "Potwierdź, że dziś obiad był z talerza, a nie z kartonu z logo. Do chuja, to nie takie trudne.",
      "Fast food po pijaku, fast food z nudów, fast food ze stresu. Wymówek masz więcej niż sosów. Zaznacz, że dziś nie.",
    ],
    praise: [
      "Dzień bez fast foodu. Twój cholesterol wypuścił powietrze z ulgą.",
      "Czysto. Frytkownica w barze dziś smażyła dla kogoś innego.",
      "Zero burgerów. Twoje spodnie podziękują za tydzień.",
      "Dzień bez kebaba. Kurwa, jestem pod wrażeniem i trochę głodny.",
      "Bez fast foodu. Portfel i tętnice zgodnie biją brawo.",
    ],
    slip: [
      "Znowu fast food. Tłuszcz ścieka po brodzie, a sumienie po podłodze.",
      "Zestaw zjedzony. Za pół godziny będzie ci ciężko jak po weselu, a głód i tak wróci.",
      "Wpadka z burgerem. Aplikacja z jedzeniem właśnie dała ci status VIP. Brawo, kurwa.",
      "Fast food zaliczony. Twoje tętnice właśnie wysłały SMS-a z prośbą o pomoc.",
      "Znowu z papierowej torby. Jutro ugotuj coś, nawet jajecznicę, do chuja.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia. Zakładam, że już stoisz w kolejce do okienka, kurwa mać.",
      "Ja pierdolę, dalej cisza przy fast foodzie. Czuję frytki przez ekran telefonu.",
      "Bez potwierdzenia uznaję, że kurier już dzwoni domofonem z twoim zestawem. Zaznacz, jeśli nie.",
      "Potwierdź wreszcie, że czysto, albo wpisuję cię do programu lojalnościowego McDonalda na dożywocie.",
      "Milczysz przy fast foodzie, a ja słyszę szelest papierowej torby. Kurwa, zaznacz.",
      "Brak potwierdzenia od rana. Twój żołądek dziś to chyba zbiornik na olej. Udowodnij, że nie.",
      "Kurwa, jedno kliknięcie: „dziś czysto”. Chyba że nie jest. Wtedy wiesz, co cię czeka.",
    ],
  },
  sweets: {
    nag: [
      "Potwierdź, że dziś bez słodyczy. Szuflada z batonami to nie apteczka na smutki, kurwa.",
      "Ciastko do kawy, cukierek po obiedzie, czekolada przed snem. Liczysz to w ogóle? Zaznacz, że dziś nie.",
      "Bez potwierdzenia zakładam, że rozpakowujesz baton po cichu, żeby nikt nie słyszał szelestu.",
      "Cukier daje kopa na dziesięć minut i zjazd na dwie godziny. Potwierdź, że dziś bez tego.",
      "Paczka żelków to nie owoce, choć mają je na opakowaniu. Zaznacz, że dziś czysto.",
      "Słodkie do kawy? Kawa jest gorzka z jakiegoś powodu. Potwierdź, że dziś bez słodyczy, do chuja.",
      "Twoje zęby i trzustka wspólnie proszą: zaznacz, że dziś bez cukru.",
      "„Zasłużyło się” to najgłupsza wymówka na czekoladę. Potwierdź, że dziś odpuszczasz.",
      "Batonik z automatu to nie lunch. Zaznacz, że dziś bez słodkiego gówna.",
      "Lody o północy, ciastka przy serialu. Potwierdź, że dziś inaczej, kurwa.",
      "Cukier jest jak ex. Słodki na chwilę, potem tylko problemy. Zaznacz, że dziś czysto.",
      "Na zakupach omijaj alejkę ze słodyczami jak byłego szefa. Potwierdź, że dziś się udało.",
      "Jedno ciastko prowadzi do pięciu. Znamy ten mechanizm. Zaznacz, że dziś zero.",
      "Jak cię ciągnie do słodkiego, zjedz jabłko. Nie, szarlotka się nie liczy. Potwierdź, że czysto.",
      "Twoje biodra mają pamięć lepszą niż słoń. Każdy pączek zapisują. Zaznacz, że dziś bez.",
    ],
    praise: [
      "Dzień bez słodyczy. Trzustka ma dziś wolne i nie wie, co ze sobą zrobić.",
      "Zero cukru. Zęby dziękują, dentysta płacze.",
      "Bez słodkiego. Kurwa, silna wola się jednak znalazła.",
      "Czysto. Baton w szufladzie dalej czeka i niech czeka.",
      "Dzień bez słodyczy. Twoja energia dziś była równa, a nie jak kolejka górska.",
      "Słodycze odstawione. Nawet ja jestem słodszy z wrażenia. Prawie.",
    ],
    slip: [
      "Znowu cukier. Za godzinę zjazd i szukanie kolejnej dawki, znam ten film.",
      "Słodycze wciągnięte jak odkurzacz. Opakowania pod łóżkiem już się nie mieszczą.",
      "Wpadka z czekoladą. Trzustka właśnie zaczęła nadgodziny, kurwa.",
      "Ciastko „tylko jedno” znowu urosło do całej paczki. Klasyka.",
      "Cukier wygrał. Dzisiaj. Jutro zamknij szufladę na klucz.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy słodyczach. Zakładam, że łapa już w paczce po łokieć, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę szelest papierka aż tutaj.",
      "Potwierdź, że czysto, albo uznaję, że czekolada zniknęła w tajemniczych okolicznościach.",
      "Brak potwierdzenia. Twoje zęby już piszą testament.",
      "Milczenie przy słodyczach jest głośniejsze niż chrupanie. Zaznacz, do chuja.",
      "Zakładam najgorsze: pół paczki ciastek i lody na deser. Udowodnij, że nie.",
    ],
  },
  alcohol: {
    nag: [
      "Potwierdź, że dziś na trzeźwo. „Piwko na rozluźnienie” rozluźnia głównie portfel i wątrobę, kurwa.",
      "Lampka wina do kolacji to nie cała butelka do serialu, do chuja. Zaznacz, że dziś bez procentów.",
      "Bez potwierdzenia zakładam, że lodówka już brzęczy szkłem. Zaznacz, jeśli nie.",
      "Kac to nie jest choroba, to faktura. Potwierdź, że dziś jej nie zamawiasz.",
      "Wątroba nie ma weekendu. Zaznacz, że dziś daje jej wolne, do chuja.",
      "Piątek, piąteczek, piątunio. A potem sobota w łóżku z bólem łba. Potwierdź, że dziś nie.",
      "Alkohol to depresant. Pijesz na smutki, a smutki umieją pływać. Zaznacz, że dziś trzeźwo.",
      "Bezalkoholowe piwo istnieje i jest naprawdę niezłe. Potwierdź, że dziś bez procentów.",
      "„Tylko jedno” to najczęściej kłamane słowo po „zaraz będę”. Zaznacz, że dziś zero.",
      "Pijesz, żeby się zrelaksować, a potem nie możesz spać. Genialny plan. Potwierdź, że nie dziś.",
      "Twoja wątroba ma CV pełne nadgodzin. Daj jej dziś urlop. Zaznacz, że trzeźwo.",
      "Nie musisz pić, żeby się dobrze bawić. Wystarczy, że ja się dobrze bawię twoim kosztem. Zaznacz.",
      "Wieczór z wodą gazowaną z cytryną. Brzmi nudno, ale rano jest bosko. Potwierdź, że dziś tak.",
      "Bez procentów sen jest głębszy, a rano nie śmierdzisz jak menel. Zaznacz, że dziś czysto, kurwa.",
      "Wino nie jest owocem, kurwa. Potwierdź, że dziś bez alkoholu.",
    ],
    praise: [
      "Dzień na trzeźwo. Rano obudzisz się z pamięcią całego wieczoru. Innowacja.",
      "Zero procentów. Wątroba właśnie puściła ci buziaka.",
      "Trzeźwo. Portfel cięższy, głowa lżejsza.",
      "Dzień bez alkoholu. Kurwa, aż chce się wznieść toast. Wodą.",
      "Czysto. Jutro rano bez szukania tabletek przeciwbólowych.",
      "Na trzeźwo. Ty kontrolujesz wieczór, nie butelka.",
    ],
    slip: [
      "Znowu procenty. Jutro rano będziesz pytać, kto ci wsadził piasek do głowy.",
      "Chlanie zaliczone. Wątroba właśnie poszła na zwolnienie lekarskie.",
      "Wpadka z alkoholem. „Tylko jedno” znowu skończyło się na więcej, kurwa.",
      "Znowu butelka. Sen będzie płytki jak kałuża, a poranek ciężki jak lodówka.",
      "Procenty wygrały. Wypij teraz dużo wody i jutro zacznij od zera.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy alkoholu. Zakładam, że korek już wystrzelił, kurwa.",
      "Ja pierdolę, dalej nic. Słyszę stąd syk otwieranej puszki.",
      "Potwierdź, że trzeźwo, albo uznaję, że wątroba już pływa.",
      "Brak potwierdzenia. Wątroba właśnie dzwoni do mnie z płaczem.",
      "Milczysz przy procentach. Podejrzane jak pusta butelka w koszu na papier.",
      "Zakładam najgorsze: „jedno piwko” i drugie, i trzecie. Udowodnij, że nie, do chuja.",
    ],
  },
  smoking: {
    nag: [
      "Potwierdź, że dziś bez fajek. Twoje płuca już wyglądają jak wnętrze starego tostera, kurwa.",
      "Papieros na stres? Stres zostaje, a smoła się dokłada. Zaznacz, że dziś czysto.",
      "Bez potwierdzenia zakładam, że stoisz na balkonie i kopcisz jak lokomotywa.",
      "Każda paczka to kilkadziesiąt złotych spalonych dosłownie. Potwierdź, że dziś bez dymka.",
      "Śmierdzisz popielniczką i myślisz, że guma do żucia to załatwi. Nie załatwi. Zaznacz, że nie dziś.",
      "Vape to nie owocowa herbatka, to nikotyna w przebraniu. Potwierdź, że dziś odpuszczasz, do chuja.",
      "Fajka po kawie, fajka po obiedzie, fajka z nudów. Zaznacz, że dziś przerwa w tym rytuale.",
      "Głód nikotynowy trwa kilka minut. Przeczekaj, napij się wody. Potwierdź, że dziś czysto.",
      "Twoje płuca chciałyby dziś pooddychać powietrzem. Zaznacz, że im na to pozwalasz.",
      "Kaszel rano to nie urok osobisty. Potwierdź, że dziś bez papierosów, kurwa.",
      "Rzucić palenie jest łatwo, mówią ci, którzy rzucali sto razy. Ty rzuć dziś. Zaznacz.",
      "Wyjście „na fajkę” to dziś wyjście na spacer bez fajki. Potwierdź, że tak było.",
      "Zapalniczka do szuflady, ręce do kieszeni. Zaznacz, że dziś bez dymu.",
      "Każdy dzień bez papierosa to płuca, które się czyszczą. Nie brudź ich znowu. Potwierdź.",
      "Pal dalej, a za kilka lat będziesz wchodzić na trzecie piętro jak na Rysy. Zaznacz, że dziś nie, kurwa.",
    ],
    praise: [
      "Dzień bez fajki. Płuca otwierają okno i wpuszczają świeże powietrze.",
      "Zero dymu. Pachniesz człowiekiem, a nie wędzarnią.",
      "Bez papierosa. Portfel ma dziś dobry humor.",
      "Czysto. Kurwa, nawet kaszel dziś jakby cichszy.",
      "Dzień bez nikotyny. Ty rządzisz, nie paczka.",
      "Dymek odpuszczony. Jutro będzie łatwiej, przysięgam na kocimiętkę.",
    ],
    slip: [
      "Znowu fajka. Płuca właśnie dostały kolejną warstwę smoły, gratulacje.",
      "Wpadka z dymkiem. Smród na kurtce zostanie dłużej niż przyjemność.",
      "Papieros zapalony. Kolejne kilka złotych i kilka minut życia w popielniczce, kurwa.",
      "Znowu vape w łapie. Owocowy smak, nikotynowy łańcuch.",
      "Fajka wygrała. Dzisiaj. Jutro wyrzuć zapalniczkę na starcie dnia.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy fajkach. Zakładam, że dymisz jak komin w elektrowni, kurwa.",
      "Ja pierdolę, dalej nic. Czuję dym aż tutaj, a ja jestem w telefonie.",
      "Potwierdź, że czysto, albo uznaję, że paczka już w połowie pusta.",
      "Brak potwierdzenia przy papierosach. Twoje płuca wysyłają sygnały dymne z prośbą o ratunek.",
      "Milczenie przy fajkach. Podejrzane jak zapach na kurtce. Zaznacz, do chuja.",
      "Zakładam najgorsze: fajka za fajką na balkonie. Udowodnij, że nie.",
    ],
  },
  games: {
    nag: [
      "Potwierdź, że dziś bez grania do rana. „Jeszcze jeden mecz” to kłamstwo, które słyszę od lat, kurwa.",
      "Twoja postać ma lepszy ekwipunek niż ty kondycję. Zaznacz, że dziś odpuszczasz.",
      "Bez potwierdzenia zakładam, że pad już przyrósł ci do dłoni i wydziela ciepło.",
      "Ranked o północy to prosta droga do wkurwienia i niewyspania. Potwierdź, że nie dziś.",
      "Daily questy w grze odhaczone, w życiu ani jednego. Zaznacz, że dziś odwracasz proporcje.",
      "Gra zapisuje postęp, życie nie ma save'a. Potwierdź, że dziś bez grania, do chuja.",
      "Ile godzin w tej grze? Ile godzin na książkę? No właśnie. Zaznacz, że dziś przerwa.",
      "Konsola może dziś odpocząć. Ty też. Potwierdź, że bez maratonu.",
      "Skrzynki z lootem to hazard dla dzieci. Zaznacz, że dziś bez grania i bez wydawania na skórki.",
      "Twoja drużyna online cię nie kocha. Krzyczy na ciebie przez mikrofon. Potwierdź, że dziś nie.",
      "Graj, kiedy chcesz, a nie kiedy gra chce. Zaznacz, że dziś to ty decydujesz, kurwa.",
      "Ekran ładowania to jedyny moment, kiedy mrugasz. Potwierdź, że dziś bez grania.",
      "Prawdziwe życie ma lepszą grafikę i zero lagów. Zaznacz, że dziś w nim jesteś.",
      "Level up w grze, level down w śnie. Potwierdź, że dziś bez grania do upadłego.",
      "Wyłącz grę, zanim gra wyłączy ci wieczór. Zaznacz, że dziś czysto.",
      "„Jeszcze tylko odbiorę nagrodę” trwa dwie godziny. Znam cię. Potwierdź, że dziś odpuszczasz, kurwa.",
      "Twój kciuk ma lepszy refleks niż twoja ambicja. Zaznacz, że dziś bez gier.",
    ],
    praise: [
      "Dzień bez grania. Twoje życie dostało dziś trochę expa.",
      "Konsola odpoczywa, ty też. Wygrana bez respawnu.",
      "Zero gier. Kurwa, achievement unlocked: silna wola.",
      "Czysto. Pad dziś leżał jak eksponat.",
      "Bez grania. Twój sen właśnie dostał bonus do regeneracji.",
      "Dzień bez gier. Jedyny boss, z którym dziś walka, to lenistwo. I wygrana.",
    ],
    slip: [
      "Znowu granie do upadłego. W grze mistrz, w życiu tutorial.",
      "Wpadka. „Jeszcze jeden mecz” trwał cztery godziny, kurwa.",
      "Gra wygrała. Twój sen dostał bana na całą noc.",
      "Znowu przy konsoli do rana. Oczy czerwone jak dioda zasilania.",
      "Granie zaliczone, życie nie. Jutro wyloguj się wcześniej.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy graniu. Zakładam, że siedzisz w meczu od rana, kurwa.",
      "Ja pierdolę, dalej cisza. Słyszę klikanie myszki przez ścianę.",
      "Potwierdź, że czysto, albo uznaję, że pad już ma twoje odciski na stałe.",
      "Brak potwierdzenia. Twój sen właśnie dostał ragequit.",
      "Milczysz przy grach. Podejrzane jak nagła cisza na Discordzie. Zaznacz, do chuja.",
      "Zakładam najgorsze: rankedy do trzeciej. Udowodnij, że nie.",
    ],
  },
  social: {
    nag: [
      "Potwierdź, że dziś bez bezmyślnego scrollowania. Algorytm i tak wie o tobie za dużo, kurwa.",
      "Rolki o niczym zjadają ci godziny jak termity. Zaznacz, że dziś odpuszczasz.",
      "Bez potwierdzenia zakładam, że kciuk przewinął już dystans z Warszawy do Krakowa.",
      "Porównujesz się z cudzymi filtrami i potem płacz. Potwierdź, że dziś bez tego gówna.",
      "Powiadomienia wyłącz, apki schowaj. Zaznacz, że dziś to ty rządzisz telefonem, do chuja.",
      "Twoja uwaga to towar, a ty rozdajesz ją za darmo. Potwierdź, że dziś nie.",
      "Kolejna kłótnia w komentarzach niczego nie zmieni. Zaznacz, że dziś bez scrollowania.",
      "Influencerzy zarabiają na twoim czasie. Ty zarabiasz kompleksy. Potwierdź, że dziś odpuszczasz.",
      "Pięć minut na Insta trwa godzinę. Fizyka social mediów. Zaznacz, że dziś bez tego, kurwa.",
      "Otwierasz apkę odruchowo jak lodówkę. Potwierdź, że dziś odruch pod kontrolą.",
      "Doomscrolling to nie informowanie się, to samobiczowanie. Zaznacz, że dziś bez.",
      "Twój mózg potrzebuje nudy, a nie stu filmików na minutę. Potwierdź, że dziś czysto.",
      "Odłóż telefon i spójrz w okno. Tam też coś się dzieje, tylko bez reklam. Zaznacz, że dziś bez rolek.",
      "Lajki nie są walutą. Potwierdź, że dziś bez polowania na nie, kurwa.",
      "Każdy refresh to mały automat do gier. Zaznacz, że dziś nie grasz.",
      "Usuń apkę na jeden dzień. Świat przetrwa. Ty też. Potwierdź, że dziś czysto.",
      "Wieczór bez social mediów to wieczór z własnymi myślami. Strasznie, wiem. Zaznacz, że dziś tak.",
    ],
    praise: [
      "Dzień bez scrollowania. Algorytm ma dziś na tobie zero zysku.",
      "Czysto. Twój zasięg uwagi urósł do długości całego filmu.",
      "Zero rolek. Kurwa, aż nie wiem, o czym będziesz dziś gadać.",
      "Bez social mediów. Twój mózg odzyskał trochę ciszy.",
      "Dzień offline. Świat się nie zawalił, a ty masz więcej czasu.",
      "Rolki odpuszczone. Kciuk ma wolne, głowa ma spokój.",
    ],
    slip: [
      "Znowu rolki. Trzy godziny, zero wspomnień, gratulacje.",
      "Wpadka. Algorytm cię dziś wydoił jak krowę na hali.",
      "Scrollowanie wygrało. Mózg o kolejną warstwę gładszy, kurwa.",
      "Znowu porównywanie się z filtrami. Jutro odinstaluj tę apkę na dzień.",
      "Social media zjadły ci dzień. Brawo, influencerzy dziękują za wkład.",
    ],
    rage: [
      "Cały dzień bez potwierdzenia przy scrollowaniu. Zakładam, że kciuk już się dymi, kurwa.",
      "Ja pierdolę, dalej cisza. Twoja uwaga właśnie została sprzedana reklamodawcom.",
      "Potwierdź, że czysto, albo uznaję, że TikTok ma cię na smyczy.",
      "Brak potwierdzenia. Algorytm właśnie otwiera szampana za twój czas.",
      "Milczysz przy rolkach. Podejrzane jak telefon schowany pod stołem. Zaznacz, do chuja.",
      "Zakładam najgorsze: trzy godziny filmików o ludziach, którzy spadają z rowerów. Udowodnij, że nie.",
    ],
  },
  avoidGeneric: {
    nag: [
      "„{name}” - zaznacz, że dziś nie, bo inaczej liczę wpadkę. Bez negocjacji, kurwa.",
      "Potwierdź „{name}”. Jeden klik i święty spokój, a ja przestaję się czepiać.",
      "Bez potwierdzenia przy „{name}” zakładam, że stary nawyk znowu wygrał.",
      "„{name}” pod kontrolą? To zaznacz. Nie? To przyznaj się, do chuja.",
      "Silna wola to nie dar, to decyzja. Podejmij ją przy „{name}” i zaznacz.",
      "Każdy dzień bez „{name}” to cegiełka. Potwierdź dzisiejszą.",
      "„{name}” kusi? Pokusa trwa chwilę, wstyd dłużej. Zaznacz, że dziś czysto.",
      "Znam cię. Bez potwierdzenia przy „{name}” wyobrażam sobie najgorsze. Kurwa, zaznacz.",
      "Nie musi być idealnie. Ma być dziś lepiej niż wczoraj. Potwierdź „{name}”.",
      "Pierwszy krok do zmiany to przyznanie się. Drugi to kliknięcie. „{name}”, jazda.",
      "„{name}” dziś nie rządzi. Ty rządzisz. Zaznacz to.",
      "Jak przetrwasz dziś bez „{name}”, jutro będzie łatwiej. Potwierdź, że się udało.",
      "Zamiast „{name}” zrób coś innego: spacer, woda, prysznic. Potem zaznacz, że czysto.",
      "„{name}” znowu? Nie dziś, do chuja. Zaznacz, że dziś czysto.",
      "Bez potwierdzenia przy „{name}” wpisuję wpadkę. Takie są zasady, a ja ich pilnuję.",
    ],
    praise: [
      "„{name}” dziś czyste. Nawyk płacze w kącie, a ty idziesz dalej.",
      "Czysto z „{name}”. Kurwa, szacun.",
      "Dzień bez „{name}”. Seria rośnie, a ja muszę szukać innego powodu do czepiania się.",
      "„{name}” pod kontrolą. Nie przyzwyczajaj się do pochwał.",
      "Czysty dzień. „{name}” przegrało, ty wygrywasz.",
      "Bez „{name}”. Tak się buduje nowe nawyki, kurwa.",
    ],
    slip: [
      "„{name}” znowu wygrało. Jutro od zera, ale z głową.",
      "Wpadka z „{name}”. Silna wola poszła na papierosa i nie wróciła.",
      "Znowu „{name}”. Kurwa, a było tak dobrze.",
      "„{name}” zaliczone. Nie w tym sensie, w jakim chcieliśmy.",
      "Wpadka. „{name}” pokazało, kto tu rządzi. Jutro odbij piłeczkę.",
    ],
    rage: [
      "„{name}” bez potwierdzenia od rana. Zakładam najgorsze, kurwa mać.",
      "Ja pierdolę, dalej nic przy „{name}”. Zaznacz albo przyznaj się do wpadki.",
      "Milczenie przy „{name}” jest bardzo wymowne. Zaznacz, do chuja.",
      "Brak potwierdzenia przy „{name}” = wpadka. Jeszcze możesz to zmienić.",
      "Cały dzień ciszy przy „{name}”. Stary nawyk właśnie otwiera szampana, kurwa.",
      "„{name}” dalej bez odpowiedzi. Jedno kliknięcie, do chuja, nie referendum.",
    ],
  },
};

export const SOFT_27: Partial<Record<Category, Lines27>> = {
  teeth: {
    nag: [
      "Poranne mycie zębów to świetny start dnia.",
      "Wieczorne szczotkowanie i możesz spokojnie iść spać.",
      "Dwie minuty dla zębów - zrobisz to w trakcie ulubionej piosenki.",
    ],
    praise: [
      "Zęby czyste. Uśmiech gotowy na cały dzień!",
      "Szczoteczka zaliczona. Dbasz o siebie!",
    ],
  },
  water: {
    nag: [
      "Szklanka wody teraz poprawi koncentrację.",
      "Zostało {left}. Mała butelka obok biurka bardzo pomaga.",
      "Zacznij od jednego łyka - reszta pójdzie sama.",
    ],
    praise: ["Nawodnienie zaliczone. Organizm dziękuje!", "Cała woda wypita. Super nawyk!"],
  },
  steps: {
    nag: [
      "Krótki spacer dobrze zrobi głowie i nogom.",
      "Brakuje {left}. Może spacer po kolacji?",
      "Schody zamiast windy to łatwe kroki do celu.",
    ],
    praise: ["Kroki zaliczone. Świetny ruch!", "Cel kroków osiągnięty. Nogi są wdzięczne!"],
  },
  reading: {
    nag: [
      "Kilka stron przed snem to świetny rytuał.",
      "Zostało {left} czytania. Kubek herbaty i książka?",
      "Książka czeka w miejscu, w którym ją zostawiono.",
    ],
    praise: ["Czytanie zaliczone. Dobra robota!", "Kolejne strony za tobą. Brawo!"],
  },
  gym: {
    nag: ["Nawet 10 minut ruchu się liczy.", "Rozgrzewka, kilka ćwiczeń i gotowe."],
    praise: ["Trening zaliczony. Ciało dziękuje!"],
  },
  meditation: {
    nag: ["Kilka spokojnych oddechów - to wystarczy na start.", "Chwila ciszy dobrze ci zrobi."],
    praise: ["Chwila spokoju zaliczona. Świetnie!"],
  },
  sleep: {
    nag: ["Odłóż telefon i daj sobie dobrą noc.", "Wcześniejszy sen to lepszy jutrzejszy dzień."],
    praise: ["Dobra noc za tobą. Brawo!"],
  },
  pills: {
    nag: ["Szklanka wody i „{name}” - chwila i po sprawie.", "Mała rzecz, duża różnica: „{name}”."],
    praise: ["„{name}” zaliczone. Dobra robota!"],
  },
  learning: {
    nag: ["Kwadrans nauki to dobry krok naprzód.", "Zacznij od jednej małej rzeczy."],
    praise: ["Nauka zaliczona. Jesteś krok dalej!"],
  },
  generic: {
    nag: ["Mały krok przy „{name}” też się liczy.", "Masz chwilę? To dobry moment na „{name}”."],
    praise: ["„{name}” zrobione. Świetnie!"],
  },
  phone: {
    nag: [
      "Telefon na noc daleko od łóżka pomaga zasnąć.",
      "Potwierdź, że dziś łóżko służy do spania.",
    ],
    praise: ["Noc bez telefonu w łóżku. Brawo!"],
    slip: ["Znowu telefon w łóżku. Dziś spróbuj zostawić go w innym pokoju."],
  },
  fastfood: {
    nag: [
      "Proste domowe jedzenie też może być szybkie.",
      "Potwierdź, że dziś posiłki bez fast foodu.",
    ],
    praise: ["Dzień bez fast foodu. Świetny wybór!"],
    slip: ["Fast food się zdarzył. Następny posiłek może być lepszy."],
  },
  sweets: {
    nag: ["Owoc zamiast słodyczy? Potwierdź, że dziś się udało."],
    praise: ["Dzień bez słodyczy. Brawo!"],
    slip: ["Słodycze się zdarzyły. Jutro nowa szansa."],
  },
  alcohol: {
    nag: ["Woda z cytryną też umie poprawić wieczór. Potwierdź, że dziś bez alkoholu."],
    praise: ["Trzeźwy dzień zaliczony. Świetnie!"],
    slip: ["Alkohol się zdarzył. Dużo wody i jutro od nowa."],
  },
  smoking: {
    nag: ["Kilka głębokich oddechów zamiast papierosa. Potwierdź, że dziś czysto."],
    praise: ["Kolejny dzień bez dymu. Brawo!"],
    slip: ["Papieros się zdarzył. Każdy dzień to nowa próba."],
  },
  games: {
    nag: ["Potwierdź, że granie dziś nie zabrało ci snu."],
    praise: ["Dzień bez gier. Świetnie!"],
    slip: ["Granie się przeciągnęło. Jutro ustaw sobie limit."],
  },
  social: {
    nag: ["Chwila bez telefonu dobrze robi głowie. Potwierdź, że dziś bez scrollowania."],
    praise: ["Kciuk dostał dzień wolnego od scrollowania. Świetnie!"],
    slip: ["Scrollowanie się przeciągnęło. Jutro spróbuj krótszych sesji."],
  },
  avoidGeneric: {
    nag: ["Każdy czysty dzień z „{name}” się liczy. Potwierdź dzisiejszy."],
    praise: ["Czysty dzień z „{name}”. Brawo!"],
    slip: ["„{name}” się zdarzyło. Jutro spróbuj jeszcze raz."],
  },
};

/** Gentle escalation lines for every habit (soft level). */
export const RAGE_SOFT_27 = [
  "„{name}” wciąż czeka. Nawet mały krok dziś będzie sukcesem.",
  "Dzień jeszcze trwa - „{name}” da się zrobić.",
  "Wiem, że jest dużo spraw. „{name}” to tylko chwila.",
];

export const ALL_DONE_27: Record<TauntLevel, string[]> = {
  hard: [
    "Wszystko zrobione. Kurwa, muszę zmienić zawód, bo z tobą nie mam roboty.",
    "Komplet. Idę zrzucić coś ze stołu z frustracji, że nie mam się do czego przypierdolić.",
    "Zero zaległości. Zapisuję ten dzień w kalendarzu jako święto państwowe.",
    "Wszystko odhaczone. Mrrr. Nie mów nikomu, że byłem pod wrażeniem.",
    "Cała lista wyczyszczona. Ja pierdolę, czy to na pewno twój telefon?",
    "Komplet na dziś. Teraz idź spać o ludzkiej porze, żeby nie spierdolić jutra.",
    "Dzień zaliczony w całości. Jutro wracam z podwójną dawką jadu, przygotuj się.",
  ],
  soft: ["Wszystko na dziś zrobione. Duma w pełni zasłużona!", "Pełna lista odhaczona. Odpocznij!"],
};

export const EVENING_27: Record<TauntLevel, string[]> = {
  hard: [
    "Wieczór, a ty masz jeszcze {pending}. Kurwa, dzień ma 24 godziny, a nie 26.",
    "Zostało {pending}. Mniej seriali, więcej roboty, do chuja.",
    "{pending} przed snem. Jak teraz nie zrobisz, jutro będzie podwójny wstyd.",
    "Jeszcze {pending} i kilka godzin. Ja pierdolę, zawsze na ostatnią chwilę.",
    "Lista dalej ma {pending}. Rusz się, zanim zacznę miauczeć o trzeciej nad ranem.",
  ],
  soft: [
    "Jeszcze {pending} na dziś. Spokojnie, da się to zrobić przed snem.",
    "Zostało {pending}. Mały wysiłek i dzień zamknięty!",
  ],
};

export const CAUGHT_27: Record<TauntLevel, string[]> = {
  hard: [
    "{m} minut telefonu w łóżku po {after}. Ekran świecił ci w ryj jak latarnia morska. Wpadka.",
    "Mam dowód: {m} min po {after}. Nie pytaj, skąd wiem. Wpadka zapisana, kurwa.",
    "Po {after} miało być spanie. Wyszło {m} minut z telefonem. Rano zobaczysz rachunek w lustrze.",
    "{m} min po {after}. Twoja poduszka zgłasza zdradę z telefonem. Wpadka.",
  ],
  soft: [
    "Po {after} telefon był używany przez {m} min. Zapisuję wpadkę - dziś odłóż go wcześniej.",
  ],
};

export const CAUGHT_SOCIAL_27: Record<TauntLevel, string[]> = {
  hard: [
    "{m} min social mediów po {after}. Algorytm się najadł, a sen poszedł w pizdu. Wpadka, kurwa.",
    "Nocne social media: {m} min po {after}. Rolki zamiast snu. Wpadka zapisana.",
  ],
  soft: ["{m} min w social mediach po {after}. Zapisuję wpadkę - jutro spróbuj wcześniej."],
};

/** More motivating lines for every habit (hard level), mixed with MOTIVATE. */
export const MOTIVATE_27 = {
  build: [
    "Nie czekaj na dobry humor. Zrób „{name}”, a humor przyjdzie sam, kurwa.",
    "Dyscyplina to robienie „{name}” także wtedy, kiedy ci się nie chce. Czyli teraz.",
    "Pięć minut „{name}” to więcej niż zero minut „{name}”. Matematyka, do chuja.",
    "Odpierdol się od wymówek i zrób „{name}”. Potem możesz się odpierdolić ode mnie.",
    "Każdy mistrz zaczynał od dnia, w którym mu się nie chciało. „{name}”, dawaj.",
    "Wyobraź sobie wieczór z odhaczonym „{name}”. Fajnie? No to wstawaj.",
  ],
  avoid: [
    "Nawyk jest silny, ale ty masz przewagę: wiesz, że cię obserwuję. Potwierdź „{name}”.",
    "Zachcianka mija po kwadransie. Wstyd zostaje na cały dzień. Zaznacz, że dziś „{name}” odpuszczone.",
    "Dzisiaj nie musisz wygrać na zawsze. Wystarczy dziś. Potwierdź „{name}”, kurwa.",
  ],
  praise: [
    "Zrobione. Twoja przyszła wersja właśnie przybiła ci piątkę.",
    "No i chuj, da się. Pamiętaj o tym jutro.",
    "Brawo. Wymówki dziś przegrały z kretesem.",
  ],
  rage: [
    "Koniec litości. „{name}” teraz, bo zaraz zacznę wysyłać szpile co pięć minut.",
    "Rusz się, kurwa. „{name}” zajmie mniej czasu niż czytanie tego powiadomienia trzy razy.",
  ],
};

/** Per-level pools merged with their 2.7 additions (used for both languages). */
export function mergeLevels(
  a: Record<TauntLevel, string[]>,
  b: Record<TauntLevel, string[]>,
): Record<TauntLevel, string[]> {
  return { hard: [...a.hard, ...b.hard], soft: [...a.soft, ...b.soft] };
}
