package app.lovable.glow_habit_widget;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.BeforeClass;
import org.junit.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 * Calendar math (busy intervals, free windows, "no jabs during meetings")
 * must match src/lib/calendar.ts: both are checked against
 * tests/calendar-vectors.json (generated by tests/gen-calendar-vectors.ts).
 */
public class CalendarMathTest {
    private static JSONObject vectors;

    @BeforeClass
    public static void load() throws Exception {
        Path p = Paths.get("..", "..", "tests", "calendar-vectors.json");
        vectors = new JSONObject(new String(Files.readAllBytes(p), StandardCharsets.UTF_8));
    }

    private static int[][] intervals(JSONArray a) throws Exception {
        int[][] out = new int[a.length()][];
        for (int i = 0; i < a.length(); i++) {
            JSONArray iv = a.getJSONArray(i);
            out[i] = new int[]{iv.getInt(0), iv.getInt(1)};
        }
        return out;
    }

    private static int[] ints(JSONArray a) throws Exception {
        int[] out = new int[a.length()];
        for (int i = 0; i < a.length(); i++) out[i] = a.getInt(i);
        return out;
    }

    private static void assertIntervals(String msg, int[][] expected, int[][] actual) throws Exception {
        assertEquals(msg, CalendarMath.toString(expected), CalendarMath.toString(actual));
    }

    @Test
    public void mergeVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("merge");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            assertIntervals(v.toString(), intervals(v.getJSONArray("expected")),
                CalendarMath.merge(intervals(v.getJSONArray("list"))));
        }
    }

    @Test
    public void busyVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("busy");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            List<CalendarMath.Event> events = new ArrayList<>();
            JSONArray ev = v.getJSONArray("events");
            for (int j = 0; j < ev.length(); j++) {
                JSONObject e = ev.getJSONObject(j);
                events.add(new CalendarMath.Event(e.getInt("start"), e.getInt("end"), e.getBoolean("allDay"),
                    e.getInt("availability"), e.getBoolean("declined")));
            }
            assertIntervals(v.toString(), intervals(v.getJSONArray("expected")),
                CalendarMath.busy(events, v.getBoolean("allDay"), v.getBoolean("tentative")));
        }
    }

    @Test
    public void freeAfterVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("free");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            assertEquals(v.toString(), v.getInt("expected"),
                CalendarMath.freeAfter(intervals(v.getJSONArray("busy")), v.getInt("minute")));
        }
    }

    @Test
    public void freeWindowVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("windows");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            assertIntervals(v.toString(), intervals(v.getJSONArray("expected")),
                CalendarMath.freeWindows(intervals(v.getJSONArray("busy")), v.getInt("from"), v.getInt("until"),
                    v.getInt("min")));
        }
    }

    @Test
    public void jabAtVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("jab");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            assertEquals(v.toString(), v.getInt("expected"),
                CalendarMath.jabAt(v.getInt("slot"), v.getInt("limit"), intervals(v.getJSONArray("busy")),
                    v.getInt("now"), 60));
        }
    }

    @Test
    public void jabTimesVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("times");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            assertArrayEquals(v.toString(), ints(v.getJSONArray("expected")),
                CalendarMath.jabTimes(ints(v.getJSONArray("slots")), v.getInt("wake"), v.getInt("bedtime"),
                    intervals(v.getJSONArray("busy")), v.getInt("now"), 60));
        }
    }

    @Test
    public void fitVectors() throws Exception {
        JSONArray a = vectors.getJSONArray("fit");
        for (int i = 0; i < a.length(); i++) {
            JSONObject v = a.getJSONObject(i);
            int[] got = CalendarMath.fit(intervals(v.getJSONArray("busy")), v.getInt("now"), v.getInt("until"),
                ints(v.getJSONArray("needs")));
            if (v.isNull("expected")) assertNull(v.toString(), got);
            else assertArrayEquals(v.toString(), ints(v.getJSONArray("expected")), got);
        }
    }

    // ------------------------------------------------------------------
    // "Nie szpiluj w trakcie spotkań" - the slot decision in HabitNotifier.maybeTaunt
    // ------------------------------------------------------------------

    /** The rule before calendars: the latest slot that passed less than 60 min ago. */
    private static int oldRule(int[] slots, int now) throws Exception {
        int slot = -1;
        for (int m : slots) if (m <= now && now - m <= 60) slot = m;
        return slot;
    }

    @Test
    public void withoutMeetingsTheSlotLogicIsUnchanged() throws Exception {
        int[][] none = new int[0][];
        int[][] pairs = {{540, 1320}, {420, 1380}, {600, 60}, {480, 480}, {9 * 60, 22 * 60}};
        for (int[] wb : pairs) {
            for (int n : new int[]{1, 3, 5, 8}) {
                int[] slots = HabitNotifier.tauntSlots(n, wb[0], wb[1]);
                for (int now = 0; now < 24 * 60; now++) {
                    int[] at = CalendarMath.jabTimes(slots, wb[0], wb[1], none, now, 60);
                    assertEquals("n=" + n + " wake=" + wb[0] + " now=" + now, oldRule(slots, now),
                        CalendarMath.firingSlot(slots, at, now));
                }
            }
        }
    }

    @Test
    public void aSlotInsideAMeetingWaitsForItsEnd() throws Exception {
        int[] slots = HabitNotifier.tauntSlots(5, 9 * 60, 22 * 60); // 9:30 .. 21:30
        assertEquals(570, slots[0]);
        int[][] meeting = {{9 * 60, 10 * 60 + 15}}; // 9:00-10:15
        // 9:30 in the meeting: nothing fires
        assertEquals(-1, CalendarMath.firingSlot(slots, CalendarMath.jabTimes(slots, 540, 1320, meeting, 570, 60), 570));
        // the alarm is armed for 10:15
        assertEquals(615, CalendarMath.jabTimes(slots, 540, 1320, meeting, 570, 60)[0]);
        // 10:15: the 9:30 slot fires (its key stays "@570", so it fires once)
        assertEquals(570, CalendarMath.firingSlot(slots, CalendarMath.jabTimes(slots, 540, 1320, meeting, 615, 60), 615));
    }

    @Test
    public void aMeetingUntilTheNextSlotSkipsTheJab() throws Exception {
        int[] slots = HabitNotifier.tauntSlots(5, 9 * 60, 22 * 60); // 570, 750, 930, 1110, 1290
        int[][] longMeeting = {{560, 760}}; // 9:20-12:40, past the 12:30 slot
        int[] at = CalendarMath.jabTimes(slots, 540, 1320, longMeeting, 760, 60);
        assertEquals(-1, at[0]); // no double jab: the 9:30 one is dropped
        assertEquals(760, at[1]); // the 12:30 one waits until 12:40
        assertEquals(750, CalendarMath.firingSlot(slots, at, 760));
    }

    @Test
    public void aMeetingStartingDuringALateAlarmDefersToo() throws Exception {
        int[] slots = {600};
        int[][] meeting = {{620, 680}};
        // MIUI delivered the 10:00 alarm at 10:30, a meeting started 10:20 -> wait for 11:20
        assertEquals(680, CalendarMath.jabTimes(slots, 540, 1320, meeting, 630, 60)[0]);
        assertEquals(-1, CalendarMath.firingSlot(slots, CalendarMath.jabTimes(slots, 540, 1320, meeting, 630, 60), 630));
    }

    @Test
    public void theLastSlotIsCutAtBedtime() throws Exception {
        int[] slots = HabitNotifier.tauntSlots(3, 9 * 60, 22 * 60); // 570, 930, 1290
        int[][] evening = {{1280, 1330}}; // 21:20-22:10
        assertEquals(-1, CalendarMath.jabTimes(slots, 540, 1320, evening, 1300, 60)[2]);
    }

    @Test
    public void slotsAfterMidnightKeepTheirOrder() throws Exception {
        int[] slots = HabitNotifier.tauntSlots(5, 10 * 60, 60); // bedtime 01:00
        int last = slots[slots.length - 1];
        assertEquals(30, last); // 00:30
        int[][] meeting = {{20, 45}}; // 00:20-00:45
        assertEquals(45, CalendarMath.jabTimes(slots, 600, 60, meeting, 30, 60)[slots.length - 1]);
    }

    @Test
    public void untilFollowsQuietHours() throws Exception {
        assertEquals(22 * 60, CalendarMath.until(22 * 60, 9 * 60));
        assertEquals(24 * 60 + 60, CalendarMath.until(60, 9 * 60));
    }

    @Test
    public void hintText() throws Exception {
        assertEquals("Masz 18:10–18:50 wolne - idealne na 30 min.",
            CalendarBusy.hintText(1090, 1130, 30, 1000, false));
        assertEquals("Teraz masz wolne do 15:00 - idealne na 20 min.",
            CalendarBusy.hintText(840, 900, 20, 850, false));
        assertEquals("You're free 18:10–18:50 - perfect for 30 min.",
            CalendarBusy.hintText(1090, 1130, 30, 1000, true));
        assertEquals("00:30", CalendarMath.hhmm(1470));
    }

    @Test
    public void freeAndDeclinedMeetingsDoNotBlock() throws Exception {
        List<CalendarMath.Event> ev = new ArrayList<>();
        ev.add(new CalendarMath.Event(600, 660, false, CalendarMath.AVAIL_FREE, false));
        ev.add(new CalendarMath.Event(700, 760, false, CalendarMath.AVAIL_BUSY, true));
        ev.add(new CalendarMath.Event(0, 1440, true, CalendarMath.AVAIL_BUSY, false));
        ev.add(new CalendarMath.Event(800, 830, false, CalendarMath.AVAIL_TENTATIVE, false));
        assertIntervals("busy", new int[][]{{800, 830}}, CalendarMath.busy(ev, false, true));
    }
}
